### ISSUE TITLE
Inference for Android app

### ISSUE THREAD

**Issue by oldschool69** [pierluigiferrari/ssd_keras#10]
Hi everyone!

Nice job you have done! I've tested it and it's working just fine.

Did you ever try to export the generated model (h5 format) to tensorflow (pb format)  and run it in a Android app?

I'was thinking to do that but no idea where I should start from. 

Any suggestion would be great, 

Flavio

**Comment by pierluigiferrari** [comment]
Hey, sorry for the late reply. I haven't tried that and can't point you in the right direction for that unfortunately.
