### ISSUE TITLE
license limitation

### ISSUE THREAD

**Issue by mtamburrano** [pierluigiferrari/ssd_keras#104]
First of all, congratulation for your awesome work.
Then I would like to know, is it possible to change the license with something more permissive, like Apache V2?
GPL is very restrictive for some use cases....

thank you

**Comment by pierluigiferrari** [comment]
Your use case being that you want to derive proprietary software from this?

I'll think about it, but sure, spontaneously I don't see why not.

**Comment by mtamburrano** [comment]
Yes, I plan to experiment with your code and if everything goes fine is possible that I could include part of it into a release of a proprietary software.
Thank you very much

**Comment by mtamburrano** [comment]
very kind of you, thanks!
In the while I was trying another implementation, if I end up to use yours, I'll let you know

thank you again

**Comment by pierluigiferrari** [comment]
No worries either way!
