### ISSUE TITLE
problem in draw bounding box and writing class text

### ISSUE THREAD

**Issue by mohammad69h94** [pierluigiferrari/ssd_keras#107]
not draw blue bounding box and not writing the text of the label.
i have 2 class.
even when that run the program, predict box is empty!.
following image show result 

![untitled](https://user-images.githubusercontent.com/36889021/39117077-484deefe-46fb-11e8-8f2d-c3ce5f588429.jpg)

**Comment by pierluigiferrari** [comment]
If it doesn't draw any predictions (blue boxes) on the image, that probably means that there just are no predictions.
