### ISSUE TITLE
image width/height

### ISSUE THREAD

**Issue by aupilot** [pierluigiferrari/ssd_keras#11]
Hi Pierluigi,

First, thanks for brilliant well documented implementation of ssd! :)

It seems that there is a little yet annoying bug in image height/width processing. By default you're using 300x300 and it works fine. However, if you set w/h to any uneven values (say 1260x720) then it fails to run.

Cheers
Kirill

**Comment by pierluigiferrari** [comment]
I've just tried running the model with various input sizes (1260x720, among others) and it runs without issue. What type of error are you getting? I suspect you're getting a `ResourcesExhausted` error, indicating that your GPU doesn't have enough memory for this large file size. Try decreasing the batch size.
