### ISSUE TITLE
difference between voc07 and voc07++

### ISSUE THREAD

**Issue by izzandienurrahman** [pierluigiferrari/ssd_keras#110]
first of all, thank you for making this happen, it is awesome and currently, I am doing vehicle counting with video input using these examples.

what is the difference between those two terms?
Thank you

**Comment by pierluigiferrari** [comment]
Thanks, I'm glad it's useful!

"07+12":    Trained on Pascal VOC 2007 trainval and 2012 trainval
"07++12":  Trained on Pascal VOC 2007 trainval, 2007 test, and 2012 trainval

**Comment by izzandienurrahman** [comment]
got it, thank you!
