### ISSUE TITLE
TypeError: arg 5 (closure) must be None or tuple

### ISSUE THREAD

**Issue by Xunzhaocunzi** [pierluigiferrari/ssd_keras#111]
Hi @pierluigiferrari 

After you updated HDF5 in data generator, the SSD7 training model can't load model successfully, and it has error below: 
![capture](https://user-images.githubusercontent.com/32579634/39407591-f1151990-4b8d-11e8-850f-6b85a01acb91.PNG)

Could you have a look at please?

Thank you,

**Comment by pierluigiferrari** [comment]
The data generator and the Keras model have nothing to do with each other. In other words, changes in the data generator cannot affect loading a model.

I just tried loading a model and it works fine for me.

In general, if you open an issue, please bear the following things in mind:
1. Never post screenshots of text. Just copy and paste the text instead. Posting screenshots of text makes no sense and has two disadvantages: First, I cannot copy lines of text from a screenshot. Second, screenshots of text are a tremendous waste of storage space. Imagine how many terabytes of unnecessary screenshots like the one you posted are on GitHub's servers.
2. Always post the full stack trace of an error. You posted two screenshots above, but even both together don't contain the full stack trace.

**Comment by OliverKrajci** [comment]
FYI, @pierluigiferrari and whoever else runs into this, I also ran into OP's issue and the resolution was to do what was outlined in https://github.com/keras-team/keras/issues/6211.

Specifically, manually reinstate the code in this commit to keras\utils\generic_utils.py https://github.com/soaxelbrooke/keras/commit/aaada44607e8f45a13732347f70a2b372ac729b2

Cheers
