### ISSUE TITLE
Couldn't find a tree builder with the features you requested: xml.

### ISSUE THREAD

**Issue by sajjad-askari** [pierluigiferrari/ssd_keras#115]
I wanted to run the ssd300_inference that I'm getting back to this error.
What should I do to solve it?
please guide me.

**Comment by sajjad-askari** [comment]
i run code on colab.research.google with pythone3 and gpu setting.
i install lxml too with pip install lxml.
the error i get is:

FeatureNotFound                           Traceback (most recent call last)
<ipython-input-21-7cb321e66ce9> in <module>()
     26                   exclude_truncated=False,
     27                   exclude_difficult=True,
---> 28                   ret=False)
     29 
     30 convert_to_3_channels = ConvertTo3Channels()

/content/drive/ssd_keras-master/data_generator/object_detection_2d_data_generator.py in parse_xml(self, images_dirs, image_set_filenames, annotations_dirs, classes, include_classes, exclude_truncated, exclude_difficult, ret)
    352                     # Parse the XML file for this image.
    353                     with open(os.path.join(annotations_dir, image_id + '.xml')) as f:
--> 354                         soup = BeautifulSoup(f, 'xml')
    355 
    356                     folder = soup.folder.text # In case we want to return the folder in addition to the image file name. Relevant for determining which dataset an image belongs to.

/usr/local/lib/python3.6/dist-packages/bs4/__init__.py in __init__(self, markup, features, builder, parse_only, from_encoding, exclude_encodings, **kwargs)
    163                     "Couldn't find a tree builder with the features you "
    164                     "requested: %s. Do you need to install a parser library?"
--> 165                     % ",".join(features))
    166             builder = builder_class()
    167             if not (original_features == builder.NAME or

FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

**Comment by pierluigiferrari** [comment]
Hm, try

`pip install et_xmlfile`

If that doesn't work, then I suggest you post this on StackOverflow.

**Comment by sajjad-askari** [comment]
thank you so much.
pip install et_xmlfile was answer.

**Comment by pierluigiferrari** [comment]
Great!

**Comment by Garamda** [comment]
@pierluigiferrari  Thank you very much! I got helped too.

**Comment by Manzoor-Razaak** [comment]
Just an information to help others:

I had the same issue and 
`pip install et_xmlfile` did not work for me.

Below solution worked for me:

```
sudo apt-get install libxslt1-dev libxml2 python-dev
sudo pip3 install --upgrade lxml

```

**Comment by achuuuuu** [comment]
> thank you so much. pip install et_xmlfile was answer.

**Comment by achuuuuu** [comment]
it was not working in jypter notebook.Is there any way to solve this problem
