### ISSUE TITLE
SSD for classification

### ISSUE THREAD

**Issue by tsly123** [pierluigiferrari/ssd_keras#121]
First, thank for your work!
I wonder that how can I use SSD for classification without detection?
For example, input an arbitrary image, the output will be whether this is a image of human or not.
My ultimate goal is to extract good person feature from image for another task.
Thank you.

**Comment by pierluigiferrari** [comment]
That's a bit like asking how you can use a television for sound only, without the images. What would be the point of doing that? The only thing that distinguishes an object detection model from a classification model is the whole machinery for multi-classification and -localization. If you don't need that, then why use an object detection model at all? What you're describing is simple a classification task, so you can just use a classification model.
