### ISSUE TITLE
ValueError: None values not supported.

### ISSUE THREAD

**Issue by ramnithin** [pierluigiferrari/ssd_keras#124]
**When I try to train the model with the custom dataset. I get this issue,**

history = model.fit_generator(generator=train_generator,
                              steps_per_epoch=steps_per_epoch,
                              epochs=final_epoch,
                              callbacks=callbacks,
                              validation_data=val_generator,
                              validation_steps=ceil(val_dataset_size/12),
                              initial_epoch=initial_epoch)

ValueError                                Traceback (most recent call last)
<ipython-input-30-fbff6ac5d46f> in <module>()
     21                               validation_data=val_generator,
     22                               validation_steps=ceil(val_dataset_size/12),
---> 23                               initial_epoch=initial_epoch)

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1959 
   1960         do_validation = bool(validation_data)
-> 1961         self._make_train_function()
   1962         if do_validation:
   1963             self._make_test_function()

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\engine\training.py in _make_train_function(self)
    988                     training_updates = self.optimizer.get_updates(
    989                         params=self._collected_trainable_weights,
--> 990                         loss=self.total_loss)
    991                 updates = self.updates + training_updates
    992                 # Gets loss and metrics. Updates weights at each call.

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\optimizers.py in get_updates(self, loss, params)
    166         self.weights = [self.iterations] + moments
    167         for p, g, m in zip(params, grads, moments):
--> 168             v = self.momentum * m - lr * g  # velocity
    169             self.updates.append(K.update(m, v))
    170 

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variables.py in _run_op(a, *args)
    752     def _run_op(a, *args):
    753       # pylint: disable=protected-access
--> 754       return getattr(ops.Tensor, operator)(a._AsTensor(), *args)
    755     # Propagate __doc__ to wrapper
    756     try:

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py in binary_op_wrapper(x, y)
    883       if not isinstance(y, sparse_tensor.SparseTensor):
    884         try:
--> 885           y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
    886         except TypeError:
    887           # If the RHS is not a tensor, it might be a tensor aware object

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py in convert_to_tensor(value, dtype, name, preferred_dtype)
    834       name=name,
    835       preferred_dtype=preferred_dtype,
--> 836       as_ref=False)
    837 
    838 

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
    924 
    925     if ret is None:
--> 926       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    927 
    928     if ret is NotImplemented:

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    227                                          as_ref=False):
    228   _ = as_ref
--> 229   return constant(v, dtype=dtype, name=name)
    230 
    231 

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name, verify_shape)
    206   tensor_value.tensor.CopyFrom(
    207       tensor_util.make_tensor_proto(
--> 208           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    209   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    210   const_tensor = g.create_op(

~\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    369   else:
    370     if values is None:
--> 371       raise ValueError("None values not supported.")
    372     # if dtype is provided, forces numpy array to be the type
    373     # provided if possible.

ValueError: None values not supported

**Is it because of the custom loss function returning null values, how can it be # resolved?**

**Comment by pierluigiferrari** [comment]
Generate a small batch (maybe batch size 4 or something) and print it out, i.e. print out the shape of the image array and print out the complete labels array.

**Comment by blakete** [comment]
I  am having the same issue, has anyone solved this?
