### ISSUE TITLE
ssd_training.ipynb  error

### ISSUE THREAD

**Issue by RoseLii** [pierluigiferrari/ssd_keras#129]
please help me 
when i run ssd_training.ipynb

model_path='/media/y/2T/wangxingli/TT100K/ssd_keras/trained_weights/SSD300/VGG_VOC0712_SSD_300x300_iter_120000.h5'
ssd_loss = SSDLoss(neg_pos_ratio=3, alpha=1.0)
K.clear_session() # Clear previous models from memory.
model = load_model(model_path, custom_objects={'AnchorBoxes': AnchorBoxes,
                                               'L2Normalization': L2Normalization,
                                               'compute_loss': ssd_loss.compute_loss})
but have error : 
Traceback (most recent call last):
  File "ssd300_training.py", line 160, in <module>
    'compute_loss': ssd_loss.compute_loss})
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 244, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

Please help me. Why?

**Comment by pierluigiferrari** [comment]
As stated clearly in the README, the provided HDF5 files are weight files, not complete models. Hence the error. You can't use them with `load_model()`, you have to build a model and then load them with `model.load_weights()`.
