### ISSUE TITLE
subsample model retrain

### ISSUE THREAD

**Issue by ml-boringtao** [pierluigiferrari/ssd_keras#132]
I successfully subsample ssd300_coco from 80 classes to 3 classess. 
I also successfully use a dataset to train ssd300 from scratch, also the same 3 classes. 

However, when I tried to use the same dataset to train the 3 classes Subsample model, following the exact process of the ssd300 train-from-scratch, only replace the vanilla ssd300 model with the saved subsample model. I got the error message of: ValueError: None values not supported.

Any hint to help find the solution?

Thanks

**Comment by ml-boringtao** [comment]
I think I find the way to do it. I only need to load the subsample weight rather than replacing the model with weight, it seems to work.

**Comment by ml-boringtao** [comment]
I figured it out. Thanks

**Comment by PatrickUtz** [comment]
Did you use a custom dataset? I am trying to use this SSD model to detect traffic cones (only 1 class) and made my own dataset of traffic cone images and annotations.
