### ISSUE TITLE
model output

### ISSUE THREAD

**Issue by RoseLii** [pierluigiferrari/ssd_keras#133]
please help me.I'm going to use a picture to predict, and the input is this
[[[0.961441   0.008545   0.0134002  ... 0.1        0.2        0.2       ]
  [0.9827253  0.0039589  0.00526073 ... 0.1        0.2        0.2       ]
  [0.961668   0.00562329 0.01119104 ... 0.1        0.2        0.2       ]
  ...
  [0.94160825 0.01438702 0.01438924 ... 0.1        0.2        0.2       ]
  [0.9417653  0.01456027 0.01455798 ... 0.1        0.2        0.2       ]
  [0.94153374 0.01396228 0.01396634 ... 0.1        0.2        0.2       ]]]

Has 8732 rows, 17, I know there are 8732 default box each image, and each default box there are 17 output (n_classes + 4 + 8), but I don't quite understand the first column is the output probability of each category, I'm not sure. Because I changed a couple of pictures and it turned out to be the biggest of the first category.

**Comment by pierluigiferrari** [comment]
It's hard to make sense of what you're writing. I don't know what you are trying to do or what the point of this is, but what you pasted above seems to be the raw prediction output for some batch of images. The inner-most nested arrays represent raw box predictions and the first number in each of them is the probability for the respective predicted box being of the class "background", so, of course, for the vast majority of the boxes, this will be the largest probability, because the vast majority of the raw predictions are background predictions.

I still don't understand why you're even looking at the raw output. Just decode it using the provided functions.

**Comment by RoseLii** [comment]
Sorry, I didn't make it clear. My problem is that there are some images in my test set that have no labels, so I want to see the output. So I used prediction  y_pred = model.predict(batch_images)    and I looked at the intermediate results as follows:
y_pred:
    [0:24]:  my batch_size=32,why is 24?
       [0:8732]: I think there are 8732 box per image
           [0:17]:I think it's 5 classes of probability +4 telecoordinate offsets+4 anchor box coordinates+ 4 variances(i have classes),But every picture I get is the biggest 00, why？I think if the first five are the probability of a class, it shouldn't be the biggest one of each picture. It's one of these five。
Because I can't see the output of the background class, I don't know how to modify it without making an error when I detect it. I don't know if I made it clear, please forgive me
How do you decode it, and you end up with no background class, and I looked at the function and didn't quite understand。I'm trying to figure out how to deal with the background, because I think I can deal with it by working with the background class on the untargeted image in the test set.
I don't know if my idea is correct or not. Please give me your Suggestions, or do you have any good ways to deal with this problem? Thank you

**Comment by pierluigiferrari** [comment]
If you're just trying to make predictions it doesn't matter whether a given image in your test set has any ground truth or not. The whole point of training a model is to use it on images for which you don't have any ground truth. You simply feed the image to the model and decode the raw model output according to the instructions in the Jupyter notebooks. Or you build the model in "inference" mode. I still see no reason why you would need to look at the raw model output.

**Comment by RoseLii** [comment]
Thank you for your advice, but how can I do the test now so as not to report any mistakes
