### ISSUE TITLE
SSD512 predicts fewer boxes than SSD300 on the same image

### ISSUE THREAD

**Issue by jozefmorvay** [pierluigiferrari/ssd_keras#135]
I followed the notebook for inference with SSD300, loaded the VGG_VOC0712_SSD_300x300_ft_iter_120000.h5 weights, sent in resized frames from a soccer match, and then put them back together to get a video with all soccer players marked with a box. I did no other pre-processing, as VGG mean subtraction is done by your code in the first lambda layer. This worked just fine, you can see the first video frame here. With classification threshold of 0.5, I get this:

![300](https://user-images.githubusercontent.com/4798190/41256403-c89c4b74-6dc9-11e8-9744-d4295cf6acd8.jpg)

Decent, but could be better, the smaller players in the back of the playground are not recognized. So I used SSD512 instead, again from the inference guide notebook, loaded the correct weights (VGG_VOC0712_SSD_512x512_ft_iter_120000.h5), and did the same thing with the frames. I had hoped for the smaller players to be detected, but instead, the network only recognizes 3 boxes instead of 6 that SSD300 does in the first frame:

![500](https://user-images.githubusercontent.com/4798190/41256538-3036a586-6dca-11e8-9bac-215cc007e77c.jpg)

Interestingly, the white player on the right is marked correctly by SSD512, while he was not with SSD300, but other than that, it's just not right.
This gets slightly better over the course of the video, but the SSD512 version output never reaches number of detections of SSD300. How can this be? I must be missing something trivial, but can't figure it out. The bigger the input, the better the detection should be, yet I observe the opposite.

**Comment by Rampeul** [comment]
You seems to use pascal VOC based learning, have you tried the others (with COCO fine tuning in particular) ? Check this [section](https://github.com/pierluigiferrari/ssd_keras#download-the-original-trained-model-weights) ;) . From my experience, COCO dataset is much more challenging than pascal VOC and network learned from it provide better predictions for person detection.

**Comment by jozefmorvay** [comment]
@Rampeul I haven't tried using pure COCO weights, as it didn't make much sense for me to do so, because:

1. The weights I use are first trained on COCO, then finetuned on VOC 07 and 12 trainval. The weights nomenclature is explained in the original paper.
2. If the SSD300 model works with the weights, there is just no way this SSD512 would not work. This is unrelated to weights, I did wrong something else.

**Comment by pierluigiferrari** [comment]
Yes, I would expect SSD512 to perform strictly better than SSD300. At least it does perform strictly better on any test datasets I've tried (VOC 2007 test, VOC 2012 test).

Note that the weights you loaded require the smaller MS COCO scaling factors, not the Pascal VOC scaling factors, although that wouldn't be able to explain the results above, since this is a classification issue, not a localization issue.

If you just used the `ssd512_inference.ipynb` notebook as is (except for the preset scaling factors), then I have no explanation for what's going on here.

**Comment by jozefmorvay** [comment]
I used everything as is, scaling factors included. I have only limited understanding of what purpose all those input parameters related to anchors serve, so I wouldn't know how the scaling factors can influence the prediction, if at all. I simply assumed that since the weights are finetuned on VOC, I can leave the code as is. I understand that first, all boxes with confidence of lower than 0.01 are filtered out, then in the next step boxes with jaccard overlap of 0.45 and greater are kept and lastly, of those that make it that far, top 200 are chosen. My 200 predicted boxes are, save for the three boxes that are shown in the image, simply zeros, as if there were not even enough predictions saying that there is a person in the anchor.

Is your contact mail in your github profile current?

**Comment by pierluigiferrari** [comment]
> I simply assumed that since the weights are finetuned on VOC, I can leave the code as is.

You cannot. As clearly stated in the README in the section titled "Important notes", any model that was trained on MS COCO requires the MS COCO scaling factors.

> My 200 predicted boxes are, save for the three boxes that are shown in the image, simply zeros, as if there were not even enough predictions saying that there is a person in the anchor.

Well, if you set the confidence threshold to 0.5, of course there aren't going to be 200+ predictions with confidence 0.5 or higher in the image after NMS. The fact that the last stage of the decoding process limits the number of predictions to 200 obviously does not imply that there are necessarily 200 or more predictions left after the previous decoding stages.

> Is your contact mail in your github profile current?

I don't reply to emails regarding my public repositories.

**Comment by jozefmorvay** [comment]
Any idea how to troubleshoot this? The only thing I can think of right now is to run some deconvolutions and see the activations layer per layer and maybe compare the two SSD versions? 

Since until I figure out what the problem is with 512, I am only left with 300 version. I would like to implement feature fusion mentioned in couple of papers to help it better recognize smaller objects, and I wanted you to oversee that effort, that's what email question was for. Papers contemplating feature fusion of some sort:

https://arxiv.org/ftp/arxiv/papers/1709/1709.05054.pdf
https://arxiv.org/pdf/1712.00960.pdf
https://arxiv.org/pdf/1506.04579.pdf

**Comment by pierluigiferrari** [comment]
> Any idea how to troubleshoot this?

Not of the top of my head. If you send over the first frame (attach to this thread) I might try it out myself when I find the time to see if I can reproduce this behavior, which would be a sensible first step.

Regarding the feature fusion SSD: It's a sensible improvement over the vanilla SSD architecture, but I currently don't have the time to get involved in implementing that.

**Comment by jozefmorvay** [comment]
The first frame of the video:

![first_frame](https://user-images.githubusercontent.com/4798190/41455467-913c1be4-707d-11e8-8cbe-5eebb348eac7.jpg)

You don't have to implement anything, I'll do it. You will just review the PR, I suppose.

**Comment by pierluigiferrari** [comment]
> You don't have to implement anything, I'll do it. You will just review the PR, I suppose.

That's what I was talking about, that's still being involved. The back and forth leading up to the merger of a PR and reviewing and testing somebody else's code can take longer than implementing something myself. You can send me a PR whenever you're ready of course, I just wanted you to know that I don't have much time at the moment.

**Comment by jozefmorvay** [comment]
I see. Could you at least please try to do an inference with that frame I posted? I just want to see if you observe the same thing.

**Comment by pierluigiferrari** [comment]
My Ubuntu machine is currently in the shop for repairs, but once I have it back I'll try it.

**Comment by jozefmorvay** [comment]
Not to be a nuisance, but do you have any idea when that machine is coming back from repairs?
