### ISSUE TITLE
Invalid loss,terminating training. loss is nan when using "ssd300_training" to train my own datasets. 

### ISSUE THREAD

**Issue by perry0418** [pierluigiferrari/ssd_keras#136]
39/100 [==========>...................] - ETA: 1:01:16 - loss: nan  
Batch 38: Invalid loss, terminating training

**Comment by pierluigiferrari** [comment]
Just try again. As explained [here](https://github.com/pierluigiferrari/ssd_keras/blob/master/training_summaries/ssd300_pascal_07%2B12_training_summary.md), SGD is unstable at the beginning of the training.
