### ISSUE TITLE
Face detection using ssd300

### ISSUE THREAD

**Issue by conduire** [pierluigiferrari/ssd_keras#137]
### If you open a GitHub issue, here is the policy:
My issue is regarding SSD implementation.
I am new to Deep learning and I do have question regarding SSD 300, so I need help
I have created a Face database in PascalVOC format. I can say that the PascalVOC database I have created is fine, only on the basis that:
 1. it works in ssd300_training.ipynb.
 2. it has all the xml files, with bounding box coordinates for only a single class "face" and all the things needed in xml file. ( since I compared it to the xml files in the original PascalVOC database.

So my question is can this SSD be used to train a new dataset ? if yes then what are the changes to be made?
 (since I have tried training by loading the "VGG_ILSVRC_16_layers_fc_reduced.h5 "  when asked in section 2.1, for 200 epochs. I got good result in validation. But in the inference it is not even able to make a bounding box.)

**Comment by pierluigiferrari** [comment]
> it works in ssd300_training.ipynb.

It's unclear what exactly that means.

> So my question is can this SSD be used to train a new dataset ?

Of course.

> if yes then what are the changes to be made?

Search the old issues, the question of how to adjust the anchor box parameters for a given dataset has been asked and answered multiple times before.

> (since I have tried training by loading the "VGG_ILSVRC_16_layers_fc_reduced.h5 " when asked in section 2.1, for 200 epochs. I got good result in validation. But in the inference it is not even able to make a bounding box.)

This is likely due to some mistake you made somewhere. Be as systematic as possible when you try to debug an object detection model. The first step is to make sure that the dataset is consistent, for example that all objects of a given class are labeled, not just some. The next step is to make sure that the input data is being handled correctly by the data generator, i.e. that the ground truth boxes are where they are supposed to be when you print them onto their respective images.

**Comment by conduire** [comment]
I am sorry for the incorrect wordings I may have used or am going to use
it works in ssd300_training.ipynb. - it means that the SSD 300 was able to train the model using my dataset.


In the ssd300_inference
in section 1.1 - I loaded my trained weights after 120 epochs .
in section 2 - I loaded a new image(not same as training dataset image)
in section 4 - visualize the prediction - There was no predicted box in the image.

in section 5 -Make predictions on Pascal VOC 2007 Test - I filled all the required fields  Image selected randomly by the batch generator has a ground truth box [[  1 181  83 290 192]]  
                                                 and the predicted box is [1.  183.87  83.03 292.65 194.17]]
and there is truth box as well as predicted box on the image . 
What does this mean? what could be the reason behind no predicted box in section 4 and section 5 having a predicted box ?

My dataset only has a single class that is face. And almost all the (1500) images in dataset have a single face in it]

**Comment by pierluigiferrari** [comment]
> in section 2 - I loaded a new image(not same as training dataset image)

But still an image that contains a face and is similar to your training dataset?

> in section 5 -Make predictions on Pascal VOC 2007 Test - I filled all the required fields Image selected randomly by the batch generator has a ground truth box [[ 1 181 83 290 192]]
and the predicted box is [1. 183.87 83.03 292.65 194.17]]
and there is truth box as well as predicted box on the image .

Is that for an image from the training dataset or not from the training dataset?

**Comment by conduire** [comment]
I am sorry there is a slight misunderstanding, I had uploaded my face image instead of the fish image in  section 2. But I did not get any bounding box.
