### ISSUE TITLE
[Not an issue] Question about Scale 1.05

### ISSUE THREAD

**Issue by mikeliao97** [pierluigiferrari/ssd_keras#139]
Hi, thank you for your hard work. I did not find fault in the implementation, so I can understand if you don't answer it.

In the paper, I know they listed scale_min = 0.2, scale_max = 0.9. My understanding is that Scale means "magnification", so 0.2 is looking at a really small part of the image. **Thus, I'm wondering what does a scale of 1.05 do?** This is bigger than the original image, and you can't upsample the original. 

Thanks!

**Comment by pierluigiferrari** [comment]
In its default settings, SSD produces two default/prior/anchor boxes with aspect ratio 1 at each predictor layer, one slightly smaller, the other slightly bigger.

The size of the smaller anchor box is computed using the scaling factor for the respective layer.

The size of the larger anchor box is computed using the geometric mean of the two scaling factors for a given predictor layer and the next larger scaling factor.

Illustrated by the example of the Pascal VOC scaling factors of SSD300:

The scaling factors are `[0.1, 0.2, 0.37, 0.54, 0.71, 0.88, 1.05]`. Note that this list contains 7 scaling factors even though SSD300 only has 6 predictor layers. The scaling factors for the first (most shallow) predictor layer are:

0.1 for the smaller box with aspect ratio 1 and `sqrt(0.1, 0.2) = 0.1414` for the larger one.

The scaling factors for the last (deepest) predictor layer are:

0.88 for the smaller box with aspect ratio 1 and `sqrt(0.88, 1.05) = 0.9612` for the larger one.

That is, the largest scaling factor (1.05) is just chosen such that its geometric mean with the previous scaling factor (0.88) produces a number close to 1.0, and it is only being used for the computation of the size of the second aspect-rario-1 box of the deepest predictor layer.

**Comment by mikeliao97** [comment]
ahh, great. Thank you for the explanation, I really appreciate it.
