### ISSUE TITLE
how to get the ./data/train_labels.csv file

### ISSUE THREAD

**Issue by jinfagang** [pierluigiferrari/ssd_keras#14]
Hi, thanks for this wonderful work. I want test on your ssd7 dataset, I just downloaded the images file from your google drive, but how to get the train_label.csv file? Any link or resource would be very appreciated!!

**Comment by pierluigiferrari** [comment]
Hey, thanks! The CSV file is in the same folder as the images, i.e. you already have it.

**Comment by jinfagang** [comment]
Just find it! Thanks! Sorry for the bother!

**Comment by pierluigiferrari** [comment]
No problem at all!
