### ISSUE TITLE
Alternative to inspect.signature as I'm using python 2

### ISSUE THREAD

**Issue by cyberphantom** [pierluigiferrari/ssd_keras#142]
I'm still exploring the code, I know this is not an issue but I'm seeking for help in my running probem:

I'm running ssd300_inference, everything works well until step:

`# Generate a batch and make predictions.

batch_images, batch_filenames, batch_inverse_transforms, batch_original_images, batch_original_labels = next(generator)

i = 0 # Which batch item to look at

print("Image:", batch_filenames[i])
print()
print("Ground truth boxes:\n")
print(np.array(batch_original_labels[i]))`

It Stops the Iteration and gives the below error
`
AttributeErrorTraceback (most recent call last)
<ipython-input-9-53dae584464a> in <module>()
      1 # Generate a batch and make predictions.
      2 
----> 3 batch_images, batch_filenames, batch_inverse_transforms, batch_original_images, batch_original_labels = next(generator)
      4 
      5 i = 0 # Which batch item to look at

/home/saif/Documents/ssd_keras/data_generator/object_detection_2d_data_generator.pyc in generate(self, batch_size, shuffle, transformations, label_encoder, returns, keep_images_without_gt, degenerate_box_handling)
   1068                         if not (self.labels is None):
   1069 
-> 1070                             if ('inverse_transform' in returns) and ('return_inverter' in inspect.signature(transform).parameters):
   1071                                 batch_X[i], batch_y[i], inverse_transform = transform(batch_X[i], batch_y[i], return_inverter=True)
   1072                                 inverse_transforms.append(inverse_transform)

AttributeError: 'module' object has no attribute 'signature'

`

and when running 

`# Predict.

y_pred = model.predict(batch_images)`

gives the error

`
NameErrorTraceback (most recent call last)
<ipython-input-17-e94627db9e5a> in <module>()
      1 # Predict.
      2 
----> 3 y_pred = model.predict(batch_images)

NameError: name 'batch_images' is not defined

`

**Comment by pierluigiferrari** [comment]
Sorry, as is clearly stated in the README, I don't provide support for Python 2. It's 2018, Python 2 is over. If you insist on running Py2, you could create a Py3 virtual/conda environment and run this implementation from there.

The second error is just a consequence of the first. Obviously `batch_images` is not defined if the batch generation failed.

**Comment by cyberphantom** [comment]
Thanks for your replay, I need python 2.7 because I will run the detector inside ROS indigo which only supports python 2.7 so :(
I'm trying to find away to read the parameters using alternative way.

**Comment by pierluigiferrari** [comment]
I see. In this case, if you use a work-around for the inspect module, the rest of the code should work with Py2 (I think, no guarantees).

**Comment by cyberphantom** [comment]
Do you know what is the data type of "transform" that we are passing here, it is not a function or module, class, method, function, traceback, frame, or code object

**Comment by cyberphantom** [comment]
I found it 
inspect.getargspec(transform.__call__).args

**Comment by cyberphantom** [comment]
Found it

`inspect.getargspec(transform.__call__).args`
