### ISSUE TITLE
Degenerate boxes check doesn't work if keep_images_without_gt = True

### ISSUE THREAD

**Issue by kocurvik** [pierluigiferrari/ssd_keras#143]
I am getting an error on this line:

https://github.com/pierluigiferrari/ssd_keras/blob/3ac9adaf3889f1020d74b0eeefea281d5e82f353/data_generator/object_detection_2d_data_generator.py#L1102

Stack trace:
```
Traceback (most recent call last):
  File "***/train_ssd7_both.py", line 299, in <module>
    batch_images, batch_labels, batch_filenames = next(predict_generator)
  File "***\data_generator\object_detection_2d_data_generator.py", line 841, in generate
    if np.any(batch_y[i][:,xmax] - batch_y[i][:,xmin] <= 0) or np.any(batch_y[i][:,ymax] - batch_y[i][:,ymin] <= 0):
IndexError: too many indices for array
```

It happens when keep_images_without_gt = True. That way some labels are just empty lists. 

I fixed it in my heavily modified version by surpassing degenerate box checking when batch_y[i].size == 0. It might be a bug, but I might just have parsed labels w/o gt boxes in a wrong way.

**Comment by pierluigiferrari** [comment]
Yes, this is a known issue. I'll fix it soon. I haven't put much thought into it yet, but I believe replacing [this line](https://github.com/pierluigiferrari/ssd_keras/blob/3ac9adaf3889f1020d74b0eeefea281d5e82f353/data_generator/object_detection_2d_data_generator.py#L1068) by

`if not (self.labels is None or batch_y[i].size == 0):`

should fix it.

**Comment by halhwadi** [comment]
I got the same error msg (Input has undefined rank)and looks there is no enough details in google about this issue, can someone help me to figure out how to resolve this problem:

Model Code:
def make_model(input_shape, num_classes):
    inputs = keras.Input(shape=input_shape)


    # Entry block
    x = layers.experimental.preprocessing.Rescaling(1.0 / 255)(inputs)
    x = layers.Conv2D(32, 3, strides=2, padding="same")
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    x = layers.Conv2D(64, 3, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    previous_block_activation = x  # Set aside residual

    for size in [128, 256, 512, 728]:
        x = layers.Activation("relu")(x)
        x = layers.SeparableConv2D(size, 3, padding="same")(x)
        x = layers.BatchNormalization()(x)

        x = layers.Activation("relu")(x)
        x = layers.SeparableConv2D(size, 3, padding="same")(x)
        x = layers.BatchNormalization()(x)

        x = layers.MaxPooling2D(3, strides=2, padding="same")(x)

        # Project residual
        residual = layers.Conv2D(size, 1, strides=2, padding="same")(
            previous_block_activation
        )
        x = layers.add([x, residual])  # Add back residual
        previous_block_activation = x  # Set aside next residual

    x = layers.SeparableConv2D(1024, 3, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    x = layers.GlobalAveragePooling2D()(x)
    if num_classes == 2:
        activation = "sigmoid"
        units = 1
    else:
        activation = "softmax"
        units = num_classes

    x = layers.Dropout(0.5)(x)
    outputs = layers.Dense(units, activation=activation)(x)
    return keras.Model(inputs, outputs)


model = make_model(input_shape= (1024,1024,1), num_classes=11)
keras.utils.plot_model(model, show_shapes=True)
