### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal

### ISSUE THREAD

**Issue by cyberphantom** [pierluigiferrari/ssd_keras#145]
I'm following the weight_sampling_tutorial, using weights from VGG_coco_SSD_300x300_iter_400000.h5
WHen running to step 5.2 trying to load the model in 
model.load_weights(weights_path, by_name=True)
I got the error:
 

ValueErrorTraceback (most recent call last)
<ipython-input-12-2f7a46d4adea> in <module>()
     31 weights_path = weights_destination_path
     32 
---> 33 model.load_weights(weights_path, by_name=True)
     34 
     35 print("Weights file loaded:", weights_path)

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in load_weights(self, filepath, by_name, skip_mismatch)
   2641         if by_name:
   2642             load_weights_from_hdf5_group_by_name(
-> 2643                 f, self.layers, skip_mismatch=skip_mismatch)
   2644         else:
   2645             load_weights_from_hdf5_group(f, self.layers)

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in load_weights_from_hdf5_group_by_name(f, layers, skip_mismatch)
   3246                                             weight_values[i]))
   3247 
-> 3248     K.batch_set_value(weight_value_tuples)

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in batch_set_value(tuples)
   2363                 assign_placeholder = tf.placeholder(tf_dtype,
   2364                                                     shape=value.shape)
-> 2365                 assign_op = x.assign(assign_placeholder)
   2366                 x._assign_placeholder = assign_placeholder
   2367                 x._assign_op = assign_op

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.pyc in assign(self, value, use_locking)
    571       the assignment has completed.
    572     """
--> 573     return state_ops.assign(self._variable, value, use_locking=use_locking)
    574 
    575   def assign_add(self, delta, use_locking=False):

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.pyc in assign(ref, value, validate_shape, use_locking, name)
    274     return gen_state_ops.assign(
    275         ref, value, use_locking=use_locking, name=name,
--> 276         validate_shape=validate_shape)
    277   return ref.assign(value)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.pyc in assign(ref, value, validate_shape, use_locking, name)
     55     _, _, _op = _op_def_lib._apply_op_helper(
     56         "Assign", ref=ref, value=value, validate_shape=validate_shape,
---> 57         use_locking=use_locking, name=name)
     58     _result = _op.outputs[:]
     59     _inputs_flat = _op.inputs

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.pyc in _apply_op_helper(self, op_type_name, name, **keywords)
    785         op = g.create_op(op_type_name, inputs, output_types, name=scope,
    786                          input_types=input_types, attrs=attr_protos,
--> 787                          op_def=op_def)
    788       return output_structure, op_def.is_stateful, op
    789 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in create_op(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_shapes, compute_device)
   2956         op_def=op_def)
   2957     if compute_shapes:
-> 2958       set_shapes_for_outputs(ret)
   2959     self._add_op(ret)
   2960     self._record_op_seen_by_control_dependencies(ret)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in set_shapes_for_outputs(op)
   2207       shape_func = _call_cpp_shape_fn_and_require_op
   2208 
-> 2209   shapes = shape_func(op)
   2210   if shapes is None:
   2211     raise RuntimeError(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in call_with_requiring(op)
   2157 
   2158   def call_with_requiring(op):
-> 2159     return call_cpp_shape_fn(op, require_shape_fn=True)
   2160 
   2161   _call_cpp_shape_fn_and_require_op = call_with_requiring

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.pyc in call_cpp_shape_fn(op, require_shape_fn)
    625     res = _call_cpp_shape_fn_impl(op, input_tensors_needed,
    626                                   input_tensors_as_shapes_needed,
--> 627                                   require_shape_fn)
    628     if not isinstance(res, dict):
    629       # Handles the case where _call_cpp_shape_fn_impl calls unknown_shape(op).

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.pyc in _call_cpp_shape_fn_impl(op, input_tensors_needed, input_tensors_as_shapes_needed, require_shape_fn)
    689       missing_shape_fn = True
    690     else:
--> 691       raise ValueError(err.message)
    692 
    693   if missing_shape_fn:

ValueError: Dimension 0 in both shapes must be equal, but are 3 and 258 for 'Assign_49' (op: 'Assign') with input shapes: [3,3,512,344], [258,512,3,3].``

> --------I

 **tried to change keras.jason to "channels_first" but it gave me Negative dimension size caused by subtracting 3 from 1 error as below:**

ValueErrorTraceback (most recent call last)
<ipython-input-12-2f7a46d4adea> in <module>()
     22                 top_k=200,
     23                 nms_max_output_size=400,
---> 24                 return_predictor_sizes=False)
     25 
     26 print("Model built.")

/home/saif/Documents/ssd_keras/models/keras_ssd300.pyc in ssd_300(image_size, n_classes, mode, l2_regularization, min_scale, max_scale, scales, aspect_ratios_global, aspect_ratios_per_layer, two_boxes_for_ar1, steps, offsets, clip_boxes, variances, coords, normalize_coords, subtract_mean, divide_by_stddev, swap_channels, confidence_thresh, iou_threshold, top_k, nms_max_output_size, return_predictor_sizes)
    311     #conv10_1_2
    312     conv8_1 = Conv2D(128, (1, 1), activation='relu', padding='same', kernel_initializer='he_normal', kernel_regularizer=l2(l2_reg), name='conv8_1')(conv7_2)
--> 313     conv8_2 = Conv2D(256, (3, 3), strides=(1, 1), activation='relu', padding='valid', kernel_initializer='he_normal', kernel_regularizer=l2(l2_reg), name='conv8_2')(conv8_1)
    314 
    315     #conv11_1_2

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in __call__(self, inputs, **kwargs)
    615 
    616             # Actually call the layer, collecting output(s), mask(s), and shape(s).
--> 617             output = self.call(inputs, **kwargs)
    618             output_mask = self.compute_mask(inputs, previous_mask)
    619 

/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.pyc in call(self, inputs)
    166                 padding=self.padding,
    167                 data_format=self.data_format,
--> 168                 dilation_rate=self.dilation_rate)
    169         if self.rank == 3:
    170             outputs = K.conv3d(

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in conv2d(x, kernel, strides, padding, data_format, dilation_rate)
   3330         strides=strides,
   3331         padding=padding,
-> 3332         data_format=tf_data_format)
   3333 
   3334     if data_format == 'channels_first' and tf_data_format == 'NHWC':

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.pyc in convolution(input, filter, padding, strides, dilation_rate, name, data_format)
    749                      dilation_rate=dilation_rate,
    750                      name=name, data_format=data_format)
--> 751     return op(input, filter)
    752 
    753 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.pyc in __call__(self, inp, filter)
    833 
    834   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
--> 835     return self.conv_op(inp, filter)
    836 
    837 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.pyc in __call__(self, inp, filter)
    497 
    498   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
--> 499     return self.call(inp, filter)
    500 
    501 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.pyc in __call__(self, inp, filter)
    185         padding=self.padding,
    186         data_format=self.data_format,
--> 187         name=self.name)
    188 
    189 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.pyc in conv2d(input, filter, strides, padding, use_cudnn_on_gpu, data_format, name)
    629         "Conv2D", input=input, filter=filter, strides=strides,
    630         padding=padding, use_cudnn_on_gpu=use_cudnn_on_gpu,
--> 631         data_format=data_format, name=name)
    632     _result = _op.outputs[:]
    633     _inputs_flat = _op.inputs

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.pyc in _apply_op_helper(self, op_type_name, name, **keywords)
    785         op = g.create_op(op_type_name, inputs, output_types, name=scope,
    786                          input_types=input_types, attrs=attr_protos,
--> 787                          op_def=op_def)
    788       return output_structure, op_def.is_stateful, op
    789 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in create_op(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_shapes, compute_device)
   2956         op_def=op_def)
   2957     if compute_shapes:
-> 2958       set_shapes_for_outputs(ret)
   2959     self._add_op(ret)
   2960     self._record_op_seen_by_control_dependencies(ret)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in set_shapes_for_outputs(op)
   2207       shape_func = _call_cpp_shape_fn_and_require_op
   2208 
-> 2209   shapes = shape_func(op)
   2210   if shapes is None:
   2211     raise RuntimeError(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in call_with_requiring(op)
   2157 
   2158   def call_with_requiring(op):
-> 2159     return call_cpp_shape_fn(op, require_shape_fn=True)
   2160 
   2161   _call_cpp_shape_fn_and_require_op = call_with_requiring

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.pyc in call_cpp_shape_fn(op, require_shape_fn)
    625     res = _call_cpp_shape_fn_impl(op, input_tensors_needed,
    626                                   input_tensors_as_shapes_needed,
--> 627                                   require_shape_fn)
    628     if not isinstance(res, dict):
    629       # Handles the case where _call_cpp_shape_fn_impl calls unknown_shape(op).

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.pyc in _call_cpp_shape_fn_impl(op, input_tensors_needed, input_tensors_as_shapes_needed, require_shape_fn)
    689       missing_shape_fn = True
    690     else:
--> 691       raise ValueError(err.message)
    692 
    693   if missing_shape_fn:

ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv8_2/convolution' (op: 'Conv2D') with input shapes: [?,5,1,128], [3,3,128,256].

Any resolve please?

**Comment by cyberphantom** [comment]
@pierluigiferrari Please help ^_^

**Comment by cyberphantom** [comment]
Solved by adding skip_mistmach = True

**Comment by melih-unsal** [comment]
@cyberphantom  Where did you put skip_mistmach = True?
