### ISSUE TITLE
How to compute the prediction speed of SSD

### ISSUE THREAD

**Issue by TrungHieu-Le** [pierluigiferrari/ssd_keras#149]
Hello Pierluigiferrari
Thank for your sharing,
In your notebook, you mentioned the prediction speed of SSD, and show the results. 
Could you please share the source code or let me know how to compute it? 
Thank you very much.

**Comment by pierluigiferrari** [comment]
The same way you compute the run time of any program. You use some Python module like `time` or `timeit`, run a bunch of predictions and record the time for each, and take the average.

**Comment by TrungHieu-Le** [comment]
Hello Pierluigiferrari,
Thank for your answer,
Could you please let me know more?
When computing the prediction speed, we also compute the run time of drawing the predicted bounding boxes or not 
Thank you!
