### ISSUE TITLE
Issue when training.

### ISSUE THREAD

**Issue by jetjodh** [pierluigiferrari/ssd_keras#151]
I was using this [file](https://colab.research.google.com/drive/1rLSJKNe5KtaKfMVnwgELwwrQGqG-oaIJ#scrollTo=L25gbVj_HFq-)  which you prepared when resolving this [issue](https://github.com/pierluigiferrari/ssd_keras/issues/77). I am trying to detect tect on my own custom dataset and having following problem. How do I resolve?

Stack Trace:
Epoch 1/5

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-75ab933fd3d2> in <module>()
     11                               callbacks=callbacks,
     12                               validation_data=val_generator,
---> 13                               validation_steps=ceil(val_dataset_size/batch_size))

~\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2210                 batch_index = 0
   2211                 while steps_done < steps_per_epoch:
-> 2212                     generator_output = next(output_generator)
   2213 
   2214                     if not hasattr(generator_output, '__len__'):

~\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\keras\utils\data_utils.py in get(self)
    777             success, value = self.queue.get()
    778             if not success:
--> 779                 six.reraise(value.__class__, value, value.__traceback__)

~\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\keras\utils\data_utils.py in _data_generator_task(self)
    642                             # => Serialize calls to
    643                             # infinite iterator/generator's next() function
--> 644                             generator_output = next(self._generator)
    645                             self.queue.put((True, generator_output))
    646                         else:

~\Documents\GitHub\ssd_keras\data_generator\object_detection_2d_data_generator.py in generate(self, batch_size, shuffle, transformations, label_encoder, returns, keep_images_without_gt, degenerate_box_handling)
   1149                     batch_y_encoded, batch_matched_anchors = label_encoder(batch_y, diagnostics=True)
   1150                 else:
-> 1151                     batch_y_encoded = label_encoder(batch_y, diagnostics=False)
   1152                     batch_matched_anchors = None
   1153 

~\Documents\GitHub\ssd_keras\ssd_encoder_decoder\ssd_input_encoder.py in __call__(self, ground_truth_labels, diagnostics)
    347                 labels = convert_coordinates(labels, start_index=xmin, conversion='corners2minmax')
    348 
--> 349             classes_one_hot = class_vectors[labels[:, class_id].astype(np.int)] # The one-hot class IDs for the ground truth boxes of this batch item
    350             labels_one_hot = np.concatenate([classes_one_hot, labels[:, [xmin,ymin,xmax,ymax]]], axis=-1) # The one-hot version of the labels for this batch item
    351 

IndexError: index 592 is out of bounds for axis 0 with size 2

**Comment by pierluigiferrari** [comment]
The stack trace pretty much provides the answer to the problem: The error is raised by line 349, which contains an inline comment telling you that what this line does is turning the class IDs of the given batch item into a one-hot vector. The error says that the `class_vectors` array has size 2, but you're trying to index it with class ID 592. That is, your `SSDInputEncoder` thinks your model has only 2 classes in total (i.e. one positive class and the background class), while the labels in your ground truth data seem to represent at least 592 different classes. Hence, I'd assume that you're building the model (or at least the `SSDInputEncoder` instance) with the wrong number of classes.

**Comment by jetjodh** [comment]
Cool, I have gone with another methodology.
