### ISSUE TITLE
Question about input image size

### ISSUE THREAD

**Issue by sachinsdate** [pierluigiferrari/ssd_keras#152]
Hi Pierluigi,
I am running a transfer learning session on COCO stuff 2017 categories using the code from ssd300_training.ipynb

So far it's going beautifully!

A quick question:
Where is it, in your code that you resize the training images to 300x300? I looked and looked, but the line of code is eluding me. 

My DataGenerator flags are as follows:
load_images_into_memory=False, hdf5_dataset_path=None

Thanks
 Sachin

**Comment by pierluigiferrari** [comment]
The data generator is being given an [`SSDDataAugmentation`](https://github.com/pierluigiferrari/ssd_keras/blob/master/data_generator/data_augmentation_chain_original_ssd.py) object, which is an image transformation object that consists of a sequence of other image transformation objects. One of those image transformations is a `Resize` object from [this](https://github.com/pierluigiferrari/ssd_keras/blob/master/data_generator/object_detection_2d_geometric_ops.py) module.

In case this seems confusing to you, [this](https://github.com/pierluigiferrari/data_generator_object_detection_2d/blob/master/data_generator_tutorial.ipynb) tutorial explains the design of the data generator.

**Comment by sachinsdate** [comment]
Okay I see it now. I don't how I missed that. Thanks! Closing this query.
