### ISSUE TITLE
Adding more object categories dynamically

### ISSUE THREAD

**Issue by ramnithin** [pierluigiferrari/ssd_keras#153]
I tried to add more number of classes to the existing trained model. I was able to create the weights file which contained the previously trained weights as well. But When I train the model with new data of the new classes, the previously trained weights breaks and there is no detection of old classes.

I tried to freeze the pre-trained weights and only train on the weights of the new classes. I am able to identify the filters of the confidence score to be frozen, but it is not possible to identify separate localisation  filters( filters for finding the co-ordinates of offsets to anchor boxes)  with respect to each class. Because each anchor box has confidence score for all the classes, but has only one set of coordinates for the offsets. So before having the confidence score, we will not know to which class the anchor box belongs to so that we can freeze the weights.

So is it not possible to upsample the number of classes ?  Is retraining the whole network  with new classes the only way around? Is SSD built in such a way that upsampling is not possible at all? Any help would be useful. Thanks in advance!!!

**Comment by pierluigiferrari** [comment]
This has nothing to do with SSD in particular. If you train only certain classes of a pre-trained neural network, the network will naturally gradually become worse at the classes on which you don't train it.

**Comment by ramnithin** [comment]
I am referring to the training of new classes along with the existing ones. My question is how will you add more classes to the model, I should be able to detect old classes as well along with the new ones. How do you train the new classes without breaking the old weights? I do not prefer training the model from scratch with old and new classes combined.

**Comment by pierluigiferrari** [comment]
The answers to these questions are already given in my previous post above, but I'll take another stab at this one:

> How do you train the new classes without breaking the old weights?

You train on the combined old dataset (containing the old classes) and new dataset (containing the new classes) simultaneously.

More generally, as I wrote in my previous post above: If your model is built to classify `K` different classes, you must train it on all `K` classes. The answers to your questions above all follow directly from the previous sentence. You must always train the model on all classes that it is supposed to distinguish (unless you use so-called continuous learning techniques such as [elastic weight consolidation](https://arxiv.org/pdf/1612.00796.pdf)). In particular, if you have a model that is trained on `N` classes and you expand it (i.e. upsample the classifier layers) to learn another `M` additional classes, you must train the model on all `M + N` classes. If you don't, it will gradually "unlearn" the classes on which you don't train.
