### ISSUE TITLE
How do I create the Y values for a custom X image ?

### ISSUE THREAD

**Issue by jmaister** [pierluigiferrari/ssd_keras#156]
I am trying to train SSD7 with custom classes. I already have some images (X) and its boxes (Y = (class, x1, y1, x2, y2)).

The Y that I start with has shape (1, 5, 1) and the network has (1, 66640, 4).

How do I convert my Y to the Y that the network "understands" with all the box "metadata" ?

**Comment by pierluigiferrari** [comment]
That's what the [`SSDInputEncoder`](https://github.com/pierluigiferrari/ssd_keras/blob/master/ssd_encoder_decoder/ssd_input_encoder.py) is for, which is also explained in the README and in the training tutorials.

**Comment by jmaister** [comment]
Thanks, I made it work with the SSDInputEncoder.
After training, the decoder returns back weird data. I'll continue investigating.

**Comment by pierluigiferrari** [comment]
In case you have images of variable size, try to follow the setup in the SSD300 training notebook (instead of that in the SS7 training notebook).

**Comment by jmaister** [comment]
I combined VGG16 (from keras.applications.vgg16.VGG16) + the end of SSD7.

Cool, I'll try with VGG16 (keras) + SSD300.

**Comment by pierluigiferrari** [comment]
What's the point of doing that? SSD300 and SSD512 are based on VGG-16 anyway, so why go through the trouble of patching together the architecture manually when it's already there in the repo?

**Comment by jmaister** [comment]
So I can use the pretrained weights of VGG-16.

**Comment by pierluigiferrari** [comment]
There are trained VGG-16 weights provided in this repository and both the SSD300 and SSD512 models use them.

Did you not read the SSD 300 training tutorial at all? Section 2.
