### ISSUE TITLE
There are many errors when i run it on win10.Can this model work well on windows?

### ISSUE THREAD

**Issue by AllanZuo** [pierluigiferrari/ssd_keras#158]
Can this model work well on windows?

**Comment by pierluigiferrari** [comment]
I don't run Windows and have no experience with it, so I don't know. I test this implementation on Ubuntu and Mac OS only. As long as you have Python, TensorFlow and Keras installed on your system, I don't see why this would be operating system-dependent, but again, I know next to nothing about Windows.

If this implementation didn't work on Windows though, I would assume that you would probably not be the first to open an issue about it, so I guess it's more likely that whatever errors you're getting are specific to your setup.

**Comment by AllanZuo** [comment]
Thanks for your reply. You are right.It lacks some required library in my environment.I have fixed many problems in my environment. But there is one problem still left.

Traceback (most recent call last):
  File "D:/Program/SSD_keras-master/ssd_300test.py", line 86, in <module>
    'compute_loss': ssd_loss.compute_loss})
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\keras\engine\saving.py", line 259, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.


I don‘t know how to fix it.I download the weight as provied.Below is the soure code.

weights_path = 'D:\\Program\\SSD_keras-master\\VGG_VOC0712_SSD_300x300_ft_iter_120000.h5'
model.load_weights(weights_path, by_name=True)

adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
ssd_loss = SSDLoss(neg_pos_ratio=3, alpha=1.0)

model.compile(optimizer=adam, loss=ssd_loss.compute_loss)
model_path = 'D:\\Program\\SSD_keras-master\\VGG_ILSVRC_16_layers_fc_reduced.h5'

ssd_loss = SSDLoss(neg_pos_ratio=3, n_neg_min=0, alpha=1.0)

K.clear_session() # Clear previous models from memory.

model = load_model(model_path, custom_objects={'AnchorBoxes': AnchorBoxes,
                                               'L2Normalization': L2Normalization,
                                               'DecodeDetections': DecodeDetections,
                                               'compute_loss': ssd_loss.compute_loss})
.
`
Could you help me to annalysis it?

**Comment by pierluigiferrari** [comment]
> model_path = 'D:\Program\SSD_keras-master\VGG_ILSVRC_16_layers_fc_reduced.h5'

`VGG_ILSVRC_16_layers_fc_reduced.h5` is a weights file, not a model file. You're trying to call the `load_model()` function on a weights file. The Keras documentation and Google are your friends 🙂

**Comment by AllanZuo** [comment]
Thanks a lot! I see it now. Each of them(refering to 'load weight') will be ok. That is to say one can use a pre-trained weight by others or their own model trained by themself. And it can run in win10 system too.
