### ISSUE TITLE
the usage of trainval.txt in ssd300_training.ipynb

### ISSUE THREAD

**Issue by Garamda** [pierluigiferrari/ssd_keras#161]
First of all, I appreciate your work which makes using ssd more easier.

I want to use ssd_keras for crack detection. That means I want to train my crack image dateset, not VOC2007 or VOC2012. So my idea is first, using the pre-trained weight of randomly sampled number of classes, because I expect that randomly sampled pre-trained weight will generate better result than base weight. And just change the dataset from VOC2007/2012 to my crack image dateset which is to be trained.

That's why I create my own trainval.txt and test.val files to train my crack image dateset. I made it by copying the format of original trainval.txt file from VOC2007 and VOC2012. But I encountered the error below.

```
Processing image set 'trainval.txt':   0%|                                                       | 0/1 [00:00<?, ?it/s]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-33-f78c82f9a373> in <module>()
     37                         exclude_truncated=False,
     38                         exclude_difficult=False,
---> 39                         ret=False)
     40 
     41 val_dataset.parse_xml(images_dirs=[Crack_images_dir],

~\keras\ssd_keras\data_generator\object_detection_2d_data_generator.py in parse_xml(self, images_dirs, image_set_filenames, annotations_dirs, classes, include_classes, exclude_truncated, exclude_difficult, ret, verbose)
    478                 if not annotations_dir is None:
    479                     # Parse the XML file for this image.
--> 480                     with open(os.path.join(annotations_dir, image_id + '.xml')) as f:
    481                         soup = BeautifulSoup(f, 'xml')
    482 

FileNotFoundError: [Errno 2] No such file or directory: '../../Desktop/SPARK/Concrete Crack Images for Classification/Positive 300 X 300/annotation/000001000002000003000004000005000006000007...(*I just skipped it*)...019995019996019997019998019999020000.xml'
```

When I put single file name in trainval.txt, just like "005001", it was processed through well(005001.xml) so it is not about the lxml issue. The problem is this code can not process 2 files or more, like "005001005002". The entire string in trainval.txt is identified as one file name. So I tried almost everything about changing the format of trainval.txt, but it never worked.

So What I wanted to ask specifically is,
: If my trainval.txt file is wrong, how can I change it following the right format?
Those questions are maybe not supposed to be posted here because it can be asked to PASCAL VOC. However I coulnd't find "how to create my own trainval.txt following the right format" neither in PASCAL VOC nor ssd_keras so I'm asking here. Then, how can I create the right trainval.txt for my own dataset?
 

Below is the full code for data generation

```
train_dataset = DataGenerator(load_images_into_memory=True, hdf5_dataset_path=None)
val_dataset = DataGenerator(load_images_into_memory=True, hdf5_dataset_path=None)

Crack_images_dir      = '../../Desktop/SPARK/Concrete Crack Images for Classification/Positive 300 X 300/Positive/'

Crack_images_dir_annotations      = '../../Desktop/SPARK/Concrete Crack Images for Classification/Positive 300 X 300/annotation/'

trainval_image_set_filename = '../../Desktop/SPARK/Concrete Crack Images for Classification/Positive 300 X 300/trainval.txt'
test_image_set_filename     = '../../Desktop/SPARK/Concrete Crack Images for Classification/Positive 300 X 300/test.txt'

classes = ['crack']

train_dataset.parse_xml(images_dirs=[Crack_images_dir],
                        image_set_filenames=[trainval_image_set_filename],
                        annotations_dirs=[Crack_images_dir_annotations],
                        classes=classes,
                        include_classes='all',
                        exclude_truncated=False,
                        exclude_difficult=False,
                        ret=False)

val_dataset.parse_xml(images_dirs=[Crack_images_dir],
                      image_set_filenames=[test_image_set_filename],
                      annotations_dirs=[Crack_images_dir_annotations],
                      classes=classes,
                      include_classes='all',
                      exclude_truncated=False,
                      exclude_difficult=True,
                      ret=False)
```
        * Windows 10
        * about implementing ssd300_training.ipynb
        * Keras 2.2
        * TensorFlow version 1.9.0

Thank you for your help.
And If my questions are not proper, I should apologize for that.

**Comment by pierluigiferrari** [comment]
When you create your `trainval.txt`, you must put a newline character after each image ID, not put all image IDs in a single line.

If you just look at the Pascal VOC `trainval.txt` in a text editor and compare it to yours, you should see the difference.

**Comment by Garamda** [comment]
@pierluigiferrari I really appreciate it. It worked!
I have never tried to change each lines. Thank you very much.

I opened 'trainval.txt' in PASCAL VOC only with notepad, which doesn't show newline characters.
As you said "a text editor", I tried wordpad and it finally shows newline characters.
I learned today that even using proper text editor is important.

Again, Thank you very much!

**Comment by pierluigiferrari** [comment]
You're welcome!

**Comment by Leon924** [comment]
@ First of all, Thank you for your great work ! 
when I am using pascalvoc2007trainval  to run ssd300training.ipynb, I came across this bug, how can I solve this？ @Garamda @pierluigiferrari 


Processing image set 'trainval.txt':   0%|          | 0/5011 [00:00<?, ?it/s]

Processing image set 'trainval.txt':   0%|          | 6/5011 [00:00<01:24, 59.43it/s]

Processing image set 'trainval.txt':   1%|          | 36/5011 [00:00<01:03, 78.11it/s]

Processing image set 'trainval.txt':   1%|          | 57/5011 [00:00<00:51, 96.10it/s]

Processing image set 'trainval.txt':   2%|鈻?        | 91/5011 [00:00<00:40, 122.45it/s]

Processing image set 'trainval.txt':   2%|鈻?     

Processing image set 'trainval.txt': 100%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 5011/5011 [00:19<00:00, 252.88it/s]

Processing image set 'trainval.txt':   0%|          | 0/11540 [00:00<?, ?it/s]

Processing image set 'trainval.txt':   0%|          | 34/11540 [00:00<00:34, 337.01it/s]

Processing image set 'trainval.txt':   1%|          | 68/11540 [00:00<00:34, 336.60it/s]

Processing image set 'trainval.txt':  99%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枆| 11437/11540 [00:38<00:00, 253.74it/s]

Processing image set 'trainval.txt':  99%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枆| 11463/11540 [00:38<00:00, 248.34it/s]

Processing image set 'trainval.txt': 100%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枆| 11495/11540 [00:38<00:00, 264.00it/s]

Processing image set 'trainval.txt': 100%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枆| 11522/11540 [00:38<00:00, 259.96it/s]

Processing image set 'trainval.txt': 100%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 11540/11540 [00:38<00:00, 299.57it/s]

Processing image set 'test.txt':   0%|          | 0/4952 [00:00<?, ?it/s]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-16-ba6ac43939b3> in <module>
     54                       exclude_truncated=False,
     55                       exclude_difficult=True,
---> 56                       ret=False)
     57 
     58 # Optional: Convert the dataset into an HDF5 dataset. This will require more disk space, but will

~/liqiang/Deeplearning/SSD_keras/ssd_keras/data_generator/object_detection_2d_data_generator.py in parse_xml(self, images_dirs, image_set_filenames, annotations_dirs, classes, include_classes, exclude_truncated, exclude_difficult, ret, verbose)
    478                 if not annotations_dir is None:
    479                     # Parse the XML file for this image.
--> 480                     with open(os.path.join(annotations_dir, image_id + '.xml')) as f:
    481                         soup = BeautifulSoup(f, 'xml')
    482 

FileNotFoundError: [Errno 2] No such file or directory: '/export/userhome/liqiang/liqiang/Deeplearning/SSD/SSD-datasets/VOC2007/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/Annotations/000001.xml'
 
envs:
voc2007trainval
python3.6
keras2.2
tf-gpu 1.10
