### ISSUE TITLE
Single Picture Data Augmentation

### ISSUE THREAD

**Issue by lukerschwan** [pierluigiferrari/ssd_keras#168]
Hello, I have been loving working with your model. I have an implementation that requires detection given only one picture with a bounding box. Is there any way to automatically generate enough data and XML files using your data augmentation library for detection? 
Thank You.

**Comment by pierluigiferrari** [comment]
You need to be more precise: You mean you have only one training image?

**Comment by lukerschwan** [comment]
Yes, I only will have one training image.

**Comment by pierluigiferrari** [comment]
I mean, that should be obvious then: You almost certainly won't get a model that generalizes, regardless of how much data augmentation you perform.

If you're already working with the model anyway though, you could just try and see what happens.
