### ISSUE TITLE
Understanding converting gt absolute coordinates to offsets

### ISSUE THREAD

**Issue by Xiaohong-Deng** [pierluigiferrari/ssd_keras#169]
In `SSDInputEncoder#__call__`, the following code is used to convert absolute ground truth bounding box coordinates to offsets relative to anchor boxes.

I don't understand why it is done this way. In 'centroids' mode, the offsets for coordinates are not the difference but the difference divided by width and height. The offsets for width and height are the natural log to the ratio of ground truth and anchor box.

Any literature suggested?

Thanks in advance.

```python
        if self.coords == 'centroids':
            y_encoded[:,:,[-12,-11]] -= y_encoded[:,:,[-8,-7]] # cx(gt) - cx(anchor), cy(gt) - cy(anchor)
            y_encoded[:,:,[-12,-11]] /= y_encoded[:,:,[-6,-5]] * y_encoded[:,:,[-4,-3]] # (cx(gt) - cx(anchor)) / w(anchor) / cx_variance, (cy(gt) - cy(anchor)) / h(anchor) / cy_variance
            y_encoded[:,:,[-10,-9]] /= y_encoded[:,:,[-6,-5]] # w(gt) / w(anchor), h(gt) / h(anchor)
            y_encoded[:,:,[-10,-9]] = np.log(y_encoded[:,:,[-10,-9]]) / y_encoded[:,:,[-2,-1]] # ln(w(gt) / w(anchor)) / w_variance, ln(h(gt) / h(anchor)) / h_variance (ln == natural logarithm)
        elif self.coords == 'corners':
            y_encoded[:,:,-12:-8] -= y_encoded[:,:,-8:-4] # (gt - anchor) for all four coordinates
            y_encoded[:,:,[-12,-10]] /= np.expand_dims(y_encoded[:,:,-6] - y_encoded[:,:,-8], axis=-1) # (xmin(gt) - xmin(anchor)) / w(anchor), (xmax(gt) - xmax(anchor)) / w(anchor)
            y_encoded[:,:,[-11,-9]] /= np.expand_dims(y_encoded[:,:,-5] - y_encoded[:,:,-7], axis=-1) # (ymin(gt) - ymin(anchor)) / h(anchor), (ymax(gt) - ymax(anchor)) / h(anchor)
            y_encoded[:,:,-12:-8] /= y_encoded[:,:,-4:] # (gt - anchor) / size(anchor) / variance for all four coordinates, where 'size' refers to w and h respectively
        elif self.coords == 'minmax':
            y_encoded[:,:,-12:-8] -= y_encoded[:,:,-8:-4] # (gt - anchor) for all four coordinates
            y_encoded[:,:,[-12,-11]] /= np.expand_dims(y_encoded[:,:,-7] - y_encoded[:,:,-8], axis=-1) # (xmin(gt) - xmin(anchor)) / w(anchor), (xmax(gt) - xmax(anchor)) / w(anchor)
            y_encoded[:,:,[-10,-9]] /= np.expand_dims(y_encoded[:,:,-5] - y_encoded[:,:,-6], axis=-1) # (ymin(gt) - ymin(anchor)) / h(anchor), (ymax(gt) - ymax(anchor)) / h(anchor)
            y_encoded[:,:,-12:-8] /= y_encoded[:,:,-4:] # (gt - anchor) / size(anchor) / variance for all four coordinates, where 'size' refers to w and h respectively
```

**Comment by Xiaohong-Deng** [comment]
Question remains unsolved

**Comment by pierluigiferrari** [comment]
> the offsets for coordinates are not the difference but the difference divided by width and height.

The division by width/height is to have relative offsets instead of absolute offsets (i.e. relative to the anchor box widths/heights).

> The offsets for width and height are the natural log to the ratio of ground truth and anchor box.

In contrast to the center point offsets, the offsets for the box width and height are not symmetrical. A given ground truth box can be arbitrarily wider than a given anchor box, but it cannot have a width of less than zero. You want to treat relative deviations from the anchor box width/height equally in both directions. Converting the height and width offsets to the logarithmic scale does just that. Note that `ln(a) = -ln(1/a)` for any positive real number `a`, e.g. `ln(0.5) = -ln(2)`, which fulfills the purpose of treating relative width/height deviations equally in both directions.

**Comment by Xiaohong-Deng** [comment]
So all these are for normalization, right? For faster convergence and other reasons we do normalization in general cases.

**Comment by pierluigiferrari** [comment]
> So all these are for normalization, right?

No, taking the natural logarithm doesn't normalize anything, it's a nonlinear coordinate transformation to ensure effective learning for the reasons explained above. It's not done for faster convergence, but to achieve better results (i.e. convergence against a lower limit).

**Comment by Xiaohong-Deng** [comment]
Seems I wasn't in the right direction. I thought natural log brings two values of different magnitudes closer to each other, e.g., log(0.001) = -6.9, log(0.00001)=-11.51. I thought this was meant to avoid an error term overwhelming other error terms in loss function. That's normalization as I understand it. But you are right about the nonlinear part. Normalization usually involves only linear operations.

So I have to ask questions that may sound dumb.

>  You want to treat relative deviations from the anchor box width/height equally in both directions.

What does "treat deviation equally" mean? What benefit we get from that?

> i.e. convergence against a lower limit

What is a lower limit? Why it brings better results?
