### ISSUE TITLE
Data aumentation is quite different from original SSD

### ISSUE THREAD

**Issue by liuwei16** [pierluigiferrari/ssd_keras#17]
For example, in this repo, image translation is adopted, which is common in image classification, but is it necessary for object detection?
Why not realize the original Data aumentation in SSD?

**Comment by pierluigiferrari** [comment]
Check the latest commit, I've updated the data augmentation ops. The generator now provides new operations that are more useful. The data augmentation is still different from the original implementation, but a lot closer now than before. It works quite well.
