### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'append'

### ISSUE THREAD

**Issue by Garamda** [pierluigiferrari/ssd_keras#171]
Hi! I'm working on implementing your code to my own project.
First of all, great thanks to you. Your work helped me a lot.

What I wanted to do is to apply this detection code to videos.
So I followed #35, and saved each frames first.
Next, I used iteration loop to append the images of each frame into 'orig_images = []' and 'input_images = []'.
However, it doesn't work, while a single image was successfully went through this process.
The code is below.

```
orig_images = [] # Store the images here.
input_images = [] # Store resized versions of the images here.

for i in range(0,320):
    if(i%5==0):
        img_path = 'C:\\Users\\user\Desktop\\frames\\frame%d.jpg'%i
        print(img_path)
        orig_images.append(imread(img_path))
        img = image.load_img(img_path, target_size=(img_height, img_width))
        img = image.img_to_array(img) 
        input_images.append(img)
        input_images = np.array(input_images)


C:\Users\user\Desktop\frames\frame0.jpg
C:\Users\user\Desktop\frames\frame5.jpg
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-77-c59779a88106> in <module>()
     13         img = image.load_img(img_path, target_size=(img_height, img_width))
     14         img = image.img_to_array(img)
---> 15         input_images.append(img)
     16         input_images = np.array(input_images)

AttributeError: 'numpy.ndarray' object has no attribute 'append'
```

Does this mean that I can't append multiple slides of images into 'input_images' so I have to change the format of 'input_images'? 
Or, is there better way for me to pass each frames to the code?

I really appreciate your help.

**Comment by pierluigiferrari** [comment]
Not to be a dick, but your problem has obviously nothing to do with this SSD implementation. This is simply an issue of you using a NumPy function incorrectly. It's telling you right there in the error message that you are using the wrong syntax for NumPy's `append()` method, so the sensible thing to do would be to take a look at the NumPy documentation for this method.
