### ISSUE TITLE
how to run on videos

### ISSUE THREAD

**Issue by SahadevPoudel** [pierluigiferrari/ssd_keras#174]

**Comment by SahadevPoudel** [comment]
if somebody have done it, please help me

**Comment by maksatkanat** [comment]
> if somebody have done it, please help me

Hello! just use for loop and opencv to read video and recognize frame. For example:
`import cv2`
`#import other libraries , you can use ssd300_inference.ipynb`
`cap = cv2.VideoCapture('pathToFile/1.mp4') `
`while(True):`
`    ret, img = cap.read()`
`    input_images = [img]`
`    # here you can use the code starting from "ssd300_inference.ipynb" file, Chapter 3: Make predictions`
`    # cycle will give you all frames from video file one by one, as rgb image.`

**Comment by SahadevPoudel** [comment]
thank you , i successfully did it.
