### ISSUE TITLE
Anchor boxes generate

### ISSUE THREAD

**Issue by omrylcn** [pierluigiferrari/ssd_keras#178]
Hi, This great repo , thanks for sharing. When i look "keras_ssd7.py" script , i saw "Generate the anchor boxes" part . I cant understant  this part .  I did not see in  original paper of ssd , is it extra part   or am i wrong ?

**Comment by pierluigiferrari** [comment]
They are called "prior boxes" in the original Caffe implementation.

**Comment by omrylcn** [comment]
Hi, thanks for answer. But I still do not understand why we use anchor box generator . Are they same anchor boxes and default boxes ? Do we use default boxes (eg 4 ) for each features map cell

**Comment by pierluigiferrari** [comment]
Read the documentation. The README contains a "Terminology" section in which this is explained clearly.
