### ISSUE TITLE
 I used the function SSDDataAugmentation, but why did the data not increase?

### ISSUE THREAD

**Issue by Edward1900** [pierluigiferrari/ssd_keras#186]
I trained according to the document ssd300_training.ipynb, and the data was not augmented.
How to use data expansion? I used the function SSDDataAugmentation, but why did the data not increase?

**Comment by pierluigiferrari** [comment]
That is not how that works. The data augmentation is being performed ad-hoc. You're not going to see "more" data on your hard drive.

**Comment by Edward1900** [comment]
> That is not how that works. The data augmentation is being performed ad-hoc. You're not going to see "more" data on your hard drive.

Thank you for your answer, How do I know how many images it expands?

**Comment by pierluigiferrari** [comment]
Each of the `N` individual sequential transformations contained in `SSDDataAugmentation` is independently applied with a certain probability, usually 0.5. The percentage of images being transformed by at least one transformation is thus roughly `(1 - 0.5^N)` if I did the math right. In other words, almost all images that the model sees during the training are uniquely transformed in some way.

**Comment by Edward1900** [comment]
> Each of the `N` individual sequential transformations contained in `SSDDataAugmentation` is independently applied with a certain probability, usually 0.5. The percentage of images being transformed by at least one transformation is thus roughly `(1 - 0.5^N)` if I did the math right. In other words, almost all images that the model sees during the training are uniquely transformed in some way.

Ok, thank you very much.
