### ISSUE TITLE
Problem generator training ssd7

### ISSUE THREAD

**Issue by vmerc** [pierluigiferrari/ssd_keras#187]
Hello,

I'm trying to train ssd7 with the ipynb that you provided. I create  a batch generator following your instructions and i have an error using fit generator : ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (16, 1).
My batchsize is 16 so i supposed that i did produced empty batches but when i check my generator (with a next) i have a list of 16 images and 16 encoded labels as it should be.
The only difference is that my image's size augmented in the generator : (375, 1242, 3) instead of (370,1224,3) (kitti dataset). Could you help me to fix this problem ?

**Comment by mechealww2** [comment]
it maybe the problem about label mismatch.
