### ISSUE TITLE
How to evaluation ssd7 and csv data?

### ISSUE THREAD

**Issue by freekoy** [pierluigiferrari/ssd_keras#188]
How to evaluation ssd7 and csv data?

**Comment by GriffinAustin** [comment]
[Official Python Docs for csv](https://docs.python.org/3.4/library/csv.html)

**Comment by GriffinAustin** [comment]
Example `csv` module in use
```
import csv
with open('file.csv', 'rb') as f:
    reader = csv.reader(f)
    your_list = list(reader)
```

**Comment by freekoy** [comment]
Thanks, but I have a problem, why is training ssd7 not the same result as in your file?
Training from scratch, just modified the batch size to 4
Trained for 60 rounds with a loss of more than 2

**Comment by mechealww2** [comment]
> 
> 
> Thanks, but I have a problem, why is training ssd7 not the same result as in your file?
> Training from scratch, just modified the batch size to 4
> Trained for 60 rounds with a loss of more than 2



> 
> 
> How to evaluation ssd7 and csv data?

Hi, i have some problem on ssd7 evaluation. Can you share some code for me?Thks.   orz

**Comment by freekoy** [comment]
Comment out the code that builds the model, retain the code that loads the model directly
run

**Comment by mechealww2** [comment]
So

> 
> 
> Comment out the code that builds the model, retain the code that loads the model directly
> run
So you mean make adaption to the SSD300 evaluation code？
