### ISSUE TITLE
 OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

### ISSUE THREAD

**Issue by santhoshav15** [pierluigiferrari/ssd_keras#197]
I sub sampled the required weight samples from 
https://github.com/pierluigiferrari/ssd_keras/blob/master/weight_sampling_tutorial.ipynb

While trying to load these sub sampled weights for training using this 
https://github.com/pierluigiferrari/ssd_keras/blob/master/ssd300_training.ipynb

I am unable to get the model weights loaded here is the complete error

> 
> --------------------------------------------------------------------------
> OSError                                   Traceback (most recent call last)
> <ipython-input-3-1f4f5ccb4844> in <module>
>      23 weights_path = '/home/lenavo/Downloads/pretrained_subsample.h5'
>      24 
> ---> 25 model.load_weights(weights_path, by_name=True)
>      26 
>      27 # 3: Instantiate an optimizer and the SSD loss function and compile the model.
> 
> ~/.virtualenvs/playWithKeras/lib/python3.5/site-packages/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
>    1155         if h5py is None:
>    1156             raise ImportError('`load_weights` requires h5py.')
> -> 1157         with h5py.File(filepath, mode='r') as f:
>    1158             if 'layer_names' not in f.attrs and 'model_weights' in f:
>    1159                 f = f['model_weights']
> 
> ~/.virtualenvs/playWithKeras/lib/python3.5/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
>     310             with phil:
>     311                 fapl = make_fapl(driver, libver, **kwds)
> --> 312                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
>     313 
>     314                 if swmr_support:
> 
> ~/.virtualenvs/playWithKeras/lib/python3.5/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
>     140         if swmr and swmr_support:
>     141             flags |= h5f.ACC_SWMR_READ
> --> 142         fid = h5f.open(name, flags, fapl=fapl)
>     143     elif mode == 'r+':
>     144         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
> 
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py/h5f.pyx in h5py.h5f.open()
> 
> OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

How to i load the sampled weight for training?

OS: Ubuntu 16.04
Tensor Flow Version: 1.12.0
Keras Version: 2.2.4

**Comment by 999suhaib** [comment]
Same problem, kindly help!
