### ISSUE TITLE
how to get the pretrained ssd300 model (.hdf5)?

### ISSUE THREAD

**Issue by liuwei16** [pierluigiferrari/ssd_keras#2]
By the way, how to transfer the caffemodel to .hdf5 file?

**Comment by pierluigiferrari** [comment]
I know of some tools others have built, which you can find [here](https://github.com/ethereon/caffe-tensorflow), [here](https://github.com/duguyue100/transcaffe), and [here](https://github.com/MarcBS/keras/tree/master/keras/caffe), although I haven't tried those yet and cannot say how well they work. Most of them seem focussed on converting model (not only the weights), which could be problematic with the custom layers in SSD.

You could also install Caffe and convert the original weights to HDF5 from within Caffe, but of course that would require to get into Caffe to a certain level (which I haven't gotten around to doing yet).
