### ISSUE TITLE
extra layers in ssd300 net

### ISSUE THREAD

**Issue by alalbiol** [pierluigiferrari/ssd_keras#20]
Hi, 
I am trying to get better understanding of ssd object detection and your code is really helpful. Thanks

However, I found a difference between your ssd300 model and the paper in the model: 
In particular I think that layers: conv6_1, conv6_2, conv7_1, conv7_2 are not included in the original paper (fig 2)
In the paper fc7 is connected to conv8 layers
I also think that padding in pool3 should be changed to same, so that the ouput shape of conv4 is 19x19 as in the paper

Thanks

**Comment by pierluigiferrari** [comment]
Both the paper and the model evolved over time, both in terms of the layer names and the layer structure. The layer structure you see in the paper is the same you see in `ssd300.py`, they are just named differently than in the paper. Layers `conv8` - `conv11` in the diagram in the paper are the same as layers `conv6` - `conv9` in `ssd300.py`. The naming in the paper is not consistent with the naming in the actual `prototxt` that defines the model, and I followed the naming in the `prototxt` file, i.e. what you see in `ssd300.py` accurately reflects the original Caffe implementation. In other words, what matters is not the paper, but the Caffe model implementation file.

Regarding the `pool3` layer, it too is parameterized exactly according to the original Caffe implementation of SSD300. The padding of all pooling layers is `valid` except for `pool5`.

I recommend you download the original Caffe model and take a look at `deploy.prototxt` to convince yourself of the model definitions are the same.

**Comment by alalbiol** [comment]
Thanks! you are totally right

**Comment by pierluigiferrari** [comment]
Anytime!
