### ISSUE TITLE
Where can I find the dataset for ssd7_training?

### ISSUE THREAD

**Issue by BruceDai003** [pierluigiferrari/ssd_keras#201]
I'm quite new to the object detection datasets format, so I decide not to use customized dataset in the first place. I noticed that in the `ssd7_training.ipynb`,  you were using udacity_driving_datasets. Could you provide a link as to where I can download the data. So that I can successfully run this tutorial notebook on training a 7 layer SSD? 
I googled about this udacity driving dataset, but not sure about which is the right one. And I think I don't want to have a huge amount of dataset ( > 10GB) to download if not necessary. I just want to get the training process running with decent amount of training data. So could you provide a link to get the training data.
Thanks a lot for this great project.

**Comment by pierluigiferrari** [comment]
The links to both the original Udacity driving datasets and the resized version I use in the tutorial are provided in the Jupyter notebook.

**Comment by BruceDai003** [comment]
Thanks, apologize for didn't see that. Please close this issue.
