### ISSUE TITLE
KeyError: 'val_loss'

### ISSUE THREAD

**Issue by sigmoidx** [pierluigiferrari/ssd_keras#202]
Hi, I encountered an error saying 'KeyError: val_loss'

Epoch 1/120

Epoch 00001: LearningRateScheduler setting learning rate to 0.001.
 385/1000 [==========>...................] - ETA: 1:54 - loss: nan 

And it returns nan as well. 

Any solutions for this?
Thanks,

**Comment by Michelexie** [comment]
I encountered the same error. And I think it's because the learning rate is set to be too high for initial epoches in `ssd300_training.ipynb` 
As the code below:
`# Define a learning rate schedule.

def lr_schedule(epoch):
    if epoch < 80:
        return 0.001
    elif epoch < 100:
        return 0.0001
    else:
        return 0.00001` 

And I set it to be:
`# Define a learning rate schedule.

def lr_schedule(epoch):
    if epoch < 80:
        return 0.00001
    elif epoch < 100:
        return 0.0001
    else:
        return 0.001`

Then the training can move on.

**Comment by thaodod** [comment]
I also had the same problem. :( @sigmoidx  did you solve it ?

**Comment by buaa-luzhi** [comment]
@Michelexie @doduythao @sigmoidx @pierluigiferrari 

I also had the same problem.   Have you solved the problem?  Thank you !!!

**Comment by buaa-luzhi** [comment]
> I encountered the same error. And I think it's because the learning rate is set to be too high for initial epoches in `ssd300_training.ipynb`
> As the code below:
> `# Define a learning rate schedule.
> 
> def lr_schedule(epoch):
> if epoch < 80:
> return 0.001
> elif epoch < 100:
> return 0.0001
> else:
> return 0.00001`
> 
> And I set it to be:
> `# Define a learning rate schedule.
> 
> def lr_schedule(epoch):
> if epoch < 80:
> return 0.00001
> elif epoch < 100:
> return 0.0001
> else:
> return 0.001`
> 
> Then the training can move on.

I don't think that's a very logical way to set it up.
In general, the initial value is set to large and then gradually reduced.
Why do you set a small initial value and then gradually increase it.
Thank you!
