### ISSUE TITLE
ssd7 inference model

### ISSUE THREAD

**Issue by rohanbanerjee** [pierluigiferrari/ssd_keras#204]
When I am loading the weights for just testing the model on custom input, it is throwing an error

raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

Any help regarding this would be useful!

**Comment by ndor** [comment]
@rohanbanerjee (or anyone else), did u solve this issue? im having the same problem... :/

**Comment by Tortoise17** [comment]
I am facing the same problem. !

**Comment by llabs-ai** [comment]
Me too.
"Cannot create group in read only mode."
