### ISSUE TITLE
Error while training ssd7

### ISSUE THREAD

**Issue by SaddamRaut** [pierluigiferrari/ssd_keras#207]
Epoch 1/20

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-c43c96b01be4> in <module>()
     11                               validation_data=val_generator,
     12                               validation_steps=ceil(val_dataset_size/batch_size),
---> 13                               initial_epoch=initial_epoch)

/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                         signature += str_val
     86                     if i < len(kwargs) - 1:
---> 87                         signature += ', '
     88                 signature += ')`'
     89                 warnings.warn('Update your `' + object_name +

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2145 
   2146         try:
-> 2147             if do_validation and not val_gen:
   2148                 # Prepare data for validation
   2149                 if len(validation_data) == 2:

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in train_on_batch(self, x, y, sample_weight, class_weight)
   1831             ins = x
   1832         self._make_predict_function()
-> 1833         f = self.predict_function
   1834         return self._predict_loop(f, ins, batch_size=batch_size,
   1835                                   verbose=verbose, steps=steps)

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1412                     outs[i] /= steps
   1413         else:
-> 1414             batches = _make_batches(num_samples, batch_size)
   1415             index_array = np.arange(num_samples)
   1416             for batch_index, (batch_start, batch_end) in enumerate(batches):

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    139     # Raises
    140         ValueError: In case of invalid user-provided argument.
--> 141     """
    142     if x_weight is None or len(x_weight) == 0:
    143         return [None for _ in output_names]

ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (16, 1)

ÇAK*²µí*

**Comment by amichayfeldman** [comment]
I also have this issue..

**Comment by amichayfeldman** [comment]
I solved this problem by change batch size to 1, figure out what are size of images, and realize that some images have different shapes. So, check your input images shapes..

**Comment by Ai-is-light** [comment]
@amichayfeldman you mean every image must have the same width and height?

**Comment by Ai-is-light** [comment]
Error when checking input: expected input_1 to have shape (300, 480, 3) but got array with shape (766, 512, 3)
@amichayfeldman , this repo's code can't process the produced **.h5 data's height and width?
