### ISSUE TITLE
How can i get precision and recall instead of AP or mAP from the evaluator?

### ISSUE THREAD

**Issue by JoyceYa** [pierluigiferrari/ssd_keras#208]
@pierluigiferrari  Thanks for sharing your work, I don't quite understand the `true_positives` and `false_positives` in the evaluator, if i want to get the precision and recall for each class, should i write a new function to calculate them? Is there any information in the evaluator i can use to do that? Thanks in advance.

**Comment by haibucuo0** [comment]
hi, have you solved it？

**Comment by huangzhenjie** [comment]
hi, have you solved it？
