### ISSUE TITLE
H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.

### ISSUE THREAD

**Issue by santhoshav15** [pierluigiferrari/ssd_keras#213]
OS: Ubuntu 16.04
Python: 3.6.7
Keras: 2.2.4
Tensorflow: 1.12.0
h5py: 2.9.0

I am trying to sample the weights. Using [Weight sampling Tutorial](https://github.com/pierluigiferrari/ssd_keras/blob/master/weight_sampling_tutorial.ipynb)

> /home/lenovo/.virtualenvs/docclass/lib/python3.6/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
>   "Use dataset[()] instead.", H5pyDeprecationWarning)

This is the error that is being displayed after running the  **Sub-sample the classifier weights**

Anyone know how i can fix this?

**Comment by pierluigiferrari** [comment]
You have to post the full stack trace please, not just a snippet of it. Is this an actual error or just a warning?

**Comment by santhoshav15** [comment]
When i run the block
**Sub-sample the classifier weights**

> /home/lenovo/.virtualenvs/docclass/lib/python3.6/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> "Use dataset[()] instead.", H5pyDeprecationWarning)

This is the entire warning message that is being displayed.

**Build the model** block generates the sampled weights without any warning or error

**Comment by pierluigiferrari** [comment]
Since it's just a deprecation warning, you can ignore it, the code still works. Or, if you want to fix it, the warning itself gives a clear instruction about how this needs to be fixed.

**Comment by santhoshav15** [comment]
Yes the code seems to be working.

```
    @property
    @with_phil
    def value(self):
        """  Alias for dataset[()] """
        warn("dataset.value has been deprecated. "
            "Use dataset[()] instead.", H5pyDeprecationWarning)
        return self[()]
```

This is the code inside

> /home/lenovo/.virtualenvs/docclass/lib/python3.6/site-packages/h5py/_hl/dataset.py

How do i fix it?

**Comment by duskybomb** [comment]
@santhoshav15 just replace
```
    kernel = weight_source_file[name][name]['kernel:0'].value
    bias = weight_source_file[name][name]['bias:0'].value
```
with this
```
    kernel = weight_source_file[name][name]['kernel:0'][()]
    bias = weight_source_file[name][name]['bias:0'][()]
```

**Comment by NagabhushanSN95** [comment]
> @santhoshav15 just replace
> 
> ```
>     kernel = weight_source_file[name][name]['kernel:0'].value
>     bias = weight_source_file[name][name]['bias:0'].value
> ```
> 
> with this
> 
> ```
>     kernel = weight_source_file[name][name]['kernel:0'][()]
>     bias = weight_source_file[name][name]['bias:0'][()]
> ```

It works like a charm, which is evident from the number of likes.
But what does `[()]` mean?
