### ISSUE TITLE
ValueError: Tensor("training/SGD/Variable:0", shape=(3, 3, 3, 64), dtype=float32_ref) must be from the same graph as Tensor("SGD/momentum/read:0", shape=(), dtype=float32).

### ISSUE THREAD

**Issue by zimurui** [pierluigiferrari/ssd_keras#214]

**Comment by ahangchen** [comment]
I also meet this error, any news now? don't close this issue until it's solved. @pierluigiferrari

**Comment by momo1986** [comment]
Same issue, looks like the version problem.

**Comment by saadyousuf45** [comment]
did anyone solve this??

**Comment by Raquelie** [comment]
Hello, I got the error and my issue seemed to be that I was using get_optimizer() before creating the graph for the network

**Comment by yeyewen** [comment]
Updating tensorflow to 1.13.1 worked for me.

**Comment by phamkhactu** [comment]
I have updated, but it not worked for me!! @yeyewen . I use keras 2.2.4 , tf  1.13.1

**Comment by chenjjjjuu** [comment]
do you solve?
