### ISSUE TITLE
DegenerateBatchError

### ISSUE THREAD

**Issue by Naga-Renu** [pierluigiferrari/ssd_keras#220]
The following error generated while executing fit_generator:

FLIR_ADAS Thermal Data set had been used instead of PASCAL VOC data set

 DegenerateBatchError: You produced an empty batch. This might be because the images in the batch vary in their size and/or number of channels. Note that after all transformations (if any were given) have been applied to all images in the batch, all images must be homogenous in size along all axes.

Can anyone have idea when the above error will be thrown?

**Comment by artur99** [comment]
I also got this issue and after some hours of investigation 😂 I found out that my xmin, xmax, ymin, ymax were in the wrong order, and the generated entries in the batch were deleted by degenerate_box_handling. Fixed them and now it's all fine, I just wrote in case anyone else gets this error and this might be the problem.

**Comment by himalivaghela** [comment]
> x

can you please tell how did you solve this issue?

**Comment by rafiaahsan** [comment]
> I also got this issue and after some hours of investigation 😂 I found out that my xmin, xmax, ymin, ymax were in the wrong order, and the generated entries in the batch were deleted by degenerate_box_handling. Fixed them and now it's all fine, I just wrote in case anyone else gets this error and this might be the problem.

You save my life thanks bro :)
