### ISSUE TITLE
Cannot save inference model

### ISSUE THREAD

**Issue by metal3d** [pierluigiferrari/ssd_keras#221]
I'm trying to train ssd_7 model using the example notbook. Everything is ok and I can see my bounding boxes.

My goal is now to be able to provide a "tensorflow" inference graph (pb file). So I'm doing:

```python
from tensorflow.python.framework import graph_util
from keras_loss_function.keras_ssd_loss import SSDLoss
from keras_layers.keras_layer_AnchorBoxes import AnchorBoxes
import keras

K.clear_session()
K.set_learning_phase(0)

ssd_loss = SSDLoss(neg_pos_ratio=3, alpha=1.0)

model = keras.models.load_model(
    './ssd7_epoch-07_loss-3.0512_val_loss-2.6327.h5', 
    custom_objects={
        'AnchorBoxes': AnchorBoxes,
        'compute_loss': ssd_loss.compute_loss,
    }
)
outnames = [n.name for n in model.outputs]

sess = K.get_session()
g = graph_util.convert_variables_to_constants(
    sess,
    sess.graph.as_graph_def(),
    outnames)
```

And it throws an error:

```
AssertionError: predictions/concat:0 is not in graph
```

Looking at the graph, there is that operation in the graph... So... what's the problem ?

PS: to precise, I'm trying to build an inference graph to be able to import it inside OpenVINO, or via OpenCV.ddn - I need inference graph because training operations are not supported and the training graph is a bit "heavy"

**Comment by duarte2025** [comment]
i'm same problem, The architecture was made not only by Keras. I'm trying to solve this. If you can solve it please notify me.

**Comment by metal3d** [comment]
automatic close is not nice...

**Comment by JustVugg** [comment]
any solution for this problem?
