### ISSUE TITLE
How to Train Model on One Class

### ISSUE THREAD

**Issue by PatrickUtz** [pierluigiferrari/ssd_keras#222]
Hello Pierluigi,

First of all thank you for this incredibly detailed tutorial as it has helped me get my hands dirty with ML for my undergrad research project. As such, I am trying to use this SSD model to detect traffic cones (only 1 class) and made my own dataset of traffic cone images and annotations. I followed the weight_sampling_tutorial and made a subsampled weight for 1 class (set to random). I am wondering how I can then use this model to train off my dataset and output only 1 class (whether it is a traffic cone or not). Thank you!  @pierluigiferrari

**Comment by PatrickUtz** [comment]
@pierluigiferrari Just checking in for an update. Thank you!

**Comment by pierluigiferrari** [comment]
You would create a model with `n_classes = 1` and then load the sub-sampled weights into the model. You would also have to make sure that your dataset only contains labels for the one class, which I assume is the case (if it isn't, set `include_classes = [1]` in the parser method you're using).
