### ISSUE TITLE
How to use multi gpu in ssd_keras project? I tried, but i get an error

### ISSUE THREAD

**Issue by acejsk** [pierluigiferrari/ssd_keras#223]
from keras.utils import multi_gpu_model

model = ssd_300(image_size=(img_height, img_width, img_channels), ~~~~~

dev_gpus = K.tensorflow_backend._get_available_gpus()
nGpu = len(dev_gpus)    
if nGpu >= 2 : 
   model = multi_gpu_model(model, gpus=nGpu)
~~

error : No such layer : conv4_3_norm_mbox_conf

**Comment by LongChenCV** [comment]
Same problem, do you have solve this?

**Comment by mohanrobotics** [comment]
Did anyone use multiple GPU ?
