### ISSUE TITLE
issue on model checkpoint

### ISSUE THREAD

**Issue by yinhaoscu** [pierluigiferrari/ssd_keras#226]
I tried the ssd300_training.ipynb, the model_checkpoint would save the best model at each epoch end.  I set a breakpoint in debug mode, and checked that the AnchorBox layer contains the values for this_steps (8 or 16 or 32 ...) and this_offsets (0.5).  However when I loaded the model from the .h5 file saved by epoch checkpoint and reviewed the loaded model that the values of this_steps and this_offsets are None, the others parameters for AnchorBox layer are correct. I think it's a bug, leading to unmatched anchor box coordinates of gt box and predicted anchor box.  For example, the correct value of this_steps for conv4_3 feature map is 8, however in the loaded model, as the value is None, this_steps equals to 300/38=7.89 instead of 8.  The mAP and accuracy is only 26.8% after 120 epochs with Adam optimizer.

**Comment by Sulince** [comment]
I run  ssd300_training.ipynb in VOC07+12 ,i got error like this:
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-b6b88e11130e> in <module>()
     54                       exclude_truncated=False,
     55                       exclude_difficult=True,
---> 56                       ret=False)
     57 
     58 # Optional: Convert the dataset into an HDF5 dataset. This will require more disk space, but will

~/ssd_keras-master/data_generator/object_detection_2d_data_generator.py in parse_xml(self, images_dirs, image_set_filenames, annotations_dirs, classes, include_classes, exclude_truncated, exclude_difficult, ret, verbose)
    478                 if not annotations_dir is None:
    479                     # Parse the XML file for this image.
--> 480                     with open(os.path.join(annotations_dir, image_id + '.xml')) as f:
    481                         soup = BeautifulSoup(f, 'xml')
    482 

**FileNotFoundError: [Errno 2] No such file or directory: '/home/sulince/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/Annotations/000001.xml'**
Any change should made to the datasate??? @yinhaoscu @pierluigiferrari

**Comment by Leon924** [comment]
@Sulince  @pierluigiferrari  same problem as mine. anybody will solve that?
