### ISSUE TITLE
Train it in my own dataset and get the error

### ISSUE THREAD

**Issue by momo1986** [pierluigiferrari/ssd_keras#227]
Bug issue
        * Ubuntu16
        * Which commit of this repository you're on
        * Keras version 2.2.2
        * TensorFlow 1.12.0

I use the architecture of ssd-7:
Here is the code:

> from keras.optimizers import Adam
> from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, TerminateOnNaN, CSVLogger
> from keras import backend as K
> from keras.models import load_model
> from math import ceil
> import numpy as np
> from matplotlib import pyplot as plt
> 
> from models.keras_ssd7 import build_model
> from keras_loss_function.keras_ssd_loss import SSDLoss
> from keras_layers.keras_layer_AnchorBoxes import AnchorBoxes
> from keras_layers.keras_layer_DecodeDetections import DecodeDetections
> from keras_layers.keras_layer_DecodeDetectionsFast import DecodeDetectionsFast
> 
> from ssd_encoder_decoder.ssd_input_encoder import SSDInputEncoder
> from ssd_encoder_decoder.ssd_output_decoder import decode_detections, decode_detections_fast
> 
> from data_generator.object_detection_2d_data_generator import DataGenerator
> from data_generator.object_detection_2d_misc_utils import apply_inverse_transforms
> from data_generator.data_augmentation_chain_variable_input_size import DataAugmentationVariableInputSize
> from data_generator.data_augmentation_chain_constant_input_size import DataAugmentationConstantInputSize
> from data_generator.data_augmentation_chain_original_ssd import SSDDataAugmentation
> img_height = 1080 # Height of the input images
> img_width = 1920 # Width of the input images
> img_channels = 3 # Number of color channels of the input images
> intensity_mean = 127.5 # Set this to your preference (maybe `None`). The current settings transform the input pixel values to the interval `[-1,1]`.
> intensity_range = 127.5 # Set this to your preference (maybe `None`). The current settings transform the input pixel values to the interval `[-1,1]`.
> n_classes = 2 # Number of positive classes
> scales = [0.08, 0.16, 0.32, 0.64, 0.96] # An explicit list of anchor box scaling factors. If this is passed, it will override `min_scale` and `max_scale`.
> aspect_ratios = [0.5, 1.0, 2.0] # The list of aspect ratios for the anchor boxes
> two_boxes_for_ar1 = True # Whether or not you want to generate two anchor boxes for aspect ratio 1
> steps = None # In case you'd like to set the step sizes for the anchor box grids manually; not recommended
> offsets = None # In case you'd like to set the offsets for the anchor box grids manually; not recommended
> clip_boxes = False # Whether or not to clip the anchor boxes to lie entirely within the image boundaries
> variances = [1.0, 1.0, 1.0, 1.0] # The list of variances by which the encoded target coordinates are scaled
> normalize_coords = True # Whether or not the model is supposed to use coordinates relative to the image size
> # 1: Build the Keras model
> import tensorflow as tf
> K.clear_session() # Clear previous models from memory.
> tf.reset_default_graph()
> model = build_model(image_size=(img_height, img_width, img_channels),
>                     n_classes=n_classes,
>                     mode='training',
>                     l2_regularization=0.0005,
>                     scales=scales,
>                     aspect_ratios_global=aspect_ratios,
>                     aspect_ratios_per_layer=None,
>                     two_boxes_for_ar1=two_boxes_for_ar1,
>                     steps=steps,
>                     offsets=offsets,
>                     clip_boxes=clip_boxes,
>                     variances=variances,
>                     normalize_coords=normalize_coords,
>                     subtract_mean=intensity_mean,
>                     divide_by_stddev=intensity_range)
> 
> # 2: Optional: Load some weights
> 
> #model.load_weights('./ssd7_weights.h5', by_name=True)
> 
> # 3: Instantiate an Adam optimizer and the SSD loss function and compile the model
> 
> adam = Adam()
> 
> ssd_loss = SSDLoss(neg_pos_ratio=3, alpha=1.0)
> 
> model.compile(optimizer=adam, loss=ssd_loss.compute_loss)
> 
> # TODO: Set the path to the `.h5` file of the model to be loaded.
> 
> # We need to create an SSDLoss object in order to pass that to the model loader.
> ssd_loss = SSDLoss(neg_pos_ratio=3, alpha=1.0)
> 
> K.clear_session() # Clear previous models from memory.
> 
> 
> # 1: Instantiate two `DataGenerator` objects: One for training, one for validation.
> 
> # Optional: If you have enough memory, consider loading the images into memory for the reasons explained above.
> 
> train_dataset = DataGenerator(load_images_into_memory=False, hdf5_dataset_path=None)
> validation_dataset = DataGenerator(load_images_into_memory=False, hdf5_dataset_path=None)
> # 2: Parse the image and label lists for the training and validation datasets.
> 
> # TODO: Set the paths to your dataset here.
> 
> # Images
> train_images_dir = '/fast/right_hand_images'
> validation_images_dir = '/fast/right_hand_test'
> # Ground truth
> train_labels_filename = '/fast/right_hand_images/right_hand_label.csv'
> validation_labels_filename = '/fast/right_hand_test/right_hand_test.csv'
> train_dataset.parse_csv_center(images_dir=train_images_dir,
>                         labels_filename=train_labels_filename,
>                         input_format=['image_name', 'center_x', 'center_y', 'width', 'height', 'class_id'], # This is the order of the first six columns in the CSV file that contains the labels for your dataset. If your labels are in XML format, maybe the XML parser will be helpful, check the documentation.
>                         include_classes='all')
> validation_dataset.parse_csv_center(images_dir=validation_images_dir,
>                         labels_filename=validation_labels_filename,
>                         input_format=['image_name', 'center_x', 'center_y', 'width', 'height', 'class_id'], # This is the order of the first six columns in the CSV file that contains the labels for your dataset. If your labels are in XML format, maybe the XML parser will be helpful, check the documentation.
>                         include_classes='all')
> 
> 
> # Optional: Convert the dataset into an HDF5 dataset. This will require more disk space, but will
> # speed up the training. Doing this is not relevant in case you activated the `load_images_into_memory`
> # option in the constructor, because in that cas the images are in memory already anyway. If you don't
> # want to create HDF5 datasets, comment out the subsequent two function calls.
> 
> train_dataset.create_hdf5_dataset(file_path='dataset_right_hand_train.h5',
>                                   resize=False,
>                                   variable_image_size=True,
>                                   verbose=True)
> 
> validation_dataset.create_hdf5_dataset(file_path='dataset_right_hand_val.h5',
>                                 resize=False,
>                                 variable_image_size=True,
>                                 verbose=True)
> 
> # Get the number of samples in the training and validations datasets.
> train_dataset_size = train_dataset.get_dataset_size()
> val_dataset_size   = validation_dataset.get_dataset_size()
> 
> print("Number of images in the training dataset:\t{:>6}".format(train_dataset_size))
> print("Number of images in the validation dataset:\t{:>6}".format(val_dataset_size))
> # 3: Set the batch size.
> 
> batch_size = 16
> 
> # 4: Define the image processing chain.
> 
> data_augmentation_chain = DataAugmentationConstantInputSize(random_brightness=(-48, 48, 0.5),
>                                                             random_contrast=(0.5, 1.8, 0.5),
>                                                             random_saturation=(0.5, 1.8, 0.5),
>                                                             random_hue=(18, 0.5),
>                                                             random_flip=0.5,
>                                                             random_translate=((0.03,0.5), (0.03,0.5), 0.5),
>                                                             random_scale=(0.5, 2.0, 0.5),
>                                                             n_trials_max=3,
>                                                             clip_boxes=True,
>                                                             overlap_criterion='area',
>                                                             bounds_box_filter=(0.3, 1.0),
>                                                             bounds_validator=(0.5, 1.0),
>                                                             n_boxes_min=1,
>                                                             background=(0,0,0))
> 
> # 5: Instantiate an encoder that can encode ground truth labels into the format needed by the SSD loss function.
> 
> # The encoder constructor needs the spatial dimensions of the model's predictor layers to create the anchor boxes.
> predictor_sizes = [model.get_layer('classes4').output_shape[1:3],
>                    model.get_layer('classes5').output_shape[1:3],
>                    model.get_layer('classes6').output_shape[1:3],
>                    model.get_layer('classes7').output_shape[1:3]]
> 
> ssd_input_encoder = SSDInputEncoder(img_height=img_height,
>                                     img_width=img_width,
>                                     n_classes=n_classes,
>                                     predictor_sizes=predictor_sizes,
>                                     scales=scales,
>                                     aspect_ratios_global=aspect_ratios,
>                                     two_boxes_for_ar1=two_boxes_for_ar1,
>                                     steps=steps,
>                                     offsets=offsets,
>                                     clip_boxes=clip_boxes,
>                                     variances=variances,
>                                     matching_type='multi',
>                                     pos_iou_threshold=0.5,
>                                     neg_iou_limit=0.3,
>                                     normalize_coords=normalize_coords)
> 
> # 6: Create the generator handles that will be passed to Keras' `fit_generator()` function.
> 
> train_generator = train_dataset.generate(batch_size=batch_size,
>                                          shuffle=True,
>                                          transformations=[data_augmentation_chain],
>                                          label_encoder=ssd_input_encoder,
>                                          returns={'processed_images',
>                                                   'encoded_labels'},
>                                          keep_images_without_gt=False)
> 
> val_generator = validation_dataset.generate(batch_size=batch_size,
>                                      shuffle=False,
>                                      transformations=[],
>                                      label_encoder=ssd_input_encoder,
>                                      returns={'processed_images',
>                                               'encoded_labels'},
>                                      keep_images_without_gt=False)
> # Define model callbacks.
> 
> # TODO: Set the filepath under which you want to save the weights.
> model_checkpoint = ModelCheckpoint(filepath='ssd7_epoch-{epoch:02d}_loss-{loss:.4f}_val_loss-{val_loss:.4f}.h5',
>                                    monitor='val_loss',
>                                    verbose=1,
>                                    save_best_only=True,
>                                    save_weights_only=False,
>                                    mode='auto',
>                                    period=1)
> 
> csv_logger = CSVLogger(filename='ssd7_training_log.csv',
>                        separator=',',
>                        append=True)
> 
> early_stopping = EarlyStopping(monitor='val_loss',
>                                min_delta=0.0,
>                                patience=10,
>                                verbose=1)
> 
> reduce_learning_rate = ReduceLROnPlateau(monitor='val_loss',
>                                          factor=0.2,
>                                          patience=8,
>                                          verbose=1,
>                                          epsilon=0.001,
>                                          cooldown=0,
>                                          min_lr=0.00001)
> 
> callbacks = [model_checkpoint,
>              csv_logger,
>              early_stopping,
>              reduce_learning_rate]
> # TODO: Set the epochs to train for.
> # If you're resuming a previous training, set `initial_epoch` and `final_epoch` accordingly.
> initial_epoch   = 0
> final_epoch     = 20
> steps_per_epoch = 1000
> 
> history = model.fit_generator(generator=train_generator,
>                               steps_per_epoch=steps_per_epoch,
>                               epochs=final_epoch,
>                               callbacks=callbacks,
>                               validation_data=val_generator,
>                               validation_steps=ceil(val_dataset_size//batch_size),
>                               initial_epoch=initial_epoch)
> 
> plt.figure(figsize=(20,12))
> plt.plot(history.history['loss'], label='loss')
> plt.plot(history.history['val_loss'], label='val_loss')
> plt.legend(loc='upper right', prop={'size': 24})
> plt.saveflig('Train_epoch.fig')

I got the error:
Traceback (most recent call last):
  File "train_ssd7.py", line 230, in <module>
    initial_epoch=initial_epoch)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 39, in fit_generator
    model._make_train_function()
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 498, in _make_train_function
    loss=self.total_loss)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/optimizers.py", line 479, in get_updates
    lr_t = lr * (K.sqrt(1. - K.pow(self.beta_2, t)) /
  File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1476, in sqrt
    x = tf.clip_by_value(x, zero, inf)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py", line 66, in clip_by_value
    [t, clip_value_min, clip_value_max]) as name:
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6023, in __enter__
    g = _get_graph_from_inputs(self._values)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5664, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5600, in _assert_same_graph
    original_item))
ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32) must be from the same graph as Tensor("sub:0", shape=(), dtype=float32).

Looks like it happens in the Keras backend tensorflow structure.
How can I resolve it??
Thanks

**Comment by momo1986** [comment]
Please do not close the ticket, I rewrite the loss function as close to keras-style as possible, problem still exists.

**Comment by momo1986** [comment]
I met the problem on the case of ssd-7 training. For ssd-300, it is OK.

**Comment by Bella722** [comment]
hi, momo1986, the problem is easy,
img_height = 1080 # Height of the input images
img_width = 1920 # Width of the input images

but in ssd7, you shuold set img_height = 300, img_width = 480
here you maybe misunderstand the img_height and img_width doesn't mean the real you data size, they mean the net input size, whatever your data size is, the resize founction will work on your data to img_height = 300, img_width = 480. So correct your code will be okay.

**Comment by ftyuuu** [comment]
i also meet this problem, and the solution of Bella722 is not work.

**Comment by Bella722** [comment]
> i also meet this problem, and the solution of Bella722 is not work.
could you upload your data? I can try.

**Comment by ftyuuu** [comment]
> > i also meet this problem, and the solution of Bella722 is not work.
> > could you upload your data? I can try.

I am using the dataset used by the author. https://drive.google.com/open?id=1tfBFavijh4UTG4cGqIKwhcklLXUDuY0D

**Comment by ftyuuu** [comment]
> > i also meet this problem, and the solution of Bella722 is not work.
> > could you upload your data? I can try.

可以加下QQ吗？

**Comment by vkherde** [comment]
Hi, 
I am also facing the same issue, has anyone got an answer to this problem?

**Comment by NorwayLobster** [comment]
Hi.
have someone solved this problem? thank you very much

**Comment by 2017TJM** [comment]
Using TensorFlow backend.
D:\pycharm project deeplearning\day1\SSD\ssd_keras-master\data_generator\object_detection_2d_data_generator.py:43: UserWarning: 'BeautifulSoup' module is missing. The XML-parser will be unavailable.
  warnings.warn("'BeautifulSoup' module is missing. The XML-parser will be unavailable.")
2019-04-17 03:00:23.767154: I c:\users\user\source\repos\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-04-17 03:00:24.000366: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-04-17 03:00:24.001087: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2019-04-17 03:00:24.694358: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-17 03:00:24.694810: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0 
2019-04-17 03:00:24.695115: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N 
2019-04-17 03:00:24.695516: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4744 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "D:/pycharm project deeplearning/day1/SSD/ssd_keras-master/ssd7_training.py", line 133, in <module>
    'compute_loss': ssd_loss.compute_loss})
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\engine\saving.py", line 224, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\utils\io_utils.py", line 326, in __getattr__
    return wrapper(getattr(self.data, attr))
AttributeError: 'Group' object has no attribute 'decode'

**Comment by liuzhuang1024** [comment]
> Please do not close the ticket, I rewrite the loss function as close to keras-style as possible, problem still exists.

Problem solved after restart

**Comment by liuzhuang1024** [comment]
> > Please do not close the ticket, I rewrite the loss function as close to keras-style as possible, problem still exists.
> 
> Problem solved after restart
But generators are problematic

**Comment by 2017TJM** [comment]
loss值很大要怎么修改了

**Comment by Ai-is-light** [comment]
same problem! 
l set the n_classes = 12 and  batch_size =16
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (16, 1)

**Comment by Ai-is-light** [comment]
@lzmisscc reset what? would you mind tell us

**Comment by allen-ash** [comment]
@2017TJM 请问您是否已经解决了上面tensor必须是相同graph的问题，还有您的tensorflow和keras版本是多少？
