### ISSUE TITLE
Different dataset, slow training

### ISSUE THREAD

**Issue by Dadko4** [pierluigiferrari/ssd_keras#230]
I tried to train ssd_300 model on mapillary vistas dataset and it is too slow. Can you tell me why? Is pictures with bigger resolution problem? And what can I do to improve the speed of the training?

**Comment by Sulince** [comment]
Looks like yo have run the train file successfully. 
I run ssd300_training.ipynb in VOC07+12 ,i got error like this:
FileNotFoundError Traceback (most recent call last)
in ()
54 exclude_truncated=False,
55 exclude_difficult=True,
---> 56 ret=False)
57
58 # Optional: Convert the dataset into an HDF5 dataset. This will require more disk space, but will

~/ssd_keras-master/data_generator/object_detection_2d_data_generator.py in parse_xml(self, images_dirs, image_set_filenames, annotations_dirs, classes, include_classes, exclude_truncated, exclude_difficult, ret, verbose)
478 if not annotations_dir is None:
479 # Parse the XML file for this image.
--> 480 with open(os.path.join(annotations_dir, image_id + '.xml')) as f:
481 soup = BeautifulSoup(f, 'xml')
482

FileNotFoundError: [Errno 2] No such file or directory: '/home/sulince/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/Annotations/000001.xml'
Any change should made to the datasate???   Help  me please! @Dadko4

**Comment by Dadko4** [comment]
I am not sure, but it looks like small mistake in file paths. try to look if file '/home/sulince/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/Annotations/000001.xml' really exists.

**Comment by Leon924** [comment]
@Dadko4 @Sulince @pierluigiferrari it doesnt exists actually, but we download VOC2007 from internet, originally it dont have this.
how can we slove this problem, anybody knoe this?

**Comment by codingWw** [comment]
> I tried to train ssd_300 model on mapillary vistas dataset and it is too slow. Can you tell me why? Is pictures with bigger resolution problem? And what can I do to improve the speed of the training?

Hi there, have the slow training problem been solved? @Dadko4

**Comment by Ai-is-light** [comment]
same problem! Hi there, have the slow training problem been solved? @Dadko4

**Comment by WillowTotoro** [comment]
Hey same here, I find my code did not using GPU while training. Do y'all know why?
