### ISSUE TITLE
evaluate

### ISSUE THREAD

**Issue by mechealww2** [pierluigiferrari/ssd_keras#232]
I got error on that, anyone can help? I am really upset. It's takes me too much time.Thks.
##############################################################################
Loading labels: 100%|██████████| 5011/5011 [00:01<00:00, 3721.78it/s]
Loading image IDs: 100%|██████████| 5011/5011 [00:00<00:00, 8529.74it/s]
Creating HDF5 dataset: 100%|██████████| 186/186 [00:01<00:00, 153.88it/s]
Number of images in the validation dataset:	   186
2019-03-12 10:13:12.012518: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0)
Number of images in the evaluation dataset: 186

Producing predictions batch-wise: 100%|██████████| 24/24 [00:45<00:00,  1.91s/it]
Matching predictions to ground truth, class 1/8.: 100%|██████████| 23694/23694 [00:00<00:00, 50547.56it/s]
No predictions for class 2/8
No predictions for class 3/8
No predictions for class 4/8
No predictions for class 5/8
No predictions for class 6/8
No predictions for class 7/8
No predictions for class 8/8
Computing precisions and recalls, class 1/8
Computing precisions and recalls, class 2/8
Traceback (most recent call last):
  File "C:/Users/lenvov/PycharmProjects/lyk/DIY_robot/ssd_keras/ssd7_evaluate2.py", line 171, in <module>
    verbose=True)
  File "C:\Users\lenvov\PycharmProjects\lyk\DIY_robot\ssd_keras\eval_utils\average_precision_evaluator.py", line 226, in __call__
    self.compute_precision_recall(verbose=verbose, ret=False)
  File "C:\Users\lenvov\PycharmProjects\lyk\DIY_robot\ssd_keras\eval_utils\average_precision_evaluator.py", line 767, in compute_precision_recall
    tp = self.cumulative_true_positives[class_id]
IndexError: list index out of range

**Comment by qduOliver** [comment]
i have the same problem.have you solved it?

**Comment by qduOliver** [comment]
@mechealww2

**Comment by pierluigiferrari** [comment]
The evaluator currently cannot handle the case where the model returns no predictions at all for a one or more classes unfortunately. The OP is getting this error because the model only returns predictions for one out of the 8 classes.

You can fix this problem locally by making the changes suggested [here](https://github.com/pierluigiferrari/ssd_keras/pull/155).

That being said, if the model makes no predictions for 7 out of 8 classes, there is probably no point in evaluating the mAP.

**Comment by mechealww2** [comment]
thanks.

**Comment by qduOliver** [comment]
thank you  very much@pierluigiferrari

**Comment by huangzhenjie** [comment]
I modify it，but i still have this error，how can i do？@pierluigiferrari

**Comment by Sulince** [comment]
have you solve it? I have changed my average_precision_evaluator.py as you do, but i got this error:
`Producing predictions batch-wise: 100%|██████████| 35/35 [00:44<00:00, 1.04it/s]
Matching predictions to ground truth, class 1/10.: 100%|██████████| 44551/44551 [00:01<00:00, 33243.84it/s]
No predictions for class 2/10
No predictions for class 3/10
No predictions for class 4/10
No predictions for class 5/10
No predictions for class 6/10
No predictions for class 7/10
No predictions for class 8/10
No predictions for class 9/10
No predictions for class 10/10
Computing precisions and recalls, class 1/10
Computing precisions and recalls, class 2/10
IndexError Traceback (most recent call last)
in ()
18 return_recalls=True,
19 return_average_precisions=True,
---> 20 verbose=True)
21
22 mean_average_precision, average_precisions, precisions, recalls = results

~/SSD/ssd_keras/eval_utils/average_precision_evaluator.py in call(self, img_height, img_width, batch_size, data_generator_mode, round_confidences, matching_iou_threshold, border_pixels, sorting_algorithm, average_precision_mode, num_recall_points, ignore_neutral_boxes, return_precisions, return_recalls, return_average_precisions, verbose, decoding_confidence_thresh, decoding_iou_threshold, decoding_top_k, decoding_pred_coords, decoding_normalize_coords)
224 #############################################################################################
225
--> 226 self.compute_precision_recall(verbose=verbose, ret=False)
227
228 #############################################################################################

~/SSD/ssd_keras/eval_utils/average_precision_evaluator.py in compute_precision_recall(self, verbose, ret)
765 # Iterate over all classes.
766 for class_id in range(1, self.n_classes + 1):
--> 767
768 if verbose:
769 print("Computing precisions and recalls, class {}/{}".format(class_id, self.n_classes))

IndexError: list index out of range`

how can i solve it? i think it is still the same problem. Thank you very much! @mechealww2 @huangzhenjie @mynameiswh

**Comment by Yaoyuanzhou** [comment]
@Sulince you have solved it? i meet this problem too.if you have done it, can you email me,thanks a lot.
email: yaoyuanzhou@stu.sicau.edu.cn

**Comment by MBoaretto25** [comment]
@Yaoyuanzhou @Sulince 
I have fixed this in my code as suggested [here](https://github.com/pierluigiferrari/ssd_keras/pull/155).

```
            # In case there are no predictions at all for this class, we're done here.
            if len(predictions) == 0:
                print("No predictions for class {}/{}".format(class_id, self.n_classes))
                true_positives.append(true_pos)
                false_positives.append(false_pos)
                cumulative_true_positives.append(np.cumsum(true_pos))
                cumulative_false_positives.append(np.cumsum(false_pos))
                continue
```

**Comment by liguilan1227** [comment]
@pierluigiferrari  I changed my code by following you, but some new error occured.

No predictions for class 2/20
No predictions for class 3/20
No predictions for class 4/20
No predictions for class 5/20
No predictions for class 6/20
No predictions for class 7/20
No predictions for class 8/20
No predictions for class 9/20
No predictions for class 10/20
No predictions for class 11/20
No predictions for class 12/20
No predictions for class 13/20
No predictions for class 14/20
No predictions for class 15/20
No predictions for class 16/20
No predictions for class 17/20
No predictions for class 18/20
No predictions for class 19/20
No predictions for class 20/20
Computing precisions and recalls, class 1/20
Computing precisions and recalls, class 2/20
Computing precisions and recalls, class 3/20
Computing precisions and recalls, class 4/20
Computing precisions and recalls, class 5/20
Computing precisions and recalls, class 6/20
Computing precisions and recalls, class 7/20
Computing precisions and recalls, class 8/20
Computing precisions and recalls, class 9/20
Computing precisions and recalls, class 10/20
Computing precisions and recalls, class 11/20
Computing precisions and recalls, class 12/20
Computing precisions and recalls, class 13/20
Computing precisions and recalls, class 14/20
Computing precisions and recalls, class 15/20
Computing precisions and recalls, class 16/20
Computing precisions and recalls, class 17/20
Computing precisions and recalls, class 18/20
Computing precisions and recalls, class 19/20
Computing precisions and recalls, class 20/20
Computing average precision, class 1/20
Computing average precision, class 2/20
Computing average precision, class 3/20
Computing average precision, class 4/20
Computing average precision, class 5/20
Computing average precision, class 6/20
Computing average precision, class 7/20
Computing average precision, class 8/20
Computing average precision, class 9/20
Computing average precision, class 10/20
Computing average precision, class 11/20
Computing average precision, class 12/20
Computing average precision, class 13/20
Computing average precision, class 14/20
Computing average precision, class 15/20
Computing average precision, class 16/20
Computing average precision, class 17/20
Computing average precision, class 18/20
Computing average precision, class 19/20
Computing average precision, class 20/20
aeroplane     AP    0.0
bicycle       AP    0.0
bird          AP    0.0
boat          AP    0.0
bottle        AP    0.0
bus           AP    0.0
car           AP    0.0
cat           AP    0.0
chair         AP    0.0
cow           AP    0.0
diningtable   AP    0.0
dog           AP    0.0
horse         AP    0.0
motorbike     AP    0.0
person        AP    0.0
pottedplant   AP    0.0
sheep         AP    0.0
sofa          AP    0.0
train         AP    0.0
tvmonitor     AP    0.0
 mAP   0.0

It seems like something occured that the mAP I got was 0 in each class, but the origin weight got the same result. Could you help me ?

**Comment by alsdn1342** [comment]
I hope my comment was helpful.
i change code in average_precision_evaluator.py


```
if self.model_mode == 'training':
                # Decode.
                y_pred = decode_detections(y_pred,
                                           confidence_thresh=decoding_confidence_thresh,
                                           iou_threshold=decoding_iou_threshold,
                                           top_k=decoding_top_k,
                                           input_coords=decoding_pred_coords,
                                           normalize_coords=decoding_normalize_coords,
                                           img_height=img_height,
                                           img_width=img_width,
                                           border_pixels=decoding_border_pixels)
else:

                # Filter out the all-zeros dummy elements of `y_pred`.
                y_pred_filtered = []
                for i in range(len(y_pred)):
                    y_pred_filtered.append(y_pred[i][y_pred[i,:,0] != 0])
                y_pred = y_pred_filtered
```


to 


``` 
if self.model_mode == 'training':
                # Decode.
                y_pred = decode_detections(y_pred,
                                           confidence_thresh=decoding_confidence_thresh,
                                           iou_threshold=decoding_iou_threshold,
                                           top_k=decoding_top_k,
                                           input_coords=decoding_pred_coords,
                                           normalize_coords=decoding_normalize_coords,
                                           img_height=img_height,
                                           img_width=img_width,
                                           border_pixels=decoding_border_pixels)
else:
                y_pred = decode_detections(y_pred,
                                           confidence_thresh=decoding_confidence_thresh,
                                           iou_threshold=decoding_iou_threshold,
                                           top_k=decoding_top_k,
                                           input_coords=decoding_pred_coords,
                                           normalize_coords=decoding_normalize_coords,
                                           img_height=img_height,
                                           img_width=img_width,
                                           border_pixels=decoding_border_pixels)
```
          

If I'm wrong, please reply.

Thanks you
