### ISSUE TITLE
Keras to tf.keras

### ISSUE THREAD

**Issue by ghost** [pierluigiferrari/ssd_keras#237]
Has anyone ported this (awesome) tutorial to tf.keras from keras?
My motivation is related to training in AWS SageMaker where there is some required functionality in a tf.contrib package.

For the most part this seems pretty straight forward but I hit a wall (exceeded my talent) on 
keras_ssd300.py

```
  File "/home/ubuntu/projects/rev-tensorflow-ssd/models/keras_ssd300.py", line 318, in ssd_300
    conv4_3_norm = L2Normalization(gamma_init=20, name='conv4_3_norm')(conv4_3)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/home/ubuntu/projects/rev-tensorflow-ssd/models/keras_layers/keras_layer_L2Normalization.py", line 64, in build
    self.trainable_weights = [self.gamma]
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1639, in __setattr__
    super(Layer, self).__setattr__(name, value)
AttributeError: can't set attribute
```
If I understand this correctly, this is feeding conv4_3 into the L2 normalization layer
It is trying to set the attribute:
  self.trainable_weights = [self.gamma]
from a(n added) print statement, it looks like self.gamma = 
[<tf.Variable 'conv4_3_norm/conv4_3_norm_gamma:0' shape=(512,) dtype=float32>]

Can anyone offer a clue here?

**Comment by ghost** [comment]
I forgot to add:
tensorflow 1.13 on Ubuntu 16.04

The original model (w/ keras) ran perfectly on an AWS DL-AMI Ubuntu v22 (tensorflow 1.13) and AWS SageMaker (tensorflow 1.12).    going to tf.keras required some minor changes before hitting this problem

**Comment by pierluigiferrari** [comment]
In the `build` method, try to replace

```
gamma = self.gamma_init * np.ones((input_shape[self.axis],))
self.gamma = K.variable(gamma, name='{}_gamma'.format(self.name))
self.trainable_weights = [self.gamma]
```

with

```
self.gamma = self.add_weight(name='{}_gamma'.format(self.name),
                             shape=(input_shape[self.axis],),
                             initializer=keras.initializers.Constant(value=self.gamma_init),
                             trainable=True)
```

and you'll have to `import keras` or import the initializer somehow. I don't know whether this will to the trick, but it might. In case it does, please let me know.

I might actually port this to tf.keras at some point, but no guarantees.

**Comment by ghost** [comment]
Thanks for the response and thanks for constructing two (data_generator) great tutorials.  They both really helped me -- up to my skill limit :)
I tried your recommended fix - it pushed the error forward.
```
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 512 and 38 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,38,38,512], [38]
```
I understand the effort of porting this to tensorflow.keras.   I'm sure there are more issues in the model construction.    I hope you chose to migrate in the future.   You can mark this closed for now and again I appreciate all of your efforts.   The Keras version works perfectly.

**Comment by prabh27** [comment]
Hi @pierluigiferrari , I got the same error and I tried to add the fix that you told. This is the new error I get now: 
https://pastebin.com/c8nBFLf5

**Comment by bluelancer** [comment]
+1 for the issue, if anyone have a clue will be super grateful to learn, I am trying to work with tf 2,0 and Ubuntu 16.04

**Comment by Maioy97** [comment]
tried the same fix and got 

"ValueError: Dimensions must be equal, but are 512 and 64 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,64,64,512], [64]."
 tf 1.13

**Comment by MaAmini** [comment]
> tried the same fix and got
> 
> "ValueError: Dimensions must be equal, but are 512 and 64 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,64,64,512], [64]."
> tf 1.13

I also got the same error. Do you find any solution for that?

**Comment by Manideep08** [comment]
I am also facing the same issue, can someone please provide a fix for this?

**Comment by ghost** [comment]
again my compliments to @pierluigiferrari.   I learned a ton from this project.

Tensorflow continues to evolve quickly.   I turned my attention to the examples in the Tensorflow repo.       TF 2.0 is a significant improvement but it's also significantly different.    Also become familiar with models/research/object_detection.    Here you'll find good examples and good utilities that will help with object detection

**Comment by jessicametzger** [comment]
From the description of L2 Normalization in the [paper](https://arxiv.org/abs/1506.04579) linked in keras_layers/keras_layer_L2Normalization.py, it appears the `self.gamma` tensor should be multiplied channel-wise with `output`. The `*` operation requires inputs to have the same shape. What we need to do is dot them along the channels (`self.axis`) dimension. So one should replace

```python
return output * self.gama
```
with

```python
return tf.tensordot(output, self.gamma, [[self.axis],[0]])
```
