### ISSUE TITLE
SSD300 Inference Tutorial (weights.h5 shape error)

### ISSUE THREAD

**Issue by fabioaraujopt** [pierluigiferrari/ssd_keras#242]
I'm using `ssd300_inference.ipynb` for the first time. 

I'm just following the steps and I imported from gDrive the weights `trainval35k: SSD300`. 

The code gives me the following error: 

`
ValueError: Layer #25 (named "conv4_3_norm_mbox_conf"), weight <tf.Variable 'conv4_3_norm_mbox_conf/kernel:0' shape=(3, 3, 512, 84) dtype=float32_ref> has shape (3, 3, 512, 84), but the saved weight has shape (324, 512, 3, 3)`

Can you help me?

**Comment by anystroem** [comment]
You might have to change the number of classes in the model from 20 to 80 if you use weights trained for MS COCO. I had the same error as you have and that fixed it for me.

**Comment by 2martens** [comment]
The model uses 80 classes, which become 81 with the background class. 324 divided by 81 results in 4 which is exactly the number of boxes for the first predictor layer.

84 divided by 21 results also in 4. The model weights are only using 20 classes. That is the problem.

**Comment by Ai-is-light** [comment]
@anystroem Did you try to change the n_classes for training the new model at your new different num. classes dataset?, when I changed the n_classes for finetuning, got the following errors:
line 1149, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #25 (named "conv4_3_norm_mbox_conf"), weight <tf.Variable 'conv4_3_norm_mbox_conf/kernel:0' shape=(3, 3, 512, 52) dtype=float32_ref> has shape (3, 3, 512, 52), but the saved weight has shape (84, 512, 3, 3).

**Comment by anystroem** [comment]
@Ai-is-light I only tried inference with the pre-trained weights, I did not do any training myself

**Comment by MaxxTr** [comment]
Actually I have the same issue. Do you know what was the reason for such problem ?
