### ISSUE TITLE
ssd300_evaluation problem

### ISSUE THREAD

**Issue by Yaoyuanzhou** [pierluigiferrari/ssd_keras#246]
No predictions for class 1/21
No predictions for class 2/21
No predictions for class 3/21
No predictions for class 4/21
No predictions for class 5/21
No predictions for class 6/21
No predictions for class 7/21
No predictions for class 8/21
No predictions for class 9/21
No predictions for class 10/21
No predictions for class 11/21
No predictions for class 12/21
No predictions for class 13/21
No predictions for class 14/21
No predictions for class 15/21
No predictions for class 16/21
No predictions for class 17/21
No predictions for class 18/21
No predictions for class 19/21
No predictions for class 20/21
No predictions for class 21/21
Computing precisions and recalls, class 1/21
Traceback (most recent call last):
  File "ssd300_evaluation.py", line 188, in <module>
    verbose=True)
  File "C:\Users\Mr_Yao\Desktop\SSD\ssd_keras-master\eval_utils\average_precision_evaluator.py", line 226, in __call__
    self.compute_precision_recall(verbose=verbose, ret=False)
  File "C:\Users\Mr_Yao\Desktop\SSD\ssd_keras-master\eval_utils\average_precision_evaluator.py", line 767, in compute_precision_recall
    tp = self.cumulative_true_positives[class_id]
IndexError: list index out of range

**Comment by buaa-luzhi** [comment]
@Yaoyuanzhou 
您好！
我也遇到了同样的问题，请问您解决了吗，谢谢!

**Comment by Yaoyuanzhou** [comment]
这个问题是训练代码就有问题，训练出来保存的模型是一个空模型，所以出现问题了，但是我重新用训练代码跑出来测试的时候又有新的问题了，暂时没解决------------------ 原始邮件 ------------------
发件人: "buaa-luzhi"<notifications@github.com>
发送时间: 2019年5月7日(星期二) 上午10:12
收件人: "pierluigiferrari/ssd_keras"<ssd_keras@noreply.github.com>;
抄送: "Mr.Yao"<1904272311@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [pierluigiferrari/ssd_keras] ssd300_evaluation problem (#246)



@Yaoyuanzhou
 您好！
 我也遇到了同样的问题，请问您解决了吗，谢谢!
 
&mdash;

**Comment by buaa-luzhi** [comment]
@Yaoyuanzhou
我和您测问题是一样的，但我的模型是自己训练的，只不过使用了这个文件内的ssd300_evaluation.ipynb测试我的模型的性能，但是还是出现了和您一样的问题。

**Comment by zeruniverse** [comment]
Seems issues. can be resolved by this: https://github.com/pierluigiferrari/ssd_keras/pull/249

**Comment by Yaoyuanzhou** [comment]
> Seems issues. can be resolved by this: #249

This problem is caused by the training code, and an empty model is saved so that no category can be extracted during the test.

**Comment by fengzhao860814** [comment]
you can modify the mode =training  in ssd300_evaluation to solve it

**Comment by dlsaavedra** [comment]
in utils/average_precision_evaluate.py
change line 616 
```
if len(predictions) == 0:
                print("No predictions for class {}/{}".format(class_id, self.n_classes))
                true_positives.append(true_pos)
                false_positives.append(false_pos)

                cumulative_true_pos = np.cumsum(true_pos) # Cumulative sums of the true positives
                cumulative_false_pos = np.cumsum(false_pos) # Cumulative sums of the false positives

                cumulative_true_positives.append(cumulative_true_pos)
                cumulative_false_positives.append(cumulative_false_pos)
                continue
```
