### ISSUE TITLE
Model.fit_generator out of bounds for axis 0 with size of 2

### ISSUE THREAD

**Issue by fabioaraujopt** [pierluigiferrari/ssd_keras#247]
Hello I'm trying to run SSD model.fit_generator on part of VOC_2012 dataset.
Everything is ok, but I get an error in this mode.fit_generator function:
`Epoch 1/120

Epoch 00001: LearningRateScheduler setting learning rate to 0.001.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-22-0609844a0db5> in <module>()
      9                               validation_data=val_generator,
     10                               validation_steps=ceil(val_dataset_size/batch_size),
---> 11                               initial_epoch=initial_epoch)

10 frames
/content/ssd_keras/ssd_encoder_decoder/ssd_input_encoder.py in __call__(self, ground_truth_labels, diagnostics)
    347                 labels = convert_coordinates(labels, start_index=xmin, conversion='corners2minmax')
    348 
--> 349             classes_one_hot = class_vectors[labels[:, class_id].astype(np.int)] # The one-hot class IDs for the ground truth boxes of this batch item
    350             labels_one_hot = np.concatenate([classes_one_hot, labels[:, [xmin,ymin,xmax,ymax]]], axis=-1) # The one-hot version of the labels for this batch item
    351 

IndexError: index 4 is out of bounds for axis 0 with size 2`

**Comment by 2017TJM** [comment]
应该是数据的问题，在归一化到1的过程中出现问题

**Comment by fabioaraujopt** [comment]
How can I figure out?

**Comment by fabioaraujopt** [comment]
Does anyone can find the solution?
