### ISSUE TITLE
slow training and GPU usage low

### ISSUE THREAD

**Issue by Breezeqiuyu** [pierluigiferrari/ssd_keras#250]
![Screenshot from 2019-05-06 15-43-38](https://user-images.githubusercontent.com/43719816/57212324-eaf41680-7015-11e9-85c5-f55af78c2f91.png)
Hi，Thank you very much for the program you provided.But I have encountered some problems now.
The speed of training is too slow. My sample picture is only 1000, and batch_size=32, but it takes a few minutes for each step. It is really sad. I have seen many people have this problem before, but they have not found it. The solution, I don't know if you find a way now. Below is my GPU utilization, which is really too low. I look forward to your reply.thank you.
![Screenshot from 2019-05-06 15-50-17](https://user-images.githubusercontent.com/43719816/57212554-aa48cd00-7016-11e9-9d69-f0c196eb98fa.png)
ly.

I want to know if it is my CPU, CPU: i5 6500, and my CPU utilization is very high.
![Screenshot from 2019-05-06 16-18-25](https://user-images.githubusercontent.com/43719816/57213931-d9613d80-701a-11e9-8423-396da6108ff4.png)

**Comment by Breezeqiuyu** [comment]
Looking forward to your reply. @pierluigiferrari ,thanks

**Comment by pierluigiferrari** [comment]
The processes section of the NVIDIA-SMI screenshot shows you that TensorFlow is not using your GPU. The problem is very simple: You're training on your CPU.

**Comment by codingWw** [comment]
> The processes section of the NVIDIA-SMI screenshot shows you that TensorFlow is not using your GPU. The problem is very simple: You're training on your CPU.

Hi there, I still meet the slow training problem while using our GPU to train!  We look forward to your reply. thank you. @pierluigiferrari 
![filename](https://user-images.githubusercontent.com/12908511/57288552-41cc1f80-70ec-11e9-9d04-f8ffb4355347.png)

**Comment by Breezeqiuyu** [comment]
> The processes section of the NVIDIA-SMI screenshot shows you that TensorFlow is not using your GPU. The problem is very simple: You're training on your CPU.

Thank you very much, I have found the reason, and the program is running very well and the training speed is very fast. The reason is that the environment configuration is not correct, I reconfigured my environment, and then I can work normally, thank you very much.

**Comment by Breezeqiuyu** [comment]
> > The processes section of the NVIDIA-SMI screenshot shows you that TensorFlow is not using your GPU. The problem is very simple: You're training on your CPU.
> 
> Hi there, I still meet the slow training problem while using our GPU to train! We look forward to your reply. thank you. @pierluigiferrari
> ![filename](https://user-images.githubusercontent.com/12908511/57288552-41cc1f80-70ec-11e9-9d04-f8ffb4355347.png)

Please check your program running environment

**Comment by Breezeqiuyu** [comment]
![Screenshot from 2019-05-07 20-20-19](https://user-images.githubusercontent.com/43719816/57298800-9f209a80-7105-11e9-8232-26212d10f801.png)
![Screenshot from 2019-05-07 20-20-36](https://user-images.githubusercontent.com/43719816/57298801-9f209a80-7105-11e9-9f10-6521016f2456.png)
This is my program running environment,I hope it will help you solve your problem.

**Comment by codingWw** [comment]
> This is my program running environment,I hope it will help you solve your problem.
Thank you very much, we have some differences compared to your running environment:
1. cudatoolkit  9.2
2. cudnn  7.3.1
3. keras  2.1.6
4. tensorflow-gpu 1.12.0
We built the running environment based on the dependencies between them, so is the environment the key to the problem? We look forward to your reply. thank you.

**Comment by codingWw** [comment]
> This is my program running environment,I hope it will help you solve your problem.



    Thank you very much, we have some differences compared to your running environment:
    1. cudatoolkit 9.2
    2. cudnn 7.3.1
    3. keras 2.1.6
    4. tensorflow-gpu 1.12.0
    We built the running environment based on the dependencies between them, so is the environment the key to the problem? We look forward to your reply. thank you.
    @Breezeqiuyu

**Comment by Breezeqiuyu** [comment]
> > This is my program running environment,I hope it will help you solve your problem.
> 
> ```
> Thank you very much, we have some differences compared to your running environment:
> 1. cudatoolkit 9.2
> 2. cudnn 7.3.1
> 3. keras 2.1.6
> 4. tensorflow-gpu 1.12.0
> We built the running environment based on the dependencies between them, so is the environment the key to the problem? We look forward to your reply. thank you.
> @Breezeqiuyu
> ```

I think environment is IMPORTANT,Before my environment was wrong, the speed was very slow, and after being configured into the current environment, the speed was normal.

**Comment by Breezeqiuyu** [comment]
> > This is my program running environment,I hope it will help you solve your problem.
> 
> ```
> Thank you very much, we have some differences compared to your running environment:
> 1. cudatoolkit 9.2
> 2. cudnn 7.3.1
> 3. keras 2.1.6
> 4. tensorflow-gpu 1.12.0
> We built the running environment based on the dependencies between them, so is the environment the key to the problem? We look forward to your reply. thank you.
> @Breezeqiuyu
> ```

If you don't feel trouble, you can try my environment.

**Comment by codingWw** [comment]
> > > This is my program running environment,I hope it will help you solve your problem.
> > 
> > 
> > ```
> > Thank you very much, we have some differences compared to your running environment:
> > 1. cudatoolkit 9.2
> > 2. cudnn 7.3.1
> > 3. keras 2.1.6
> > 4. tensorflow-gpu 1.12.0
> > We built the running environment based on the dependencies between them, so is the environment the key to the problem? We look forward to your reply. thank you.
> > @Breezeqiuyu
> > ```
> 
> If you don't feel trouble, you can try my environment.

OK, let's try, thank you!

**Comment by codingWw** [comment]
> > > This is my program running environment,I hope it will help you solve your problem.
> > 
> > 
> > ```
> > Thank you very much, we have some differences compared to your running environment:
> > 1. cudatoolkit 9.2
> > 2. cudnn 7.3.1
> > 3. keras 2.1.6
> > 4. tensorflow-gpu 1.12.0
> > We built the running environment based on the dependencies between them, so is the environment the key to the problem? We look forward to your reply. thank you.
> > @Breezeqiuyu
> > ```
> 
> If you don't feel trouble, you can try my environment.


After we reconfiguring our running  environment  based on your suggestions, the problem persists. And even worse, the program can't run on the GPU.
