### ISSUE TITLE
I don't get any predictions after training model

### ISSUE THREAD

**Issue by diegoxfx** [pierluigiferrari/ssd_keras#252]
Hi, 

I've been trying to train a model with just 1 class, using the [okutama dataset](http://okutama-action.org), but at inference time the model predicts nothing, even with a confidence of 0.1. 

At training, the loss wasn't bad, 2.8 in train dataset and 4.8 in validation. I don't know why i'm not getting any predictions at inference

**Comment by Ai-is-light** [comment]
@diegoxfx me too, I used the SSD300 to train one 12 classes own dataset, after trianing , I got nothing when run inference SSD 300 with my model.
have you sovled it ?

**Comment by diegoxfx** [comment]
@Ai-is-light No, i couldn't solve it

**Comment by experimentexperiment200** [comment]
Hi, even I  tried to train for one class(products on supermarket shelves) after 80 epochs with 1000 steps per epoch with batch size of 5 and with 300*300 dimensions of images loss was only improved to 1.11,and model was predict random boxes all over testing  images and training image.
