### ISSUE TITLE
A BIG BUG! when I set n_classes from 20(default) to 12, not work!!!

### ISSUE THREAD

**Issue by Ai-is-light** [pierluigiferrari/ssd_keras#256]
when I set n_classes from 20(default) to 12, and load the pretrained model pretrained_models/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.h5', I got the follow error,

str(weight_values[i].shape) + '.')
ValueError: Layer #25 (named "conv4_3_norm_mbox_conf"), weight <tf.Variable 'conv4_3_norm_mbox_conf/kernel:0' shape=(3, 3, 512, 52) dtype=float32_ref> has shape (3, 3, 512, 52), but the saved weight has shape (84, 512, 3, 3).

**Comment by SchmiederX** [comment]
This is not a bug as you stated.  The pretrained model is trained to predict 20 classes and you reduce it to 12. but the weights it has saved are meant for 20 --> your saved weight is bigger than your new weight.

maybe look into the weight-sampling-tutorial to get a better overview on how weights and models work.
