### ISSUE TITLE
Help...!!!! error in middle of training

### ISSUE THREAD

**Issue by saadyousuf45** [pierluigiferrari/ssd_keras#262]
/ssd_keras/data_generator/object_detection_2d_patch_sampling_ops.py in __call__(self, image, labels, return_inverter)
    719                         # Translate the box coordinates to the patch's coordinate system.
    720                         new_labels = np.copy(labels)
--> 721                         new_labels[:, [ymin, ymax]] -= patch_ymin
    722                         new_labels[:, [xmin, xmax]] -= patch_xmin
    723                         # Check if the patch contains the minimum number of boxes we require.

IndexError: too many indices for array

**Comment by leonel11** [comment]
Hello, @saadyousuf45! How did you solve this problem?
