### ISSUE TITLE
Can a trained model be converted to a Tensorflow Lite model?

### ISSUE THREAD

**Issue by mattroos** [pierluigiferrari/ssd_keras#269]
I'm trying to convert a trained SSD7 model (trained on the bundled Udacity training set created by @pierluigiferrari) to a Tensorflow Lite (tflite, tf.lite) model. Has anyone tried and had success?

Here's what I'm using:
Ubuntu 16.04
Tensorflow 1.13.1
Keras 2.2.4

I removed the custom AnchorBoxes layers (just commented out the relevant code in the ```keras_ssd7.py``` file, and replaced the ```anchors_concat``` tensor in ```predictions```  with two concatenated copies of the boxes_concat tensor, just as filler, since these not used by SSDLoss during training. *[Edit addition on 6/7/19]: I also converted the ELU layers to ReLU layers.* I then trained. I then built a new model with the ```build_model``` function, copied weights from the trained model, and saved that new model (thus excluding the loss function) with or without compiling first (as I'll explain momentarily).

I tried to convert the model with this, which includes compilation:
```
model.compile(optimizer=adam)
model.save('source_model_for_conversion.h5')
converter = tf.lite.TFLiteConverter.from_keras_model_file('source_model_for_conversion.h5')
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```
and alternatively with this, which excludes model compilation:
```
model.save('source_model_for_conversion.h5')
converter = tf.lite.TFLiteConverter.from_keras_model_file('source_model_for_conversion.h5')
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

In the first version, in which I compile first, I get an error message from the ```from_keras_model_file()``` call, complaining about missing gradients:
```
WARNING:tensorflow:Output "predictions" missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to "predictions".

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-7814781bb395> in <module>
      3 #                                               'compute_loss': ssd_loss.compute_loss})
      4 # # converter = tf.lite.TFLiteConverter.from_keras_model_file(filename_model)
----> 5 converter = tf.lite.TFLiteConverter.from_keras_model_file('model_no_loss.h5')
      6 #flite_model = converter.convert()
      7 # open("converted_model.tflite", "wb").write(tflite_model)

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in from_keras_model_file(cls, model_file, input_arrays, input_shapes, output_arrays)
    368     _keras.backend.clear_session()
    369     _keras.backend.set_learning_phase(False)
--> 370     keras_model = _keras.models.load_model(model_file)
    371     sess = _keras.backend.get_session()
    372 

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py in load_model(filepath, custom_objects, compile)
    273         # weights.
    274         if model._is_graph_network:  # pylint: disable=protected-access
--> 275           model._make_train_function()
    276           optimizer_weights_group = f['optimizer_weights']
    277           optimizer_weight_names = [

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _make_train_function(self)
   1917     ]
   1918     self._make_train_function_helper('train_function',
-> 1919                                      [self.total_loss] + metrics_tensors)
   1920 
   1921   def _make_fit_function(self):

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _make_train_function_helper(self, fn_name, outputs, metric_updates)
   1893             # Training updates
   1894             updates = self.optimizer.get_updates(
-> 1895                 params=self._collected_trainable_weights, loss=self.total_loss)
   1896       # Unconditional updates
   1897       updates += self.get_updates_for(None)

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py in get_updates(self, loss, params)
    483 
    484   def get_updates(self, loss, params):
--> 485     grads = self.get_gradients(loss, params)
    486     self.updates = []
    487 

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py in get_gradients(self, loss, params)
     93     grads = K.gradients(loss, params)
     94     if None in grads:
---> 95       raise ValueError('An operation has `None` for gradient. '
     96                        'Please make sure that all of your ops have a '
     97                        'gradient defined (i.e. are differentiable). '

ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

```
In the second version, in which I do not compile the model, I get this error during the ```converter.convert()``` call.
```
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
INFO:tensorflow:Froze 58 variables.
INFO:tensorflow:Converted 58 variables to const ops.

---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-12-2bab112a9a26> in <module>
      4 # # converter = tf.lite.TFLiteConverter.from_keras_model_file(filename_model)
      5 converter = tf.lite.TFLiteConverter.from_keras_model_file('model_no_loss.h5')
----> 6 tflite_model = converter.convert()
      7 # open("converted_model.tflite", "wb").write(tflite_model)
      8 

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in convert(self)
    453           input_tensors=self._input_tensors,
    454           output_tensors=self._output_tensors,
--> 455           **converter_kwargs)
    456     else:
    457       result = _toco_convert_graph_def(

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, *args, **kwargs)
    440   data = toco_convert_protos(model_flags.SerializeToString(),
    441                              toco_flags.SerializeToString(),
--> 442                              input_data.SerializeToString())
    443   return data
    444 

~/python_envs/env_ssd_keras/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str)
    203       stderr = _try_convert_to_unicode(stderr)
    204       raise ConverterError(
--> 205           "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
    206   finally:
    207     # Must manually cleanup files.

ConverterError: TOCO failed. See console for info.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 7, in <module>
    from tensorflow.contrib.lite.toco.python.toco_from_protos import main
  File "/home/mroos/.local/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 40, in <module>
    from tensorflow.contrib import distribute
  File "/home/mroos/.local/lib/python3.6/site-packages/tensorflow/contrib/distribute/__init__.py", line 27, in <module>
    from tensorflow.contrib.distribute.python.collective_all_reduce_strategy import CollectiveAllReduceStrategy
  File "/home/mroos/.local/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/collective_all_reduce_strategy.py", line 29, in <module>
    class CollectiveAllReduceStrategy(distribute_lib.StrategyV1):
AttributeError: module 'tensorflow.python.distribute.distribute_lib' has no attribute 'StrategyV1'
```

**Comment by ogruhlke94** [comment]
I just converted it to tflite completely following your instructions. Additional I had to change the ELU activations in the convolutional layers to relu.
It worked with and without compiling the model. It was a complete new model so no training before.
I wil try to convert a trained model in a next step. Just wanted to share it with you and keep this thread active

**Comment by mattroos** [comment]
Thanks for the update, @ogruhlke94! Can you share the versions you're using of the critical software (tensorflow, keras, cuda, etc.)?  I had switched from ELU to ReLU as well, but forgot to mention that in my original post.

**Comment by ogruhlke94** [comment]
Sure:
Ubuntu 18.04
Python 3.5
Tensorflow 1.13.1
Keras 2.2.4

No cuda because I'm only testing the conversion on my notebook without any gpu

**Comment by mattroos** [comment]
Interesting. I doubt my different version of Python (3.6.7) or Ubuntu (16.04) is the problem, but I have access to an 18.04 machine, so will give it a try there in the next couple days and report back.

**Comment by ogruhlke94** [comment]
Is your training with the changes to the model working fine? The predicted boxes are really bad for me (negative values for the coordinates and max confidence of 0.05)

**Comment by mattroos** [comment]
I haven't truly trained it to convergence. I just trained it a few epochs and then tried the conversion to tflite. I wanted to make sure the conversion was possible before working to train a high-performing model. Obviously the switch to ReLU from ELU could have an impact. @pierluigiferrari, do you have a sense of the importance of ELU layers versus ReLU layers?

**Comment by mattroos** [comment]
I switched to a machine with Ubuntu 18.04 and then the conversion worked for me (that is, there were no errors, just warnings), as it did for @ogruhlke94. Both with and without model compilation. I'm still not clear why it didn't work on my 16.04 machine. I have not yet fully trained a model and measured the performance before or after conversion.

**Comment by JustVugg** [comment]
@mattroos is possible to share your edit on ssd7 for tflite?

**Comment by JustVugg** [comment]
hi @mattroos @ogruhlke94 have you try to convert this model for opencv?

**Comment by stephentandjiria** [comment]
Hi, I want to implement this in Flutter using tflite_flutter plugin, but it requires .tflite model outputs to be in this form:
[https://www.tensorflow.org/lite/models/object_detection/overview#output_signature](url)

that form is the same with a working .tflite file that is **accepted by Flutter**, the model outputs **TFLite_Detection_PostProcess, TFLite_Detection_PostProcess:1, TFLite_Detection_PostProcess:2, TFLite_Detection_PostProcess:3** as seen below:
![image](https://user-images.githubusercontent.com/75295743/103270001-a6d33800-49e9-11eb-9c72-bf7c9a2872a0.png)

but when I see the outputs of the keras_ssd7.py in this repo, the output shape is different:

After conversion to .tflite, the output shape is different, i.e. (1, 1, 20):
```
model_path = 'model_expw_ssd7_300x300_epoch-07_loss-3.2785_val_loss-3.6043.h5'
ssd_loss = SSDLoss(neg_pos_ratio=3, alpha=1.0)
K.clear_session() # Clear previous models from memory.
model = load_model(model_path, custom_objects={'AnchorBoxes': AnchorBoxes,
                                               'compute_loss': ssd_loss.compute_loss})
# Common conversion
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
with open('tflite_expw_300x300.tflite', 'wb') as f:
  f.write(tflite_model)
```
![image](https://user-images.githubusercontent.com/75295743/103271109-e1d66b00-49eb-11eb-88cd-5e207cf5052c.png)

Via Python (before conversion):
```
y_pred = model.predict(batch_images)
print('y_pred.shape is : '+ str(y_pred.shape))
>> y_pred.shape is : **(1, 7160, 20)**
```

Is there any way to change the output to the appropriate shape?
Really appreciate if anyone could help, cheers!

**Comment by gemenerik** [comment]
> Hi, I want to implement this in Flutter using tflite_flutter plugin, but it requires .tflite model outputs to be in this form: [https://www.tensorflow.org/lite/models/object_detection/overview#output_signature](url=[https://www.tensorflow.org/lite/models/object_detection/overview#output_signature)
> 
> ...
> 
> Is there any way to change the output to the appropriate shape? Really appreciate if anyone could help, cheers!

I know this can be done with the TensorFlow Object Detection API, but I would like to avoid adding a dependency to it. Did you find a way to do it?
