### ISSUE TITLE
Prediction on a Single Image NOT Included in the Validation Set

### ISSUE THREAD

**Issue by ecophy** [pierluigiferrari/ssd_keras#28]
Thanks a lot for great materials here :) I would like to make prediction on a single image (e.g. 000.jpg) NOT included in the validation set. Can anyone help me to revise the code here (train_ssd7.ipynb) for the purpose? I really appreciate your kind attention and warm help!

**Comment by pierluigiferrari** [comment]
1. Load the image.
2. Put it in a list or Numpy array: `imgs = [img]`
3. Call `model.predict(imgs)`

`BatchGenerator` does currently not account for the case of generating batches of images only, but not labels. Maybe I'll add that possibility.

**Comment by ecophy** [comment]
Thanks a lot ^_^ I followed your suggestion and revised your code in the following way: "Revised Code" below. In the final stage of "Draw the predicted boxes in blue" below, I get an image with grey colors and blue boxes (instead of the original image which is NOT grey-colored). Can you help me to correct the code below? I really appreciate your kind help! 

# ============================ 
# Revised Code: Prediction on a Single Image 
# ============================ 

# Generate a sample 
import cv2 
import numpy as np 

X=Image.open('...\\001.jpg') 
X.load() 
plt.figure(figsize=(20,12))
plt.imshow(X)
current_axis = plt.gca()
X=np.asarray(X,dtype="float32") 
X=np.expand_dims(X,axis=0) 
i=0 

# Make a prediction
y_pred = model.predict(X)

# Decode the raw prediction `y_pred`
y_pred_decoded = decode_y2(y_pred,
                           confidence_thresh=0.5,
                           iou_threshold=0.4,
                           top_k='all',
                           input_coords='centroids',
                           normalize_coords=False,
                           img_height=None,
                           img_width=None)
print("Decoded predictions (output format is [class_id, confidence, xmin, xmax, ymin, ymax]):\n")
print(y_pred_decoded[i])

# Draw the predicted boxes onto the image
plt.figure(figsize=(20,12))
plt.imshow(X[i])
current_axis = plt.gca()
classes = ['B-Ground', 'U-Clothes', 'L-Clothes', 'H-Bags'] # Just so we can print class names onto the image instead of IDs

# Draw the predicted boxes in blue
for box in y_pred_decoded[i]:
    label = '{}: {:.2f}'.format(classes[int(box[0])], box[1])
    current_axis.add_patch(plt.Rectangle((box[2], box[4]), box[3]-box[2], box[5]-box[4], color='blue', fill=False, linewidth=2))  
    current_axis.text(box[2], box[4], label, size='x-large', color='white', bbox={'facecolor':'blue', 'alpha':1.0})

**Comment by pierluigiferrari** [comment]
As of the latest commit it is now also possible to use `BatchGenerator` to serve batches of images only (no labels).

You can do this either by passing the constructor a text file that contains the names (just the base names, not the full file paths) of the images you would like to generate:

```
generator = BatchGenerator(filenames='list_of_your_images.txt',
                                              filenames_type='text',
                                              images_path='path_to_directory/that_contains_the_images')
```

Or you could just pass a Python list that contains the full file paths of the images you would like to generate:

```
generator = BatchGenerator(filenames=python_list_of_your_images)
```

Then call `generator.generate()` with the desired options (it must be `train=False`). Note that the generator returns two lists in this case, the batch of images, and a list of the names of the images in the batch.

**Comment by ecophy** [comment]
Thanks a lot for your kind help ^_^ I followed your suggestion and revised your code as below ("Revised code"). Then, I get an error message "TypeError: Can't mix strings and bytes in path components ". Can you help me to correct the revised code below? I really appreciate your kind attention and warm help! 

#Revised code: 
n000='...\\l000_p.txt' # Text file containing the base names only (without the path names) 
p000='...\\s001_p\\' # Image files to make predictions on 

predict_generator = BatchGenerator(filenames=n000,
                                                           filenames_type='text',
                                                           images_path=p000)

**Comment by pierluigiferrari** [comment]
The list you pass to the constructor must contain the paths to the images, not the images themselves, i.e. your list should be

`l000.append('...\001.jpg')`

The batch generator loads the images for you, you only give it the paths where to find those images.

**Comment by ecophy** [comment]
Thanks a lot for your kind help ^_^ I followed your suggestion and revised your code as below ("Revised code"). Then, I get [ ] for "print("Predicted boxes:\n") print(y_pred_decoded[i])" (I get no predicted box here). Can you help me to correct the revised code below? I really appreciate your kind attention and warm help!

#Revised code:
# Generate a sample 
l000=[] # List of Images 
l000.append('...\\001.jpg') 
print(l000) 
g000 = BatchGenerator(filenames=l000,
                                       filenames_type='pickle') 
g001 = g000.generate(batch_size=1,
                                     train=False,
                                     equalize=False,
                                     brightness=False,
                                     flip=False,
                                     translate=False,
                                     scale=False,
                                     max_crop_and_resize=(300, 300, 1, 3),
                                     full_crop_and_resize=(300, 300, 1, 3, 0.5),
                                     random_crop=False,
                                     crop=False,
                                     resize=False,
                                     gray=False,
                                     limit_boxes=True,
                                     include_thresh=0.4,
                                     diagnostics=False)
X, filenames = next(g001)
i = 0 # Which batch item to look at
print("Image:", filenames[i])
print()

#Make a prediction
y_pred = model.predict(X)

#Decode the raw prediction `y_pred`
y_pred_decoded = decode_y2(y_pred,
                                                 confidence_thresh=0.5,
                                                 iou_threshold=0.4,
                                                 top_k='all',
                                                 input_coords='centroids',
                                                 normalize_coords=normalize_coords,
                                                 img_height=img_height,
                                                 img_width=img_width)
np.set_printoptions(precision=2, suppress=True, linewidth=90)
print("Predicted boxes:\n")
print(y_pred_decoded[i]) # <= I get [] here 

#Draw the predicted boxes onto the image
plt.figure(figsize=(20,12))
plt.imshow(X[i])
current_axis = plt.gca()
classes = ['B', 'U', 'L', 'H'] # Just so we can print class names onto the image instead of IDs
for box in y_pred_decoded[i]:
    label = '{}: {:.2f}'.format(classes[int(box[0])], box[1])
    current_axis.add_patch(plt.Rectangle((box[2], box[4]), box[3]-box[2], box[5]-box[4], color='blue', fill=False, linewidth=2))  
    current_axis.text(box[2], box[4], label, size='x-large', color='white', bbox={'facecolor':'blue', 'alpha':1.0})

**Comment by TanmoyDL** [comment]
I got the error like " expected input_1 to have 4 dimensions, but got array with shape (687, 1087, 3)" while passing a image into model.predict([image]).
images = cv2.imread('./examples/pred_01.png')
image = np.array(images)
#Y_pred = model.predict([images]) 
#Y_pred = model.predict([image])
I have tried both the ways but I got the same error as mentioned the above. 
I am waiting for your valuable suggestions.

**Comment by pierluigiferrari** [comment]
@TanmoyDL apparently the input to `model.predict()` needs to be an array, so the way to do it is

image = cv2.imread('./examples/pred_01.png')
y_pred = model.predict(np.array([image]))

@ecophy if the loss is 317 then something is likely very wrong and there is no point trying to make any predictions with such a model, but with the provided information I can't tell anything more specific since I know nothing about how you trained the model, on what data, etc.

**Comment by TanmoyDL** [comment]
@pierluigiferrari Thanks for your kind help. It is working fine. 
Now, I will test it on the video data by passing the video frames into model.predict (). I hope it should work.

**Comment by ecophy** [comment]
Thanks a lot for your kind help :) I will restart the process (data building & model training) and I will report the result soon. I really appreciate your kind attention and warm help!

**Comment by SahadevPoudel** [comment]
> @pierluigiferrari Thanks for your kind help. It is working fine.
> Now, I will test it on the video data by passing the video frames into model.predict (). I hope it should work.

Did you test on video data?

**Comment by Alex1101a** [comment]
@SahadevPoudel  did you manage to detect on a video?
if so are you willing to share your code? 
i got stuck and tried for several days now and would appreciate any help or hint from you :)
