### ISSUE TITLE
Converting SSD_7 keras to tensorflow

### ISSUE THREAD

**Issue by AkilaPurna** [pierluigiferrari/ssd_keras#285]
We followed the following steps to achieve our target,

1. We converted the following 
```
import tensorflow as tf
from tensorflow.python.keras.optimizers import Adam
from tensorflow.python.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, TerminateOnNaN, CSVLogger
from tensorflow.python.keras import backend as K
from tensorflow.python.keras.models import load_model
```
2. Then we found an error in the _keras_layer_AnchorBoxes.py_ file. There we changed the following lines
```
[173]box_height = self.this_scale * size // np.sqrt(ar)
[180]batch_size, feature_map_height, feature_map_width, feature_map_channels = x._shape_val
[182]batch_size, feature_map_channels, feature_map_height, feature_map_width = x._shape_val
[188]step_height = self.img_height // feature_map_height
[189]step_width = self.img_width // feature_map_width
[274]boxes_tensor, dtype='int32'), (K.shape(x)[0], 1, 1, 1, 1))

```
There we are stuck with the error 
```
TypeError: in converted code:

    c:\Users\akilap\Desktop\Sprint 10\New folder\ssd_object_detection\SSD7-tf\keras_layers\keras_layer_AnchorBoxes.py:209 call *
        cy = np.linspace(offset_height * step_height, (offset_height +
    C:\Users\akilap\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py:438 __rmul__
        return self * other

    TypeError: unsupported operand type(s) for *: 'Dimension' and 'float'
```
It'll be a great help if you can help us out!

Thank you.

**Comment by CaveSven** [comment]
This line
> [182]batch_size, feature_map_channels, feature_map_height, feature_map_width = x._shape_val

causes batch_size, feature_map_channels, feature_map_height, feature_map_width to be tensors. If you want to perform normal float operations, cast them to floats first. After l.182, insert

`batch_size, feature_map_channels, feature_map_height, feature_map_width = batch_size.value, feature_map_channels.value, feature_map_height.value, feature_map_width.value`
