### ISSUE TITLE
loss function error

### ISSUE THREAD

**Issue by michalkowalski94** [pierluigiferrari/ssd_keras#289]
Tensorflow 1.14.0
Keras 2.2.5
Python 3.6.8

While trying to train SSD300 an error occurs
`

Epoch 00001: LearningRateScheduler setting learning rate to 0.001.
   1/2575 [..............................] - ETA: 4:19:27 - loss: nanBatch 0: Invalid loss, terminating training

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-482315d7a579> in <module>
      5                               validation_data=val_generator,
      6                               validation_steps=ceil(val_dataset_size/batch_size),
----> 7                               initial_epoch=initial_epoch)

c:\users\micha\appdata\local\programs\python\python36\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

c:\users\micha\appdata\local\programs\python\python36\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1656             use_multiprocessing=use_multiprocessing,
   1657             shuffle=shuffle,
-> 1658             initial_epoch=initial_epoch)
   1659 
   1660     @interfaces.legacy_generator_methods_support

c:\users\micha\appdata\local\programs\python\python36\lib\site-packages\keras\engine\training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    253                     break
    254 
--> 255             callbacks.on_epoch_end(epoch, epoch_logs)
    256             epoch += 1
    257             if callbacks.model.stop_training:

c:\users\micha\appdata\local\programs\python\python36\lib\site-packages\keras\callbacks.py in on_epoch_end(self, epoch, logs)
    150         logs = logs or {}
    151         for callback in self.callbacks:
--> 152             callback.on_epoch_end(epoch, logs)
    153 
    154     def on_train_batch_begin(self, batch, logs=None):

c:\users\micha\appdata\local\programs\python\python36\lib\site-packages\keras\callbacks.py in on_epoch_end(self, epoch, logs)
    700         if self.epochs_since_last_save >= self.period:
    701             self.epochs_since_last_save = 0
--> 702             filepath = self.filepath.format(epoch=epoch + 1, **logs)
    703             if self.save_best_only:
    704                 current = logs.get(self.monitor)

KeyError: 'val_loss'
`

**Comment by ailixe** [comment]
i have the same problem.have you solved it?

**Comment by jc-barreto** [comment]
Have someone solved it? I have the same problem
