### ISSUE TITLE
Error Message for Retraining the SSD7 Model after Restarting the Keras Program 

### ISSUE THREAD

**Issue by ecophy** [pierluigiferrari/ssd_keras#29]
Thanks a lot for great materials here :) Retraining the SSD7 model is done well before I close the Keras program for the first time. However, I get an error message below after I restart the Keras program and retrain the SSD7 model (I run 1., skip 2.1 then I run 2.2 and the rest in train_ssd7.ipynb; img_height = 260, img_width = 200, img_channels = 3). Can anyone help to retrain the SSD7 model after reopening the Keras program? I really appreciate your kind attention and warm help! 

#Error message: 
ValueError: Error when checking target: expected predictions to have shape (None, 3424, 16) but got array with shape (30, 10316, 16)

**Comment by ecophy** [comment]
Thanks a lot for great materials here :) I changed the model from SSD7 to SSD300 and set image width and height to 300 as in the original code. Then, retraining the SSD300 model was done well even after restarting the Keras program. Please, have a nice day!

**Comment by pierluigiferrari** [comment]
The input image size got messed up at some point, which results in different spatial dimensions in all tensors of the network, in particular of the `predictions` layer. I don't know how exactly you arrived at this point, but 10316 is exactly the number of boxes that the model outputs with the default settings in `train_ssd7.ipynb` with the preset image size of `(300, 480)`.

I realize that it is not ideal that the `predictor_sizes` variable is hard-coded in the code cell in section 1. If you change the image size, the predictor sizes will also change, so the way the notebook is currently set up is error-prone. I'll change that.

**Comment by pierluigiferrari** [comment]
The potential source of this problem has been fixed in the latest commits and should now no longer occur, at least not if you follow the instructions in the notebook.

**Comment by ecophy** [comment]
Thanks a lot for your kind help and great materials here ^_^ I will always keep your suggestion above in mind :) Please, have a nice day!

**Comment by pierluigiferrari** [comment]
I'll close this for now.
