### ISSUE TITLE
Model not learning.

### ISSUE THREAD

**Issue by drorhilman** [pierluigiferrari/ssd_keras#3]
Thanks for the amazing repository and explanation. 
I am trying to learn a model with one class and 1000 examples, using code very similar to train_ssd7.ipynb
But the model is always starting from loss=0 and doesn't learn anything - what may be the cause of that ?

**Comment by drorhilman** [comment]
well, I figured it out - I gave the single class I was using the number '0' (in the csv file), when I changed that to '1' it seems to work.

**Comment by pierluigiferrari** [comment]
Glad you resolved the issue! In case other problems come up, let me know.
