### ISSUE TITLE
Incompatible shapes in concatenate

### ISSUE THREAD

**Issue by jlhervy** [pierluigiferrari/ssd_keras#304]
Hello, 

I am trying to make this work with tf2.0. I am first working on the smaller **ssd7**, and at the moment I am blocked because at this line in keras_ssd7.py : 

` predictions = Concatenate(axis=2, name='predictions')([classes_softmax, boxes_concat, anchors_concat])`

The shape of **anchors_concat** in axis 1 is incompatible with the other two (7168 vs 11692 for the other two). 

I tried debugging, and now there is something that I don't understand because the **anchors** are built on top of the **boxes** layers, and the **boxes** layers have the shape : 

`(batch, height, width, n_boxes * 4)`

But the AnchorBoxes layer has this input shape : 

`(batch, channels, height, width)` if `dim_ordering = 'th'`
`(batch, height, width, channels)` if `dim_ordering = 'tf'`.

So it seems that the shapes are not consistent, as 'channels' is not in the output shape of boxes. 

Could someone enlighten me on this issue ? 

Thank you

**Comment by devdrian** [comment]
Hi jlhervy,

If I remember it correctly, the problem is in `AnchorBoxes.call()`:
`
        # We need the shape of the input tensor
        if K.image_dim_ordering() == 'tf':
            batch_size, feature_map_height, feature_map_width, feature_map_channels = x._keras_shape
        else: # Not yet relevant since TensorFlow is the only supported backend right now, but it can't harm to have this in here for the future
            batch_size, feature_map_channels, feature_map_height, feature_map_width = x._keras_shape
`

If I'm not mistaken, `K.image_dim_ordering()` doesn't return `tf` anymore in tf2, therefore it uses the ordering specified for the Theano backend in the else part. However, you should use `batch_size, feature_map_height, feature_map_width, feature_map_channels = x._shape_val`.

Hope this helps

**Comment by jlhervy** [comment]
Thank you for your answer, 

Actually I already changed this part : 
I replaced `K.image_dim_ordering()` with `K.image_data_format()`, and it seems to work.

The problem that I have is rather that the tensor that we give in input to the **AnchorBoxes** layer does not have the correct dimensions : 

We give : 
`(batch, height, width, n_boxes * 4)`
When AnchorBoxes expects this : 
`(batch, channels, height, width)`, 

(ligns 327 and 334 in **keras_ssd7.py**),

So there is no way it can work correctly right ? 
When I run in debug mode and inspect the tensor shape of **x**, it has indeed the shape `(batch, height, width, n_boxes * 4)`, and thus cannot even be reshaped to the correct shape. 

But in ssd_input_encoder.py, the correct shape is passed and thus here it works. 

I don't fully understand the differences between the initial anchors that we compute in **ssd_input_encoder.py** and the ones in the **AnchorBoxes** layer though.

**Comment by shemilhashan** [comment]
I get below error just by running ssd300_training.ipynb

ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 8732, 21), (None, 8732, 4), (None, 7584, 8)]

Checked the K.image_dim_ordering() , K.image_data_format() in AnchorBoxes file and it seems to be replaced

**Comment by babak-abad** [comment]
Hi. Anyone solved this problem?
I get this error: 
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 191040, 3), (None, 191040, 4), (None, 28800, 8)]

**Comment by AhmedShamli** [comment]
Hello @babak-abad  did you manage to solve this!
I have the same problem

**Comment by bfhaha** [comment]
Hello guys! I had the same problem before and have solved it by changing K.image_dim_ordering() == 'tf' to K.image_data_format() == 'channels_last'
See https://www.gitmemory.com/issue/pierluigiferrari/ssd_keras/313/819393660
