### ISSUE TITLE
Dimensions Must be equal

### ISSUE THREAD

**Issue by Benhaughian** [pierluigiferrari/ssd_keras#307]
The folllowing error keeps appearing on both 512 & 300.
i have tried various versions on Tensorflow and Keras on two different computers
using multiple versions of python 3.6 & 3.7.

ValueError: Dimensions must be equal, but are 512 and 38 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,38,38,512], [38].

( conv4_3_norm = L2Normalization(gamma_init=20, name='conv4_3_norm')(conv4_3) )

This happens before any weights have been loaded.

Any Ideas?

**Comment by Benhaughian** [comment]
I have figured it out,

if K.image_data_format() == 'tf':
            self.axis = 3

Is the problem with both L2 gamma addition also the AnchorBoxes.py,

Image_data_format() does not == 'tf' so the [ELSE]/[ELIF] statement is used in the code, which is not compatible due to the input shapes.

change the 'tf' to 'channel_last' as this is the output from Image_data_format()

it needs to be changed in 
keras_layer_AnchorBoxes.py (twice)
keras_layer_L2Normalization.py (Once)

**Comment by FOLEFAC** [comment]
thanks @Benhaughian for the help!!!
but the channel_last is instead channels_last

**Comment by Alex1101a** [comment]
@FOLEFAC @Benhaughian i did the changes you suggested, thanks very much for that exellent tip. 
But i still have some problems and wanted to ask if you could give me a hint please.
At step 1.1 the programm still crashes with the Error Message:
`ValueError: Dimensions must be equal, but are 512 and 38 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,38,38,512], [38].`

**Comment by shunmian** [comment]
@Alex1101a , I'm not sure the cause of the issue but after I change keras version to 2.1.0, the error `ValueError: Dimensions must be equal, but are 512 and 38 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,38,38,512], [38].` disappear.

**Comment by gaganag50** [comment]
@FOLEFAC @Benhaughian I am very new to deep learning and I am unable to understand that where exactly changes have to be made in keras_layer_AnchorBoxes.py. Can you please specify the location and changes that need to made.

**Comment by sarahosini** [comment]
> The folllowing error keeps appearing on both 512 & 300.
> i have tried various versions on Tensorflow and Keras on two different computers
> using multiple versions of python 3.6 & 3.7.
> 
> ValueError: Dimensions must be equal, but are 512 and 38 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,38,38,512], [38].
> 
> ( conv4_3_norm = L2Normalization(gamma_init=20, name='conv4_3_norm')(conv4_3) )
> 
> This happens before any weights have been loaded.
> 
> Any Ideas?

Hi, I also have this problem and it was not solved by changing change the 'tf' to 'channel_last'    my problem.

**Comment by ksh108405** [comment]
https://www.tensorflow.org/api_docs/python/tf/keras/backend/image_data_format
change to `'channels_last'`, not `'channel_last'`
