### ISSUE TITLE
How to set bounding box config?

### ISSUE THREAD

**Issue by monica352** [pierluigiferrari/ssd_keras#31]
Thank you very much for your code and detailed explanation! It's really helpful.
I used ssd300 to train other dataset, and then used the trained model to do prediction. But I got the following output:
![000](https://user-images.githubusercontent.com/32580036/33841099-bab37982-de64-11e7-953e-86867e94883e.png)
How should I set the config to get only 1 bounding box output, please? Thank you very much!

**Comment by monica352** [comment]
In the prediction part, the code use 'decode_y' to form bounding box, in which there is a config 'confidence_thresh', which is to control the lowest confidence of output bounding box. Just increase this 'confidence_thresh', and those extra boxes with lower confidence ratio will be filtered.

**Comment by pierluigiferrari** [comment]
Yes, the raw model output tensor contains thousands of box predictions and you need to use the options in `decode_y()` or `decode_y2()` to filter out the bad predictions. The documentation of these two functions explains what the individual arguments do. The `confidence_thresh` determines what the minimum confidence for a good prediction needs to be and `iou_threshold` determines how aggressively NMS will be performed. These two arguments should be the preferred tools to get the desired output, but the number of boxes in the decoded output will still vary from image to image.

If you want to force the decoded output to contain only a specific number of boxes (e.g. only 1 box), then you can set the `top_k` argument to the respective number (e.g. 1).

**Comment by monica352** [comment]
Thank you for your reply! Yes, I did not train the model enough, because I trained the model using another dataset and changed the code a little bit to adapt to this dataset and its xml file, so I just want to see quickly whether it can work and just trained the model with a small part of data. Next I will try with larger dataset. Thank you very much!!!
