### ISSUE TITLE
Hello, I have same issue (ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32)......) and tried tensorflow 1.13-2.0 and with keras 2.0-2.3 and no luck. Also tried to changed K. Clear_session() to keras.backend.clear_session() and still have same error. Can anyone help ?

### ISSUE THREAD

**Issue by ghost** [pierluigiferrari/ssd_keras#310]
Hello, I have same issue (ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32)......) and tried tensorflow 1.13-2.0 and with keras 2.0-2.3 and no luck. Also tried to changed K. Clear_session() to keras.backend.clear_session() and still have same error. Can anyone help ?
Thanks

_Originally posted by @pascaltx in https://github.com/pierluigiferrari/ssd_keras/issues/283#issuecomment-551967754_

**Comment by vineeth0911** [comment]
same issue 👎 
please any one help to resolve this error.!

**Comment by pascaltx** [comment]
if anyone solved problem, please share with us to ovecome.
