### ISSUE TITLE
ssd7_train.ipynb,anchor_concat can not concate

### ISSUE THREAD

**Issue by jiaobendaye** [pierluigiferrari/ssd_keras#313]
when i run create model cell, get error `    predictions = Concatenate(axis=2, name='predictions')([classes_softmax, boxes_concat, anchors_concat])....A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 11692, 6), (None, 11692, 4), (None, 7168, 8)]`.why the anchors_concat 's shape on axis 1 is not equal to the others?

**Comment by apichat583** [comment]
Hi, I had the same problem. In my case, I change K.image_dim_ordering() == 'tf'
to K.image_data_format=="channels_first' and it works. It'a problem of conversion between python 2 and 3.

**Comment by jiaobendaye** [comment]
> Hi, I had the same problem. In my case, I change K.image_dim_ordering() == 'tf'
> to K.image_data_format=="channels_first' and it works
Tks, I will try it.

**Comment by PaulZhangIsing** [comment]
Please go to keras_layers/anchor boxes scripts and change the K.image_dim_ordering() == 'tf':(line 171 and line 258 )
to K.image_data_format() == 'channels_last':
