### ISSUE TITLE
TF2 : AttributeError: Can't set the attribute "trainable_weights", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.

### ISSUE THREAD

**Issue by samsterckval** [pierluigiferrari/ssd_keras#322]
Implementation on TF2 gives me the error : 
```AttributeError: Can't set the attribute "trainable_weights", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.```
at the ssd_300 or ssd_500 model creation.
--> ```model = ssd_300(...)``` with nothing changed to the parameters.

I have changed all the ```keras...``` to ```tensorflow.keras...```,
and the ```keras.engine...``` ones to ```tensorflow.keras.layers...```
```tf.__version__ : 2.0.0```
```from scipy.misc import imread``` changed to ```from matplotlib.pyplot import imread```

Anyone with a solution for this?

If more info is required, I would be glad to provide.

(I'm sorry for very brief explanation, I don't have much time on my hands at this moment)

**Comment by JDanielGar96** [comment]
Have the same problem with TimeSeriesAttention

>     def build(self, input_shape):
>         dimensions = input_shape[2]
>         timed = keras.models.Sequential(name='per_time_step')
>         timed.add(
>             keras.layers.Dense(dimensions, input_shape=(dimensions,), kernel_initializer='zeros', activation='softmax', name='att_dense1')
>         )
>         timed.add(keras.layers.Dense(dimensions, kernel_initializer='glorot_normal', activation='tanh', name='att_dense2'))
>         self.timed = keras.layers.TimeDistributed(timed, name='att_td')
>         self.timed.build(input_shape)
>         self.trainable_weights = self.timed.trainable_weights
>         self.non_trainable_weights = self.timed.non_trainable_weights
>         self.built = True

**Comment by aleksandar-lazic** [comment]
Same problem with TF1.

**Comment by remic33** [comment]
same problem with tf2.1

**Comment by LucyChen0228** [comment]
Same problem with the tf 2.X on Colab

**Comment by andreapi87** [comment]
same problem with tf2.1

**Comment by jessebr2** [comment]
> Have the same problem with TimeSeriesAttention
> 
> > ```
> > def build(self, input_shape):
> >     dimensions = input_shape[2]
> >     timed = keras.models.Sequential(name='per_time_step')
> >     timed.add(
> >         keras.layers.Dense(dimensions, input_shape=(dimensions,), kernel_initializer='zeros', activation='softmax', name='att_dense1')
> >     )
> >     timed.add(keras.layers.Dense(dimensions, kernel_initializer='glorot_normal', activation='tanh', name='att_dense2'))
> >     self.timed = keras.layers.TimeDistributed(timed, name='att_td')
> >     self.timed.build(input_shape)
> >     self.trainable_weights = self.timed.trainable_weights
> >     self.non_trainable_weights = self.timed.non_trainable_weights
> >     self.built = True
> > ```

Change the:
> >     self.trainable_weights = self.timed.trainable_weights
For:
> >     self.trainable_weights.append(self.timed.trainable_weights)

**Comment by gungor2** [comment]
This does not work for me. It does not throw error but it does not append the values either.
> > Have the same problem with TimeSeriesAttention
> > > ```
> > > def build(self, input_shape):
> > >     dimensions = input_shape[2]
> > >     timed = keras.models.Sequential(name='per_time_step')
> > >     timed.add(
> > >         keras.layers.Dense(dimensions, input_shape=(dimensions,), kernel_initializer='zeros', activation='softmax', name='att_dense1')
> > >     )
> > >     timed.add(keras.layers.Dense(dimensions, kernel_initializer='glorot_normal', activation='tanh', name='att_dense2'))
> > >     self.timed = keras.layers.TimeDistributed(timed, name='att_td')
> > >     self.timed.build(input_shape)
> > >     self.trainable_weights = self.timed.trainable_weights
> > >     self.non_trainable_weights = self.timed.non_trainable_weights
> > >     self.built = True
> > > ```
> 
> Change the:
> 
> > > ```
> > > self.trainable_weights = self.timed.trainable_weights
> > > ```
> 
> For:
> 
> > > ```
> > > self.trainable_weights.append(self.timed.trainable_weights)
> > > ```

**Comment by faisalshahbaz** [comment]
I actually found the solution, You need to set self._trainable_weights instead of self.trainable_weights

**Comment by spratik** [comment]
I am facing this issue in TF 2.2
