### ISSUE TITLE
Many Prediction Boxes generated 

### ISSUE THREAD

**Issue by wala-nias** [pierluigiferrari/ssd_keras#336]
Hi,
is there any possibility to define the number of Anchor boxes to generate during training (SSD7). When I run the prediction on a new image I got many prediction boxes around each detected object (also with the same accuracy), do you have any Idea how to fix this.
Knowing that my Dataset is pretty simple (colored Blocks with three different sizes), I thought that reducing the number of Anchor boxes generated during training will help to fix this. 
Any suggestions ? 
Thanks

**Comment by hiren-2911** [comment]
> Hi,
> is there any possibility to define the number of Anchor boxes to generate during training (SSD7). When I run the prediction on a new image I got many prediction boxes around each detected object (also with the same accuracy), do you have any Idea how to fix this.
> Knowing that my Dataset is pretty simple (colored Blocks with three different sizes), I thought that reducing the number of Anchor boxes generated during training will help to fix this.
> Any suggestions ?
> Thanks

>hey did you find solution to it?
>I am facing the same problems!!!
