### ISSUE TITLE
AttributeError: 'Lambda' object has no attribute 'is_placeholder'

### ISSUE THREAD

**Issue by sakshijain032** [pierluigiferrari/ssd_keras#339]
AttributeError                            Traceback (most recent call last)
<ipython-input-11-ee9dd6b9a947> in <module>()
     11                 top_k=200,
     12                 nms_max_output_size=400,
---> 13                 return_predictor_sizes=False)
     14 
     15 print("Model built.")

C:\Users\Sakshi\Desktop\opencv-face-recognition\ssd_keras-master\ssd_keras-master\models\keras_ssd300.py in ssd_300(image_size, n_classes, mode, l2_regularization, min_scale, max_scale, scales, aspect_ratios_global, aspect_ratios_per_layer, two_boxes_for_ar1, steps, offsets, clip_boxes, variances, coords, normalize_coords, subtract_mean, divide_by_stddev, swap_channels, confidence_thresh, iou_threshold, top_k, nms_max_output_size, return_predictor_sizes)
    431                                                img_width=img_width,
    432                                                name='decoded_predictions')(predictions)
--> 433         model = Model(inputs=x, outputs=decoded_predictions)
    434     elif mode == 'inference_fast':
    435         decoded_predictions = DecodeDetectionsFast(confidence_thresh=confidence_thresh,

C:\Users\Sakshi\Anaconda3\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature)
---> 87             return func(*args, **kwargs)
     88         return wrapper
     89     return legacy_support

C:\Users\Sakshi\Anaconda3\lib\site-packages\keras\engine\topology.py in __init__(self, inputs, outputs, name)
   1551         for i, layer in enumerate(self.input_layers):
   1552             self.input_names.append(layer.name)
-> 1553             if layer.is_placeholder:
   1554                 self._feed_input_names.append(layer.name)
   1555                 self._feed_inputs.append(layer.input)

AttributeError: 'Lambda' object has no attribute 'is_placeholder'

I got this error from weight_sampling_tutorial.ipynb 
keras version 2.0.0

**Comment by tommy3266** [comment]
@Sakshi Jain Hi, i have the same problem,if you have any solution? Thansk!

**Comment by tommy3266** [comment]
@sakshijain032
hi,i have the same problem,if you have any solution? Thansk!
