### ISSUE TITLE
Transfer Learning tutorial incomplete

### ISSUE THREAD

**Issue by JoaoGranzotti** [pierluigiferrari/ssd_keras#341]
The transfer lerning tutorial ends with the following sentence:
"Seems as if our sub-sampled weights were doing a good job, sweet. Now we can fine-tune this model on our dataset with 8 classes."
*** In my case is 1 class

But how do I do this? I tried to proceed as in the normal training tutorial but I got the following error:

ValueError Traceback (most recent call last)
<ipython-input-13-dfb510b4b86a> in <module> ()
      9 validation_data = val_generator,
     10 validation_steps = 10,
---> 11 initial_epoch = initial_epoch)

6 frames
/usr/local/lib/python3.6/dist-packages/keras/optimizers.py in get_gradients (self, loss, params)
     89 grads = K.gradients (loss, params)
     90 if None in grads:
---> 91 raise ValueError ('An operation has `None` for gradient.'
     92 'Please make sure that all of your ops have a'
     93 'gradient defined (i.e. are differentiable). '

ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

Can someone explain to me how to fine tune after sub-sampling. I still don't have enough experience with keras models.

**Comment by mtchibozo** [comment]
When defining your model, make sure to change 'mode' to 'training' for the fine tuning part. The code in the notebook applies to 'inference' mode.
