### ISSUE TITLE
Stop iteration 

### ISSUE THREAD

**Issue by rd20karim** [pierluigiferrari/ssd_keras#345]
First thanks for the simple implemetation of ssd 
I try to use ssd7 for traininig in this datasets with the same required format 
but in training it's give this error:

Epoch 1/1
/usr/local/lib/python3.6/dist-packages/keras/callbacks/callbacks.py:998: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '

StopIteration                             Traceback (most recent call last)
<ipython-input-83-de121a8b8e33> in <module>()
     18                                                              patience=0,
     19                                                              epsilon=0.001,
---> 20                                                              cooldown=0)],
     21 
     22 
2 frames
/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    **183             batch_index = 0**
    184             while steps_done < steps_per_epoch:
**--> 185                 generator_output = next(output_generator)**
   186 
    **187                 if not hasattr(generator_output, '__len__'):**

**StopIteration:****** 

CODE :
epochs = 1
batch_size_train=1
history = model.fit_generator(generator = train_generator,
                              steps_per_epoch = ceil(n_train_samples/batch_size_train),
                              epochs = epochs,
                              callbacks = [ModelCheckpoint('ssd7_weights_epoch-{epoch:02d}_loss{loss:.4f}.h5',
                                                           monitor='val_loss',
                                                           verbose=1,
                                                           save_best_only=True,
                                                           save_weights_only=True,
                                                           mode='auto',
                                                           period=1),
                                           EarlyStopping(monitor='val_loss',
                                                         min_delta=0.001,
                                                         patience=2),
                                           ReduceLROnPlateau(monitor='val_loss',
                                                             factor=0.5,
                                                             patience=0,
                                                             epsilon=0.001,
                                                             cooldown=0)],
)

**Comment by HarmanBhutani** [comment]
I am facing the similar issue, unable to find the solution yet.

**Comment by jhaggle** [comment]
Could it be because you are out of memory?
