### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'labels'

### ISSUE THREAD

**Issue by leonel11** [pierluigiferrari/ssd_keras#346]
Hello! Thank you very much for the code.
When I tried to train SSD300 detector based on VGG16 I got the error `TypeError: __call__() missing 1 required positional argument: 'labels'`. It happened on the stage of calling `fit_generator` when I wanted to fit the model. How can I solve it? May this problem be caused by possible errors in datasets? The fact is that I tried to fit the model on my own data.
![Безымянный](https://user-images.githubusercontent.com/7613053/81216038-eaa0a980-8fe2-11ea-8b96-bfa6a6059eb2.png)

**Comment by Aavesh** [comment]
Did you find any solution, i also got same error

**Comment by leonel11** [comment]
Unfortunately, not. This problem was given when I tried to fit the model with flag keep_images_without_gt=True. But everything was OK with flag keep_images_without_gt=False

**Comment by Aavesh** [comment]
Yes I also have make the flag False,seems like the codes will not work if there are no bounding box(ground truth) in images
