### ISSUE TITLE
How do I test the code on video data?

### ISSUE THREAD

**Issue by TanmoyDL** [pierluigiferrari/ssd_keras#35]
Hi pierluigiferrai
Great work. Thanks for posting code.
I want to test the trained model on video data. How do I pass the video frames into Batch Generator? 
I am waiting for your valuable suggestions.

**Comment by pierluigiferrari** [comment]
You don't need `BatchGenerator` to do that. Just pass the video frames to the model's `predict()` method.

**Comment by TanmoyDL** [comment]
Thanks for your reply. 
I have tried to test an image which is not belong to the validate dataset. Once, I am able to do that then I can pass the video  frames into the model.predict(). I have tried as follows,
image_load=Image.open('./examples/bike.jpg')
image_load=np.asarray(image_load, dtype="float32")
test = BatchGenerator(filenames=image_load)
test_class = test.generate(batch_size=1,
                     train=False,
                      equalize=False,
                      brightness=False,
                      flip=False,
                      translate=False,
                      scale=False,
                      random_crop=False,
                      crop=False,
                      resize=False,
                      gray=False,
                      limit_boxes=True,
                      include_thresh=0.4,
                      diagnostics=False)                    

X, filenames = next(test_class) 
i = 0
#Make a prediction
y_pred = model.predict(X)

The error is "ValueError: Found input variables with inconsistent numbers of samples: [1, 0]".

**Comment by pierluigiferrari** [comment]
I've already answered an almost identical question in #28.

Note that
1. The `filenames` argument in the `BatchGenerator` constructor expects a list that contains the paths to the images, not the images themselves. So it would have to be `image_load=['./examples/bike.jpg']`.
2. The first point also illustrates why it is unnecessary to use `BatchGenerator` here. You've already loaded the image with `Image.open()`, so why would you need to pass it to the batch generator? All you need to do is pass the loaded image to `model.predict()`. Be aware that `model.predict()` wants its input images inside a list though, even if it is just one image, so if `img` is your image, the call has to be `model.predict([img])`, not `model.predict(img)`.
