### ISSUE TITLE
acc and val_acc are good but there is no prediction

### ISSUE THREAD

**Issue by mouad47** [pierluigiferrari/ssd_keras#352]
hello @pierluigiferrari 
first thank for this work, it's amazing
i'm having problem with the prediction, i don't know where is the bug, loss and val_loss are zeros, but i when i ran the prediction it's show nothing even with test images in the data it's self, 
i'm ussing a defrent dataset, and it's labelled properly, i had some error before that but i fixed them,
do you have any idea? please

**Comment by Ezzysci** [comment]
I have the same problem and it has to do with the confidence threshold. When I put it 0.5, I get no prediction, when I put it as 0.09, I get predictions with too many bounding boxes. What could be the general reason for this? Just as a guiding principle.
