### ISSUE TITLE
Issue with encoding the bouding box for training

### ISSUE THREAD

**Issue by adamuas** [pierluigiferrari/ssd_keras#36]
Hi,

First of all, really great work with the documentation. It was very helpful. 

I have been having issue when working with a custom dataset I made of various image sizes, I keep running into an issue when it comes to encoding the bouding boxes at line: y_encoded[i,assign_indices,:-8] = np.concatenate((class_vector[int(true_box[0])], true_box[1:]), axis=0) 

It raises an IndexError: index 14 is out of bounds for axis 0 with size 14.

Any ideas?

**Comment by adamuas** [comment]
I managed to narrow down the issue to the  full_crop_and_resize function from the ssd_batch_generator.py module and the max_crop_and_resize function as well.

**Comment by pierluigiferrari** [comment]
If you have images of varying size and don't use any of the generator's crop or resize options to  make the size homogenous, the generated batch will end up being empty, which is likely why you're getting the input shape error in the Keras model when you disable the copping options.

I need more information in order to be able to help. What does your ground truth data look like? What's the format? How many classes are there and what are their IDs?

**Comment by adamuas** [comment]
Thanks...I just came across the Caution you you wrote at the end of the generate function before the yield. I am working on a dataset of images which also has a bounding box annotated around some objects of interest using the VGG groups VIA image annotator, so the format is not like the PASCAL. I got to write a script to write out the details of this onto a csv file in this format:

['image_name', 'class_id','xmin', 'xmax', 'ymin', 'ymax']

The class_id was assigned somewhat randomly as I just used an enumerate function to label the images from 1...N (N - number of classes). In my case, I have 14 different classes.

I got to look closely at the y_encoded line of code that was churning out the error, and it seems like its trying to access the class vector, which is size 14.  Is there is a piece of code that is supposed to also include the other 12 included from bouding boxes? i.e. #classes + 12 that you stated in your docs?

Thanks again.

**Comment by adamuas** [comment]
I tried working with the number of classes as 26, it seems like the issue is more related to the number of classes, and gets brought up when you have 14 classes.

**Comment by pierluigiferrari** [comment]
Ah, that explains things.

If you have `N` classes in your dataset, then you must set the `n_classes` argument to `N+1` in the `SSDBoxEncoder` constructor and in the function that builds the model. [`train_ssd7.ipynb`](https://github.com/pierluigiferrari/ssd_keras/blob/master/train_ssd7.ipynb) explains this. So if your dataset has 14 classes, then set `n_classes = 15`.

Note that the background class is not a property of your dataset, it's a property of SSD. SSD predicts a constant (large) number of bounding boxes for every input image, regardless of how many objects are actually present in the image, and it needs to predict a class for each of those bounding boxes. So if a specific bounding box is not predicted to be one of the `N` classes in your dataset (also referred to as the positive classes), then it must be something else. That's what the background class is for (also referred to as the negative class), and the integer used for the background class is always zero.

**Comment by adamuas** [comment]
Awesome!  Its clear now. I tried using `n_classes = 15` and it seems like its working without any issues. 

Really great documentation btw :+1:

**Comment by adamuas** [comment]
Worked :+1:  Thanks again!
