### ISSUE TITLE
different shapes of y_pred in keras_ssd7.py and keras_ssd_loss.py

### ISSUE THREAD

**Issue by gauravk97** [pierluigiferrari/ssd_keras#38]
In keras_ssd_loss.py , in compute_loss,
required shape of y_true and y_pred is `[classes one-hot encoded, 4 ground truth box coordinates, 4 arbitrary entries]`, latter 4 for anchor box coordinates
 
But in model fun in keras_ssd7.py,
Output shape of  y_pred or `predictions` is (batch, n_boxes_total, n_classes + 4 + 8) where in addition to the above, there are 4 more terms for variances.

But in-spite of this contradiction that y_pred(from the model) having different shape than y_true, the model still works. I am confused by this. 
If you could tell me how it works, in order to facilitate the understanding of the project, I would be ever grateful.

**Comment by pierluigiferrari** [comment]
The required shape as stated [here in the documentation](https://github.com/pierluigiferrari/ssd_keras/blob/1c4006d70a51187798e22f26f4a1a9409f8e5e20/keras_ssd_loss.py#L108) in `keras_ssd_loss.py` is `[classes one-hot encoded, 4 ground truth box coordinate offsets, 8 arbitrary entries]`, so there is no contradiction.
