### ISSUE TITLE
How to install ssd_keras?

### ISSUE THREAD

**Issue by saanasum** [pierluigiferrari/ssd_keras#40]
How do I make the ssd_keras package?/module? work? For example `sudo pip install ssd_keras` is not functional. 

Simple cloning or downloading the repository and then using it as proposed in the [Readme](https://github.com/pierluigiferrari/ssd_keras#how-to-use-it) does not work as well when I would like to use import module function as described for example in the [train_ssd300.ipynb](https://github.com/pierluigiferrari/ssd_keras/blob/master/train_ssd300.ipynb). 

```
from keras_ssd300 import ssd_300
from keras_ssd_loss import SSDLoss
from keras_layer_AnchorBoxes import AnchorBoxes
from keras_layer_L2Normalization import L2Normalization
from ssd_box_encode_decode_utils import SSDBoxEncoder, decode_y, decode_y2
from ssd_batch_generator import BatchGenerator
```
The error occurs: `ImportError: No module named keras_ssd300` (same for further modules)

Thanks for helping a beginner and sorry if the question might be stupid but my experience using python is, so far, very limited. 

P.S.: I would like to follow the steps explained [here ](https://github.com/pierluigiferrari/ssd_keras/blob/master/train_ssd7.ipynb)and I would like to use my own model.

**Comment by saanasum** [comment]
A colleague told me:

1. to upgrade to python3. So far, I am using 2.7
2. `git clone https://github.com/pierluigiferrari/ssd_keras.git` and `cd ssd_keras`
3. work in this directory (then it should work)

**Comment by BhanuJain1207** [comment]
I am also getting the same error, i am using google colab can you please explain this step by step.
