### ISSUE TITLE
can't find val_labels.csv

### ISSUE THREAD

**Issue by mengdong824** [pierluigiferrari/ssd_keras#42]
when I train the ssd7 model, I download the consolidated and resized dataset you used , I can't find val_labels.csv.

**Comment by pierluigiferrari** [comment]
Yeah, there is no `val_labels.csv`, there is only a `labels.csv` and you have to make the training and validation split yourself. I should probably provide a split since a few people got confused by this, maybe I'll do that soon.

**Comment by mengdong824** [comment]
thanks, I will try to split it
