### ISSUE TITLE
local variable 'intersection' referenced before assignment

### ISSUE THREAD

**Issue by AhmadZakaria** [pierluigiferrari/ssd_keras#43]
Hello, 

When running `ssd300_training.ipynb`, I get the error:`local variable 'intersection' referenced before assignment`. This is caused by the `if` condition in line 66 in `ssd_box_encode_decode_utils.py` which doesn't handle the third (and default) case: `centroids`. 

Thanks

**Comment by pierluigiferrari** [comment]
Thanks a lot for pointing this out!

Fixed now.

**Comment by AhmadZakaria** [comment]
Thanks
