### ISSUE TITLE
csv Format 

### ISSUE THREAD

**Issue by mwindowshz** [pierluigiferrari/ssd_keras#47]
Hi
Thanks for your great work
I am trying to understand, how to use it,
it would have been useful to have a sample of some image and there corresponding csv file with labels, so can reproduce the format.

I have tried the following format
image_name,classID,xmin,ymin,xmax,ymax
xmin,ymin,xmax,ymax - are the in pixels position's on  the image
Checked them with drawing on image and they are correct.

> air1.jpg, 1, 352, 211, 445, 300
> air2.jpg, 1, 408, 248, 489, 334
> air3.jpg, 1, 339, 194, 460, 296
> air4.jpg, 1, 192, 295, 359, 408
> air4.jpg, 1, 311, 177, 443, 262
> air4.jpg, 1, 312, 430, 438, 509
> air4.jpg, 1, 445, 492, 617, 547
> air4.jpg, 1, 446, 290, 606, 391
> air4.jpg, 1, 457, 59, 601, 171
> air4.jpg, 1, 572, 405, 698, 478
> air4.jpg, 1, 578, 176, 704, 254
> air4.jpg, 1, 670, 281, 818, 386
> air5.jpg, 1, 295, 219, 444, 301
> air6.jpg, 1, 50, 57, 734, 321
> air6.jpg, 1, 54, 862, 1082, 1217
> air6.jpg, 1, 70, 1333, 809, 1622
> air6.jpg, 1, 72, 1688, 951, 1946
> air6.jpg, 1, 92, 465, 951, 783
> air6.jpg, 1, 871, 92, 1697, 330
> air6.jpg, 1, 895, 1272, 1796, 1593
> air6.jpg, 1, 980, 1636, 1933, 2012
> air6.jpg, 1, 1028, 439, 1760, 685
> air6.jpg, 1, 1169, 743, 1750, 1271
> air6.jpg, 1, 1809, 867, 2659, 1188
> air6.jpg, 1, 1823, 491, 2728, 818
> air6.jpg, 1, 1838, 46, 2601, 445
> air6.jpg, 1, 1839, 1286, 2731, 1561
> air6.jpg, 1, 1966, 1633, 2696, 1925
> bird1.jpg, 2, 591, 210, 789, 366
> bird2.jpg, 2, 907, 309, 1213, 520
> bird2.jpg, 2, 1270, 572, 1724, 715
> bird3.jpg, 2, 856, 695, 1168, 838
> bird3.jpg, 2, 873, 224, 1080, 387
> bird3.jpg, 2, 924, 454, 1080, 562
> bird4.jpg, 2, 1452, 1008, 2628, 1594
>
Used your parse_csv() function in ssd_batch_generator.py

for testing I created val and train with the same image list
then continued for training using the ssd_300 training Jupiter notebook 

> 1: Instantiate to `BatchGenerator` objects: One for training, one for validation.
> 
> train_dataset = BatchGenerator(box_output_format=['class_id', 'xmin', 'ymin', 'xmax', 'ymax'])
> val_dataset = BatchGenerator(box_output_format=['class_id', 'xmin', 'ymin', 'xmax', 'ymax'])

> 
> train_dataset.parse_csv(images_path = images_path,
>                                           labels_path = labesl_path,
>                                           input_format=['image_name', 'class_id','xmin', 'xmax', 'ymin', 'ymax'],
>                                           include_classes = 'all',
>                                           random_sample = False,
>                                           ret = True)
> val_dataset.parse_csv(images_path = images_path,
>                                           labels_path = labesl_path,
>                                           input_format=['image_name', 'class_id','xmin', 'xmax', 'ymin', 'ymax'],
>                                           include_classes = 'all',
>                                           random_sample = False,
>                                           ret = True)

**but learning fails**

> Epoch 1/10
> Epoch 00000: val_loss improved from inf to 210993.18750, saving model to ssd300_weights_epoch-00_loss-28.2251_val_loss-210993.1875.h5
> 1/1 [==============================] - 73s - loss: 28.2251 - val_loss: 210993.1875
> Epoch 2/10
> Epoch 00001: val_loss did not improve
> 1/1 [==============================] - 68s - loss: 238422.5000 - val_loss: 134127960.0000
> Epoch 3/10
> Epoch 00002: val_loss did not improve
> 1/1 [==============================] - 77s - loss: 176149040.0000 - val_loss: 4924609024.0000
> Epoch 4/10
> Epoch 00003: val_loss did not improve
> 1/1 [==============================] - 74s - loss: 2190408704.0000 - val_loss: 213619638272.0000

Can you please help me understand where is the fault?
did I set the labels format correct in the csv file?
did I miss something else?

**Comment by pierluigiferrari** [comment]
According to your label examples above, your input format for the parser is set incorrectly. You're setting it to

input_format=['image_name', 'class_id', 'xmin', 'xmax', 'ymin', 'ymax']

when it should be

input_format=['image_name', 'class_id', 'xmin', 'ymin', 'xmax', 'ymax']

But that's probably not the reason for the exploding loss. Did you change any other parameters in the notebook? It'd be easiest if I could take a look at your notebook.

**Comment by mwindowshz** [comment]
Hi 
Thanks
I changed the input format but as you assumed, it did not help.
Then I tried changing batch size, because my data-set is very small, so I set it to 5
now it seems like it is starting to work.
The new problem is that the training does not complete the number of ephoc's that I have set

> 

> Epoch 3/70
> 1/2 [==============>...............] - ETA: 50s - loss: 22575830.0000Epoch 00003: val_loss improved from 164947.45486 to 109449.64497, saving model to ssd300_weights_epoch-03_loss-14560252.6667_val_loss-109449.6450.h5
> 2/2 [==============================] - 108s 54s/step - loss: 13892287.8889 - val_loss: 109449.6450
> Epoch 4/70
> 1/2 [==============>...............] - ETA: 47s - loss: 138616.1562Epoch 00004: val_loss improved from 109449.64497 to 104.74940, saving model to ssd300_weights_epoch-04_loss-77501.8083_val_loss-104.7494.h5
> 2/2 [==============================] - 121s 60s/step - loss: 72408.9460 - val_loss: 104.7494
> Epoch 5/70
> 1/2 [==============>...............] - ETA: 41s - loss: 100.7861Epoch 00005: val_loss improved from 104.74940 to 15.58130, saving model to ssd300_weights_epoch-05_loss-63.8355_val_loss-15.5813.h5
> 2/2 [==============================] - 96s 48s/step - loss: 60.7563 - val_loss: 15.5813

> Epoch 12/70
> 1/2 [==============>...............] - ETA: 32s - loss: 8.6975Epoch 00012: val_loss improved from 8.57205 to 7.91139, saving model to ssd300_weights_epoch-12_loss-8.6270_val_loss-7.9114.h5
> 2/2 [==============================] - 79s 40s/step - loss: 8.6211 - val_loss: 7.9114
> Epoch 13/70
> 1/2 [==============>...............] - ETA: 33s - loss: 9.9627Epoch 00013: val_loss improved from 7.91139 to 7.49004, saving model to ssd300_weights_epoch-13_loss-9.1180_val_loss-7.4900.h5
> 2/2 [==============================] - 80s 40s/step - loss: 9.0476 - val_loss: 7.4900
> Epoch 14/70
> 1/2 [==============>...............] - ETA: 33s - loss: 9.2483Epoch 00014: val_loss improved from 7.49004 to 7.16202, saving model to ssd300_weights_epoch-14_loss-8.4601_val_loss-7.1620.h5
> 2/2 [==============================] - 80s 40s/step - loss: 8.3945 - val_loss: 7.1620
> Epoch 15/70
> 1/2 [==============>...............] - ETA: 32s - loss: 6.9160Epoch 00015: val_loss improved from 7.16202 to 6.82837, saving model to ssd300_weights_epoch-15_loss-6.6018_val_loss-6.8284.h5
> 2/2 [==============================] - 78s 39s/step - loss: 6.5756 - val_loss: 6.8284
> Epoch 16/70
> 1/2 [==============>...............] - ETA: 32s - loss: 7.6039Epoch 00016: val_loss improved from 6.82837 to 6.36522, saving model to ssd300_weights_epoch-16_loss-7.0709_val_loss-6.3652.h5
> 2/2 [==============================] - 76s 38s/step - loss: 7.0265 - val_loss: 6.3652
> Epoch 17/70
> 1/2 [==============>...............] - ETA: 31s - loss: 6.1941Epoch 00017: val_loss did not improve
> 2/2 [==============================] - 76s 38s/step - loss: 6.2313 - val_loss: 6.5592
> Epoch 18/70
> 1/2 [==============>...............] - ETA: 31s - loss: 6.9346Epoch 00018: val_loss improved from 6.36522 to 6.09256, saving model to ssd300_weights_epoch-18_loss-6.4488_val_loss-6.0926.h5
> 2/2 [==============================] - 76s 38s/step - loss: 6.4083 - val_loss: 6.0926
> Epoch 19/70
> 1/2 [==============>...............] - ETA: 32s - loss: 5.7371Epoch 00019: val_loss did not improve
> 2/2 [==============================] - 77s 38s/step - loss: 6.1198 - val_loss: 6.3816
> Epoch 20/70
> 1/2 [==============>...............] - ETA: 32s - loss: 5.8425Epoch 00020: val_loss did not improve
> 2/2 [==============================] - 78s 39s/step - loss: 6.4159 - val_loss: 6.3717
> 
> Model saved under learning/ssd300.h5
> 
> Weights also saved separately under learning/ssd300_weights.h5

**It stops and saves the model and weights - I don't understand why.**


By the way how do you generate the labes for images? what app do you use to draw the boxes and set classes?

I have been working with YOLO, and used YOLO_MARK form https://github.com/AlexeyAB/Yolo_mark
now I am converting the format to SSD format.

Thanks again
M.

**Comment by mwindowshz** [comment]
the notebook:
[ssd300_training.zip](https://github.com/pierluigiferrari/ssd_keras/files/1629732/ssd300_training.zip)
the images:
[ssd.zip](https://github.com/pierluigiferrari/ssd_keras/files/1629735/ssd.zip)

**Comment by pierluigiferrari** [comment]
There are probably many tools for annotating images for object detection, but the one I'm using is `labelImg`: https://github.com/tzutalin/labelImg

Yes, the training is stopping because of the `EarlyStopping` callback. You have to change the settings of the callbacks to suit your needs. You could increase the `patience` or even remove the callback entirely. The important thing to understand here is: Since the training performs stochastic gradient descent (with some fancy modifications) on mini-batches, the resulting gradients will not point in the direction of the actual steepest rate of descent over the whole dataset. The gradient will decrease the loss on average, but any individual training step does not necessarily change the weights into the right direction. In some training steps, the weights can actually be changed for the worse. If there are many training steps in an epoch though, the loss usually decreases over the epoch as long as the model hasn't converged yet. If there are only very few training steps in an epoch though, as in your example, then the probability increases that a given epoch might not improve the loss. Your epochs only consist of two training steps, that's very little. Either increase the number of steps in an epoch, or increase the patience in the `EarlyStopping` callback, or remove the callback altogether.

**Comment by mwindowshz** [comment]
Hi
I have tried training ssd 300 using pascal voc images, and another set of my images combinded

the training fails. the loss stoppes improving
what should I do?
is there any preperation needed to be done before training that I needed to take care of?
Do I need to compute prior boxes in some way?
Do I need to change the learning rate?

here are my results

> C:\Anaconda3\python.exe Train300.py
> Epoch 1/20000
> 2018-01-16 17:22:07.663379: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\pool_allocator.cc:247] PoolAllocator: After 5822 get requests, put_count=5800 evicted_count=1000 eviction_rate=0.172414 and unsatisfied allocation rate=0.192717
> 2018-01-16 17:22:07.663885: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
> Epoch 00001: val_loss improved from inf to 4.59718, saving model to ssd300_weights_epoch-01_loss-4.0849_val_loss-4.5972.h5
>  - 510s - loss: 4.0855 - val_loss: 4.5972
> Epoch 2/20000
> Epoch 00002: val_loss improved from 4.59718 to 3.73795, saving model to ssd300_weights_epoch-02_loss-3.8432_val_loss-3.7379.h5
>  - 496s - loss: 3.8421 - val_loss: 3.7379
> Epoch 3/20000
> Epoch 00003: val_loss improved from 3.73795 to 3.72773, saving model to ssd300_weights_epoch-03_loss-3.5999_val_loss-3.7277.h5
>  - 495s - loss: 3.5991 - val_loss: 3.7277
> Epoch 4/20000
> Epoch 00004: val_loss improved from 3.72773 to 3.21041, saving model to ssd300_weights_epoch-04_loss-3.4295_val_loss-3.2104.h5
>  - 495s - loss: 3.4275 - val_loss: 3.2104
> Epoch 5/20000
> Epoch 00005: val_loss did not improve
>  - 495s - loss: 3.2768 - val_loss: 3.7647
> Epoch 6/20000
> Epoch 00006: val_loss did not improve
>  - 495s - loss: 3.1555 - val_loss: 3.4284
> Epoch 7/20000
> Epoch 00007: val_loss improved from 3.21041 to 2.91274, saving model to ssd300_weights_epoch-07_loss-3.0289_val_loss-2.9127.h5
>  - 496s - loss: 3.0299 - val_loss: 2.9127
> Epoch 8/20000
> Epoch 00008: val_loss improved from 2.91274 to 2.87517, saving model to Assd300_weights_epoch-08_loss-2.9183_val_loss-2.8752.h5
>  - 495s - loss: 2.9190 - val_loss: 2.8752
> Epoch 9/20000
> Epoch 00009: val_loss improved from 2.87517 to 2.84980, saving model to ssd300_weights_epoch-09_loss-2.8234_val_loss-2.8498.h5
>  - 494s - loss: 2.8224 - val_loss: 2.8498
> Epoch 10/20000
> Epoch 00010: val_loss did not improve
>  - 494s - loss: 2.7386 - val_loss: 2.9425
> Epoch 11/20000
> Epoch 00011: val_loss improved from 2.84980 to 2.81891, saving model to ssd300_weights_epoch-11_loss-2.6524_val_loss-2.8189.h5
>  - 496s - loss: 2.6531 - val_loss: 2.8189
> Epoch 12/20000
> Epoch 00012: val_loss improved from 2.81891 to 2.51415, saving model to ssd300_weights_epoch-12_loss-2.5794_val_loss-2.5141.h5
>  - 495s - loss: 2.5780 - val_loss: 2.5141
> Epoch 13/20000
> Epoch 00013: val_loss did not improve
>  - 494s - loss: 2.5007 - val_loss: 2.6986
> Epoch 14/20000
> Epoch 00014: val_loss did not improve
>  - 494s - loss: 2.4322 - val_loss: 2.6762
> Epoch 15/20000
> Epoch 00015: val_loss did not improve
>  - 495s - loss: 2.3674 - val_loss: 2.7229
> Epoch 16/20000
> Epoch 00016: val_loss improved from 2.51415 to 2.42342, saving model to ssd300_weights_epoch-16_loss-2.3188_val_loss-2.4234.h5
>  - 495s - loss: 2.3198 - val_loss: 2.4234
> Epoch 17/20000
> 2018-01-16 19:40:38.950311: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\pool_allocator.cc:247] PoolAllocator: After 333497 get requests, put_count=333497 evicted_count=1000 eviction_rate=0.00299853 and unsatisfied allocation rate=0.00306749
> 2018-01-16 19:40:38.950706: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\pool_allocator.cc:259] Raising pool_size_limit_ from 256 to 281
> Epoch 00017: val_loss did not improve
>  - 495s - loss: 2.2632 - val_loss: 2.9161
> Epoch 18/20000
> Epoch 00018: val_loss improved from 2.42342 to 2.34554, saving model to ssd300_weights_epoch-18_loss-2.2214_val_loss-2.3455.h5
>  - 497s - loss: 2.2214 - val_loss: 2.3455
> Epoch 19/20000
> Epoch 00019: val_loss did not improve
>  - 510s - loss: 2.1510 - val_loss: 2.3570
> Epoch 20/20000
> Epoch 00020: val_loss improved from 2.34554 to 2.19517, saving model to ssd300_weights_epoch-20_loss-2.1135_val_loss-2.1952.h5
>  - 508s - loss: 2.1125 - val_loss: 2.1952
> Epoch 21/20000
> Epoch 00021: val_loss did not improve
>  - 499s - loss: 2.0749 - val_loss: 2.6225
> Epoch 22/20000
> Epoch 00022: val_loss improved from 2.19517 to 2.09532, saving model to ssd300_weights_epoch-22_loss-2.0382_val_loss-2.0953.h5
>  - 498s - loss: 2.0383 - val_loss: 2.0953
> Epoch 23/20000
> Epoch 00023: val_loss did not improve
>  - 498s - loss: 1.9865 - val_loss: 2.4727
> Epoch 24/20000
> Epoch 00024: val_loss did not improve
>  - 498s - loss: 1.9585 - val_loss: 2.1755
> Epoch 25/20000
> Epoch 00025: val_loss did not improve
>  - 500s - loss: 1.9084 - val_loss: 2.1985
> Epoch 26/20000
> Epoch 00026: val_loss did not improve
>  - 498s - loss: 1.8715 - val_loss: 2.4088
> Epoch 27/20000
> Epoch 00027: val_loss did not improve
>  - 498s - loss: 1.8409 - val_loss: 2.2624
> Epoch 28/20000
> Epoch 00028: val_loss improved from 2.09532 to 2.00638, saving model to ssd300_weights_epoch-28_loss-1.8000_val_loss-2.0064.h5
>  - 498s - loss: 1.7990 - val_loss: 2.0064
> Epoch 29/20000
> Epoch 00029: val_loss improved from 2.00638 to 1.59240, saving model to ssd300_weights_epoch-29_loss-1.7782_val_loss-1.5924.h5
>  - 498s - loss: 1.7779 - val_loss: 1.5924
> Epoch 30/20000
> Epoch 00030: val_loss did not improve
>  - 498s - loss: 1.7546 - val_loss: 2.0504
> Epoch 31/20000
> Epoch 00031: val_loss did not improve
>  - 498s - loss: 1.7198 - val_loss: 2.1060
> Epoch 32/20000
> Epoch 00032: val_loss did not improve
>  - 498s - loss: 1.7027 - val_loss: 1.8137
> Epoch 33/20000
> Epoch 00033: val_loss did not improve
>  - 499s - loss: 1.6733 - val_loss: 1.8809
> Epoch 34/20000
> Epoch 00034: val_loss did not improve
>  - 498s - loss: 1.6398 - val_loss: 2.1183
> Epoch 35/20000
> Epoch 00035: val_loss did not improve
>  - 498s - loss: 1.6196 - val_loss: 2.2848
> Epoch 36/20000
> Epoch 00036: val_loss did not improve
>  - 498s - loss: 1.5979 - val_loss: 2.2087
> Epoch 37/20000
> Epoch 00037: val_loss did not improve
>  - 498s - loss: 1.5765 - val_loss: 1.7122
> Epoch 38/20000
> Epoch 00038: val_loss did not improve
>  - 498s - loss: 1.5499 - val_loss: 2.0477
> Epoch 39/20000
> Epoch 00039: val_loss did not improve
>  - 498s - loss: 1.5303 - val_loss: 2.0982
> Epoch 40/20000
> Epoch 00040: val_loss did not improve
>  - 498s - loss: 1.5182 - val_loss: 2.1393
> Epoch 41/20000
> Epoch 00041: val_loss did not improve
>  - 498s - loss: 1.4879 - val_loss: 1.6461
> Epoch 42/20000
> Epoch 00042: val_loss did not improve
>  - 499s - loss: 1.4708 - val_loss: 2.2446
> Epoch 43/20000
> Epoch 00043: val_loss did not improve
>  - 498s - loss: 1.4539 - val_loss: 1.8741
> Epoch 44/20000
> Epoch 00044: val_loss did not improve
>  - 498s - loss: 1.4304 - val_loss: 1.8430
> Epoch 45/20000
> Epoch 00045: val_loss did not improve
>  - 498s - loss: 1.4089 - val_loss: 2.0356
> Epoch 46/20000
> Epoch 00046: val_loss did not improve
>  - 499s - loss: 1.4155 - val_loss: 2.0829
> Epoch 47/20000
> Epoch 00047: val_loss did not improve
>  - 498s - loss: 1.3992 - val_loss: 1.9730
> Epoch 48/20000
> Epoch 00048: val_loss did not improve
>  - 498s - loss: 1.3719 - val_loss: 2.4108
> Epoch 49/20000
> Epoch 00049: val_loss improved from 1.59240 to 1.58877, saving model to ssd300_weights_epoch-49_loss-1.3484_val_loss-1.5888.h5
>  - 498s - loss: 1.3487 - val_loss: 1.5888
> Epoch 50/20000
> Epoch 00050: val_loss did not improve
>  - 498s - loss: 1.3451 - val_loss: 2.0808
> Epoch 51/20000
> Epoch 00051: val_loss did not improve
>  - 498s - loss: 1.3354 - val_loss: 1.8737
> Epoch 52/20000
> Epoch 00052: val_loss did not improve
>  - 498s - loss: 1.3220 - val_loss: 1.8804
> Epoch 53/20000
> Epoch 00053: val_loss did not improve
>  - 498s - loss: 1.3013 - val_loss: 1.9048
> Epoch 54/20000
> Epoch 00054: val_loss did not improve
>  - 498s - loss: 1.2939 - val_loss: 1.8548
> Epoch 55/20000
> Epoch 00055: val_loss did not improve
>  - 498s - loss: 1.2703 - val_loss: 1.9844
> Epoch 56/20000
> Epoch 00056: val_loss did not improve
>  - 498s - loss: 1.2755 - val_loss: 2.1013
> Epoch 57/20000
> Epoch 00057: val_loss did not improve
>  - 498s - loss: 1.2600 - val_loss: 1.8148
> Epoch 58/20000
> Epoch 00058: val_loss did not improve
>  - 498s - loss: 1.2390 - val_loss: 2.0262
> Epoch 59/20000
> Epoch 00059: val_loss did not improve
>  - 498s - loss: 1.2359 - val_loss: 1.9004
> Epoch 60/20000
> 2018-01-17 01:37:25.104088: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\pool_allocator.cc:247] PoolAllocator: After 3894292 get requests, put_count=3894292 evicted_count=7000 eviction_rate=0.0017975 and unsatisfied allocation rate=0.00180598
> Epoch 00060: val_loss did not improve
>  - 499s - loss: 1.2097 - val_loss: 2.1573
> Epoch 61/20000
> Epoch 00061: val_loss did not improve
>  - 498s - loss: 1.2003 - val_loss: 2.1810
> Epoch 62/20000
> Epoch 00062: val_loss did not improve
>  - 498s - loss: 1.2076 - val_loss: 2.1903
> Epoch 63/20000
> Epoch 00063: val_loss did not improve
>  - 498s - loss: 1.1894 - val_loss: 1.7872
> Epoch 64/20000
> Epoch 00064: val_loss did not improve
>  - 498s - loss: 1.1817 - val_loss: 1.9804
> Epoch 65/20000
> Epoch 00065: val_loss did not improve
>  - 498s - loss: 1.1685 - val_loss: 1.9278
> Epoch 66/20000
> Epoch 00066: val_loss did not improve
>  - 499s - loss: 1.1635 - val_loss: 2.0360
> Epoch 67/20000
> Epoch 00067: val_loss did not improve
>  - 498s - loss: 1.1503 - val_loss: 1.7000
> Epoch 68/20000
> Epoch 00068: val_loss did not improve
>  - 498s - loss: 1.1491 - val_loss: 2.0532
> Epoch 69/20000
> Epoch 00069: val_loss did not improve
>  - 498s - loss: 1.1379 - val_loss: 1.8849
> 


Model saved under learning/ssd300.h5

here training stopped.

The loss seems to improve, but val_loss not.

Also question, how many epocs do you need for training PASCAL VOC, you mentioned that you need 120000 , but in the weights file it is written as iterations is this the same?

Thanks in advance
M.

**Comment by pierluigiferrari** [comment]
> Also question, how many epocs do you need for training PASCAL VOC, you mentioned that you need 120000 , but in the weights file it is written as iterations is this the same?

Iterations and epochs are not the same. One iteration (or training step) is one forward and backward pass during training, resulting in one weight update. One epoch consists of a series of training steps, usually the number of training steps needed to iterate once over the entire dataset at the used batch size. The notebook says that the original models were trained on Pascal VOC for 120,000 training steps (or more, depending on the model), not 120,000 epochs.

> what should I do?
> is there any preperation needed to be done before training that I needed to take care of?
> Do I need to compute prior boxes in some way?
> Do I need to change the learning rate?

It looks like the model is overfitting. The training loss keeps decreasing, but the validation loss stagnates. 

Pull the latest master. I realized that I forgot to add the default L2 regularization that the original Caffe models use and added that a couple of commits ago. This might help prevent the overfitting.

Also, try using data augmentation a lot more aggressively. The data augmentation settings that are preset in the training notebook are not meant to be the ideal settings. You will have to experiment with data augmentation yourself. For example, try out the random the random scaling and translation options, which will result in much more variety in the dataset in combination with the preset random padding and random cropping options.
