### ISSUE TITLE
Train on COCO-Text

### ISSUE THREAD

**Issue by Omnipresent** [pierluigiferrari/ssd_keras#48]
This is not an issue but a question. First of all thank you very much for creating and maintaining this. 

I am looking to re-train SSD on [COCO-text](https://vision.cornell.edu/se3/coco-text-2/) and I am new to deep learning. 

Should I start with `ssd7_training.ipynb` and then see if I get decent results on the test set? If so, then train on `ssd300_training.ipynb`? Are there any pointers you'd recommend before I begin the training?

**Comment by pierluigiferrari** [comment]
I'd start out with training an SSD300 or SSD512 directly. The capacity of SSD7 is probably too limited for COCO-text and the training procedure is the same regardless of the model you use. Plus for SSD300 and SSD512 you get trained models as a starting point, which is going to save you a lot of time. The only thing is that depending on the number of classes you might have to either initialize the predictor layers freshly or subsample their weights (if the kernel shapes of the last layers don't match). As for "pointers" I'd recommend before you begin the training, you'd have to be more specific as to what you mean by that.
