### ISSUE TITLE
Error: AttributeError: 'numpy.ndarray' object has no attribute 'pop'

### ISSUE THREAD

**Issue by saghiralfasly** [pierluigiferrari/ssd_keras#51]
whenever i run training i get this error after a few steps   

File "/home/saghir/keras/ssd_keras/ssd_batch_generator.py", line 1177, in generate
    batch_inverse_coord_transform.pop(j)
AttributeError: 'numpy.ndarray' object has no attribute 'pop'
 
anyone know how to solve this

**Comment by pierluigiferrari** [comment]
Thank you for pointing this out! Should be fixed now, give it a try.
