### ISSUE TITLE
Loss stagnates

### ISSUE THREAD

**Issue by Okra0o0** [pierluigiferrari/ssd_keras#55]
![2018-01-20_085957](https://user-images.githubusercontent.com/34560837/35273574-f7ed7e20-0073-11e8-8c10-9da626ce08ad.png)
I used all the data(VOC 07+12), and reduced learning rate. But the loss has been around 2.~, can't be reduced. Is there anything else that can help reduce loss?

**Comment by pierluigiferrari** [comment]
1. Use data augmentation a lot more aggressively. The data augmentation settings that are preset in the training notebook are not meant to be the ideal settings. You will have to experiment with data augmentation yourself. For example, try out the random scaling and translation options, which will result in much more variety in the dataset in combination with the preset random padding and random cropping options.
2. Keep training for longer. If the loss stagnates for two or three epochs that doesn't yet mean that it doesn't make sense to continue training. It can happen that the loss doesn't really move much for a while and then starts decreasing again.

**Comment by wastacat** [comment]
Do you plan to add focal loss to boost SSD performance?
https://arxiv.org/abs/1708.02002

**Comment by pierluigiferrari** [comment]
Probably at some point, but I can't say when.

**Comment by mwindowshz** [comment]
> Use data augmentation a lot more aggressively. The data augmentation settings that are preset in the training notebook are not meant to be the ideal settings. You will have to experiment with data augmentation yourself. For example, try out the random scaling and translation options, which will result in much more variety in the dataset in combination with the preset random padding and random cropping options.

Hi can you please explain more on dat augmentation parameters, or point the direction where are they.

I found these : 
```

subtract_mean = [104, 117, 123] # The per-channel mean of the images in the dataset
swap_channels = True # The color channel order in the original SSD is BGR
n_classes = 20 # Number of positive classes, e.g. 20 for Pascal VOC, 80 for MS COCO
scales = [0.1, 0.2, 0.37, 0.54, 0.71, 0.88, 1.05] # The anchor box scaling factors used in the original SSD300 for the Pascal VOC datasets, the factors for the MS COCO dataset are smaller, namely [0.07, 0.15, 0.33, 0.51, 0.69, 0.87, 1.05]



aspect_ratios = [[1.0, 2.0, 0.5],
                 [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                 [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                 [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                 [1.0, 2.0, 0.5],
                 [1.0, 2.0, 0.5]] # The anchor box aspect ratios used in the original SSD300; the order matters
two_boxes_for_ar1 = True
steps = [8, 16, 32, 64, 100, 300] # The space between two adjacent anchor box center points for each predictor layer.
offsets = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5] # The offsets of the first anchor box center points from the top and left borders of the image as a fraction of the step size for each predictor layer.
limit_boxes = False # Whether or not you want to limit the anchor boxes to lie entirely within the image boundaries
variances = [0.1, 0.1, 0.2, 0.2] # The variances by which the encoded target coordinates are scaled as in the original implementation
coords = 'centroids' # Whether the box coordinates to be used as targets for the model should be in the 'centroids', 'corners', or 'minmax' format, see documentation
normalize_coords = True
```
for example scales
how long can this list be?
what is the minimum what is the maximum values? can it be 
does  0.1 mean resizing the image to 10% of original size?
would 2.0 mean resizing the image to 200% of original size?

What other parameters should I try chaning?
anchor box aspect ratios ? what are they? I have all my boxes, width and height values, should I use this information to set the aspect ratios values? do you have some explanation about the values?


Also where do I set the Translation values? 

I also tried training the VOC data set with provided ssd300_training notebook, and still did no success

Thanks for your great work.
M.

**Comment by pierluigiferrari** [comment]
What you posted above are hyper parameters for the model configuration. These are **not** data augmentation parameters. Model hyper parameters determine the configuration of the **model**, data augmentation parameters affect the **input data**. You shouldn't change any of the model configuration parameters unless your data warrants it. For

"Data augmentation" means to artificially increase the size and diversity of a dataset by randomly applying certain transformations to the images.

> Also where do I set the Translation values?

Data augmentation is performed by `BatchGenerator.generate()` during the training (i.e. ad-hoc), so in the arguments of the `generate()` method of the batch generator is where you find the data augmentation options. Read the documentation of that method to understand.

> for example scales
> how long can this list be?
> what is the minimum what is the maximum values? can it be

Once again, you have to read the documentation of the functions and classes. I'm always happy to help, but I'm not happy to answer questions that are already being answered in the provided documentation. I didn't write all this documentation for nothing 🙂. For example, the `AnchorBoxes` layer class and the `SSDBoxEncoder` class both explain in their documentation what the scales list is and how many elements it must have, so that information can be found in at least two places in the documentation.

> does 0.1 mean resizing the image to 10% of original size?
> would 2.0 mean resizing the image to 200% of original size?

The scaling factors refer to the sizes of the anchor boxes (called default boxes or priors in the paper) in the individual predictor layers, they are not about resizing the images.

> anchor box aspect ratios ? what are they?

Once again, read the documentation. The aspect ratios determine the aspect ratios of the anchor boxes.

> I also tried training the VOC data set with provided ssd300_training notebook, and still did no success

Really? You pretty much just have to execute the cells in `ssd300_training.ipynb`

**Comment by mwindowshz** [comment]
Hi
Using ssd300_training.ipynb with original PASCAL VOC 2007 and 2012 did not work for me.

I would try again.
But if I understand, from what you worte, the setting in this notebook should work.
M.

**Comment by mwindowshz** [comment]
Hi Tried retraining using ssd300_trianing notebook
used VOC dataset original files.
took a clean version from github
did not change parameters, except number of ephocs 150 and patience to 40 so the learning would stop after 2 non non improving ephocs

And learning did not work. after a while learning does not improve what  am I doing wrong?

> Epoch 1/150
> 517/518 [============================>.] - ETA: 0s - loss: 9.2551Epoch 00001: val_loss improved from inf to 7.38003, saving model to ssd300_weights_epoch-01_loss-9.2552_val_loss-7.3800.h5
> 518/518 [==============================] - 561s 1s/step - loss: 9.2517 - val_loss: 7.3800
> Epoch 2/150
> 517/518 [============================>.] - ETA: 0s - loss: 7.1821Epoch 00002: val_loss improved from 7.38003 to 6.61886, saving model to ssd300_weights_epoch-02_loss-7.1819_val_loss-6.6189.h5
> 518/518 [==============================] - 540s 1s/step - loss: 7.1810 - val_loss: 6.6189
> Epoch 3/150
> 517/518 [============================>.] - ETA: 0s - loss: 6.5939Epoch 00003: val_loss improved from 6.61886 to 6.20374, saving model to ssd300_weights_epoch-03_loss-6.5935_val_loss-6.2037.h5
> 518/518 [==============================] - 536s 1s/step - loss: 6.5920 - val_loss: 6.2037
> Epoch 4/150
> 517/518 [============================>.] - ETA: 0s - loss: 6.1053Epoch 00004: val_loss improved from 6.20374 to 5.81777, saving model to ssd300_weights_epoch-04_loss-6.1053_val_loss-5.8178.h5
> 518/518 [==============================] - 536s 1s/step - loss: 6.1044 - val_loss: 5.8178
> Epoch 5/150
> 517/518 [============================>.] - ETA: 0s - loss: 5.7652Epoch 00005: val_loss improved from 5.81777 to 5.50223, saving model to ssd300_weights_epoch-05_loss-5.7657_val_loss-5.5022.h5
> 518/518 [==============================] - 537s 1s/step - loss: 5.7676 - val_loss: 5.5022
> Epoch 6/150
> 517/518 [============================>.] - ETA: 0s - loss: 5.5151Epoch 00006: val_loss improved from 5.50223 to 5.28438, saving model to ssd300_weights_epoch-06_loss-5.5146_val_loss-5.2844.h5
> 518/518 [==============================] - 537s 1s/step - loss: 5.5136 - val_loss: 5.2844
> Epoch 7/150
> 517/518 [============================>.] - ETA: 0s - loss: 5.3181Epoch 00007: val_loss improved from 5.28438 to 5.12390, saving model to ssd300_weights_epoch-07_loss-5.3177_val_loss-5.1239.h5
> 518/518 [==============================] - 536s 1s/step - loss: 5.3167 - val_loss: 5.1239
> Epoch 8/150
> 517/518 [============================>.] - ETA: 0s - loss: 5.1561Epoch 00008: val_loss improved from 5.12390 to 4.85768, saving model to ssd300_weights_epoch-08_loss-5.1563_val_loss-4.8577.h5
> 518/518 [==============================] - 537s 1s/step - loss: 5.1574 - val_loss: 4.8577
> Epoch 9/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.9835Epoch 00009: val_loss improved from 4.85768 to 4.77178, saving model to ssd300_weights_epoch-09_loss-4.9832_val_loss-4.7718.h5
> 518/518 [==============================] - 537s 1s/step - loss: 4.9820 - val_loss: 4.7718
> Epoch 10/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.8413Epoch 00010: val_loss improved from 4.77178 to 4.63327, saving model to ssd300_weights_epoch-10_loss-4.8414_val_loss-4.6333.h5
> 518/518 [==============================] - 537s 1s/step - loss: 4.8421 - val_loss: 4.6333
> Epoch 11/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.7263Epoch 00011: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 4.7265 - val_loss: 4.6733
> Epoch 12/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.6304Epoch 00012: val_loss did not improve
> 518/518 [==============================] - 536s 1s/step - loss: 4.6301 - val_loss: 4.7257
> Epoch 13/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.5222Epoch 00013: val_loss improved from 4.63327 to 4.45253, saving model to ssd300_weights_epoch-13_loss-4.5230_val_loss-4.4525.h5
> 518/518 [==============================] - 538s 1s/step - loss: 4.5256 - val_loss: 4.4525
> Epoch 14/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.4320Epoch 00014: val_loss improved from 4.45253 to 4.35563, saving model to ssd300_weights_epoch-14_loss-4.4320_val_loss-4.3556.h5
> 518/518 [==============================] - 537s 1s/step - loss: 4.4322 - val_loss: 4.3556
> Epoch 15/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.3420Epoch 00015: val_loss improved from 4.35563 to 4.26051, saving model to ssd300_weights_epoch-15_loss-4.3422_val_loss-4.2605.h5
> 518/518 [==============================] - 537s 1s/step - loss: 4.3422 - val_loss: 4.2605
> Epoch 16/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.2631Epoch 00016: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 4.2644 - val_loss: 4.4017
> Epoch 17/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.1909Epoch 00017: val_loss improved from 4.26051 to 4.20818, saving model to ssd300_weights_epoch-17_loss-4.1913_val_loss-4.2082.h5
> 518/518 [==============================] - 537s 1s/step - loss: 4.1924 - val_loss: 4.2082
> Epoch 18/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.1311Epoch 00018: val_loss improved from 4.20818 to 4.16889, saving model to ssd300_weights_epoch-18_loss-4.1306_val_loss-4.1689.h5
> 518/518 [==============================] - 537s 1s/step - loss: 4.1290 - val_loss: 4.1689
> Epoch 19/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.0664Epoch 00019: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 4.0653 - val_loss: 4.1913
> Epoch 20/150
> 517/518 [============================>.] - ETA: 0s - loss: 4.0176Epoch 00020: val_loss improved from 4.16889 to 4.12147, saving model to ssd300_weights_epoch-20_loss-4.0178_val_loss-4.1215.h5
> 518/518 [==============================] - 537s 1s/step - loss: 4.0173 - val_loss: 4.1215
> Epoch 21/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.9604Epoch 00021: val_loss improved from 4.12147 to 4.10324, saving model to ssd300_weights_epoch-21_loss-3.9606_val_loss-4.1032.h5
> 518/518 [==============================] - 537s 1s/step - loss: 3.9607 - val_loss: 4.1032
> Epoch 22/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.9101Epoch 00022: val_loss improved from 4.10324 to 4.08165, saving model to ssd300_weights_epoch-22_loss-3.9101_val_loss-4.0817.h5
> 518/518 [==============================] - 537s 1s/step - loss: 3.9102 - val_loss: 4.0817
> Epoch 23/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.8535Epoch 00023: val_loss improved from 4.08165 to 3.98108, saving model to ssd300_weights_epoch-23_loss-3.8538_val_loss-3.9811.h5
> 518/518 [==============================] - 539s 1s/step - loss: 3.8544 - val_loss: 3.9811
> Epoch 24/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.8165Epoch 00024: val_loss improved from 3.98108 to 3.92090, saving model to ssd300_weights_epoch-24_loss-3.8162_val_loss-3.9209.h5
> 518/518 [==============================] - 541s 1s/step - loss: 3.8153 - val_loss: 3.9209
> Epoch 25/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.7662Epoch 00025: val_loss improved from 3.92090 to 3.92020, saving model to ssd300_weights_epoch-25_loss-3.7662_val_loss-3.9202.h5
> 518/518 [==============================] - 537s 1s/step - loss: 3.7673 - val_loss: 3.9202
> Epoch 26/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.7300Epoch 00026: val_loss improved from 3.92020 to 3.88720, saving model to ssd300_weights_epoch-26_loss-3.7299_val_loss-3.8872.h5
> 518/518 [==============================] - 538s 1s/step - loss: 3.7294 - val_loss: 3.8872
> Epoch 27/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.6836Epoch 00027: val_loss improved from 3.88720 to 3.86859, saving model to ssd300_weights_epoch-27_loss-3.6842_val_loss-3.8686.h5
> 518/518 [==============================] - 538s 1s/step - loss: 3.6856 - val_loss: 3.8686
> Epoch 28/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.6627Epoch 00028: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 3.6629 - val_loss: 4.0433
> Epoch 29/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.6190Epoch 00029: val_loss improved from 3.86859 to 3.83858, saving model to ssd300_weights_epoch-29_loss-3.6185_val_loss-3.8386.h5
> 518/518 [==============================] - 538s 1s/step - loss: 3.6173 - val_loss: 3.8386
> Epoch 30/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.5812Epoch 00030: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.5811 - val_loss: 3.8514
> Epoch 31/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.5520Epoch 00031: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.5511 - val_loss: 3.8849
> Epoch 32/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.5195Epoch 00032: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.5191 - val_loss: 3.8624
> Epoch 33/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.4936Epoch 00033: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.4942 - val_loss: 3.8447
> Epoch 34/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.4591Epoch 00034: val_loss improved from 3.83858 to 3.76131, saving model to ssd300_weights_epoch-34_loss-3.4590_val_loss-3.7613.h5
> 518/518 [==============================] - 538s 1s/step - loss: 3.4592 - val_loss: 3.7613
> Epoch 35/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.4385Epoch 00035: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 3.4376 - val_loss: 3.7988
> Epoch 36/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.4105Epoch 00036: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 3.4101 - val_loss: 3.8473
> Epoch 37/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.3733Epoch 00037: val_loss did not improve
> 518/518 [==============================] - 539s 1s/step - loss: 3.3710 - val_loss: 3.8375
> Epoch 38/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.3555Epoch 00038: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.3596 - val_loss: 3.7827
> Epoch 39/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.3244Epoch 00039: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.3227 - val_loss: 3.7792
> Epoch 40/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.2972Epoch 00040: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.2985 - val_loss: 3.8175
> Epoch 41/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.2891Epoch 00041: val_loss improved from 3.76131 to 3.75624, saving model to ssd300_weights_epoch-41_loss-3.2882_val_loss-3.7562.h5
> 518/518 [==============================] - 538s 1s/step - loss: 3.2854 - val_loss: 3.7562
> Epoch 42/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.2565Epoch 00042: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.2545 - val_loss: 3.8117
> Epoch 43/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.2332Epoch 00043: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.2345 - val_loss: 3.8813
> Epoch 44/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.2323Epoch 00044: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 3.2323 - val_loss: 3.8162
> Epoch 45/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.1980Epoch 00045: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.1967 - val_loss: 3.7603
> Epoch 46/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.1795Epoch 00046: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 3.1806 - val_loss: 3.7861
> Epoch 47/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.1545Epoch 00047: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.1546 - val_loss: 3.7880
> Epoch 48/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.1415Epoch 00048: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.1402 - val_loss: 3.7805
> Epoch 49/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.1167Epoch 00049: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.1166 - val_loss: 3.8515
> Epoch 50/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.1066Epoch 00050: val_loss improved from 3.75624 to 3.70651, saving model to ssd300_weights_epoch-50_loss-3.1064_val_loss-3.7065.h5
> 518/518 [==============================] - 538s 1s/step - loss: 3.1058 - val_loss: 3.7065
> Epoch 51/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.0975Epoch 00051: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.0974 - val_loss: 3.8633
> Epoch 52/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.0711Epoch 00052: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.0737 - val_loss: 3.8597
> Epoch 53/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.0746Epoch 00053: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 3.0760 - val_loss: 3.7769
> Epoch 54/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.0455Epoch 00054: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.0477 - val_loss: 3.8115
> Epoch 55/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.0279Epoch 00055: val_loss improved from 3.70651 to 3.70080, saving model to ssd300_weights_epoch-55_loss-3.0279_val_loss-3.7008.h5
> 518/518 [==============================] - 538s 1s/step - loss: 3.0278 - val_loss: 3.7008
> Epoch 56/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.0093Epoch 00056: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.0096 - val_loss: 3.7777
> Epoch 57/150
> 517/518 [============================>.] - ETA: 0s - loss: 3.0095Epoch 00057: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 3.0087 - val_loss: 3.7661
> Epoch 58/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.9822Epoch 00058: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 2.9805 - val_loss: 3.8004
> Epoch 59/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.9744Epoch 00059: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 2.9744 - val_loss: 3.8296
> Epoch 60/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.9536Epoch 00060: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 2.9527 - val_loss: 3.8609
> Epoch 61/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.9527Epoch 00061: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 2.9518 - val_loss: 3.7782
> Epoch 62/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.9412Epoch 00062: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 2.9395 - val_loss: 3.7029
> Epoch 63/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.9243Epoch 00063: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 2.9268 - val_loss: 4.0173
> Epoch 64/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.9189Epoch 00064: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 2.9188 - val_loss: 3.8323
> Epoch 65/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.8985Epoch 00065: val_loss did not improve
> 518/518 [==============================] - 537s 1s/step - loss: 2.8983 - val_loss: 3.7940
> Epoch 66/150
> 517/518 [============================>.] - ETA: 0s - loss: 2.8908Epoch 00066: val_loss did not improve
> 518/518 [==============================] - 538s 1s/step - loss: 2.8908 - val_loss: 3.7346


What should the loss values be for this Dataset - Pascal VOC 2007 and 2012? 

What am I doing wrong?

Thanks.

**Comment by pierluigiferrari** [comment]
As I've already said above, my suggestions are to use more data augmentation, etc. I have no suggestions beyond what I proposed above. Closing this for now.

**Comment by eypros** [comment]
@mwindowshz why do you think that you did something wrong?
The training and evaluation loss you get is totally normal as I get it.
Compare with the provided [training summary](https://github.com/pierluigiferrari/ssd_keras/blob/master/training_summaries/ssd300_pascal_07+12_training_summary.md) to check it out. There although not mentioned by number you can see that the evaluation loss is between 4 and 5. Yours is below 4 for instance.

@Okra0o0 this applies to you too. But I am curious on how did you manage to get a val loss below 3 and a training loss just above 2 with just Voc 2007+12 training set, epoch defined with 490 samples (why exactly?) and in just 18 epochs? This should normally outperform the actual Pascal Voc 2007 test SSD300 performance.
