### ISSUE TITLE
ssd7 val_generator only returns one box.

### ISSUE THREAD

**Issue by alexiip** [pierluigiferrari/ssd_keras#58]
```
### Make predictions

# 1: Set the generator

predict_generator = val_dataset.generate(batch_size=1,
                                         shuffle=True,
                                         train=False,
                                         returns={'processed_labels',
                                                  'filenames'},
                                         equalize=False,
                                         brightness=False,
                                         flip=False,
                                         translate=False,
                                         scale=False,
                                         max_crop_and_resize=False,
                                         random_pad_and_resize=False,
                                         random_crop=False,
                                         crop=False,
                                         resize=False,
                                         gray=False,
                                         limit_boxes=True,
                                         include_thresh=0.4)

# 2: Generate samples

X, y_true, filenames = next(predict_generator)

i = 0 # Which batch item to look at

print("Image:", filenames[i])
print()
print("Ground truth boxes:\n")
print(y_true[i])


Image: ../data/udacity_driving_datasets/1478732132850753761.jpg

Ground truth boxes:

[[  1 144 141 162 156]]
```

**Comment by pierluigiferrari** [comment]
I'm unable to reproduce the issue. I've been generating a bunch of batches and the labels always include all ground truth boxes for the respective image. Did you make any changes to the code?

**Comment by alexiip** [comment]
I have not made any changes, here are my params, am I setting something incorrectly?

i```
mg_height = 300 # Height of the input images
img_width = 480 # Width of the input images
img_channels = 3 # Number of color channels of the input images
subtract_mean = 127.5 # Set this to your preference (maybe `None`). The current settings transform the input pixel values to the interval `[-1,1]`.
divide_by_stddev = 127.5 # Set this to your preference (maybe `None`). The current settings transform the input pixel values to the interval `[-1,1]`.
n_classes = 5 # Number of positive classes
scales =  None#[0.08, 0.16, 0.32, 0.64, 0.96] # An explicit list of anchor box scaling factors. If this is passed, it will override `min_scale` and `max_scale`.
aspect_ratios = [0.5, 1.0, 2.0] # The list of aspect ratios for the anchor boxes
two_boxes_for_ar1 = True # Whether or not you want to generate two anchor boxes for aspect ratio 1
steps = None # In case you'd like to set the step sizes for the anchor box grids manually; not recommended
offsets = None # # In case you'd like to set the offsets for the anchor box grids manually; not recommended
limit_boxes = False # Whether or not you want to limit the anchor boxes to lie entirely within the image boundaries
variances = [1.0, 1.0, 1.0, 1.0] # The list of variances by which the encoded target coordinates are scaled
coords = 'centroids' # Whether the box coordinates to be used should be in the 'centroids' or 'minmax' format, see documentation
normalize_coords = False # Whether or not the model is supposed to use relative coordinates that are within [0,1]
```

**Comment by alexiip** [comment]
I have just pulled the latest code and it seems to work. Sorry about that.

**Comment by pierluigiferrari** [comment]
Happy to hear that!

**Comment by heavenao** [comment]
hello，I am also training on datasets of different image sizes, but I can't find the "max_crop_and_resize" parameter in the source code.
