### ISSUE TITLE
Strange error while parsing annotations

### ISSUE THREAD

**Issue by kvinicki** [pierluigiferrari/ssd_keras#60]
Hi
First of all thanks for your great work!
I'm trying to use it on some medical images and while trying to parse annotations i got error: No such file or directory: '/home/kruno/ssd_keras-master/data/reticulocytes/labels/000001.**jpg.xml** . 
So, ok, I renamed all files (inserted **.jpg** before .xml) but then I got ValueError: 'erythrocyte' is not in list. 
I should say that i have only two classes: erythrocyte and reticulocyte.
Here is the notebook: 
[ssd300_training-Copy1.ipynb.zip](https://github.com/pierluigiferrari/ssd_keras/files/1675404/ssd300_training-Copy1.ipynb.zip)
images: 
[data.zip](https://github.com/pierluigiferrari/ssd_keras/files/1675407/data.zip)

Did I miss something?
Thanks again

**Comment by pierluigiferrari** [comment]
You need to pass the `classes` list to `val_dataset.parse_xml()`, too (in your notebook you're only passing it to `train_dataset.parse_xml()`), otherwise the `classes` argument will default to the Pascal VOC list of object categories, which doesn't contain the string 'erythrocyte' 🙂

**Comment by pierluigiferrari** [comment]
I'm happy to hear that, glad I could help!

**Comment by kvinicki** [comment]
I have just one more question.
I have very imbalanced dataset (in images there are naturally much more
erythrocytes than reticulocytes) and so my question is: if in training set
every image has at least one reticulocyte, will the model expect for the
images in the test set to also have at least one reticulocyte and
therefore misclassify some objects (cells)?
In other words, does the SSD only looks at each object in image separately,
or does it also looks at the whole image and therefore makes some rules
about the whole image?

Dana 30. sij 2018. 02:48 poslije podne osoba "Pierluigi Ferrari" <
notifications@github.com> napisala je:

**Comment by pierluigiferrari** [comment]
To answer your latter question, each neuron in any given predictor layer looks only at a certain, constant patch of the input image. For the later predictor layers such a patch might be the whole image, while for the earlier predictor layers such a patch might only be a small fraction of the image. Within whatever patch of the image a certain neuron sees, it uses all of that patch's information to "make a decision" in the sense that of course all pixels in the receptive field of that patch are collectively responsible for that neuron's activation.

As for your other questions: Imbalanced datasets can definitely lead to the classifier predicting the dominant object class with a higher probability. What people often do in practice is try to balance it out a bit by using a bunch of variations of images that contain more objects of the non-dominant object classes.

But if every image contained one reticulocyte, that will not lead to the model predicting a reticulocyte in every image just by principle. If an image contains no patterns that correspond to what a certain layer learned to be a reticulocyte, then the neurons in that layer responsible for classifying reticulocytes won't have strong activations.

**Comment by pierluigiferrari** [comment]
Just FYI there is now a tutorial on how to fine-tune one of the fully trained models on your own dataset: https://github.com/pierluigiferrari/ssd_keras/blob/master/weight_sampling_tutorial.ipynb

Even though your object of interest are very different from any of the classes that the trained models were trained on, this would probably still be the best starting point for your training.

**Comment by kvinicki** [comment]
Thank you for your clear and detailed explanation :) and especially for the tutorial

**Comment by Leon924** [comment]
@pierluigiferrari   Thanks for your detailed work and contribution first !
@kvinicki I think I came across similiar problem with you, but I am trying to train VGG_ILSVRC_16_layers_fc_reduced.h5  using pascalvoc2007 trainval, and then this bug shows up
 No such file or directory:VOC2007/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/Annotations/000001.xml'
I download this datasets from its official website. how can I solve this problem ?
I have search this filepath, it actually doesnt exist. But it is from official website. so confused !

**Comment by kvinicki** [comment]
Hi, i don't have Keras installed right now but I will install it and i'll try to help you. Can you send me the code (jupyter notebook) you used?

**Comment by Leon924** [comment]
@kvinicki  thanks for your kindness, and here is the code I used 
[ssd300_training.zip](https://github.com/pierluigiferrari/ssd_keras/files/2950667/ssd300_training.zip)
I didn't change many details, just for the path of weights and datasets in my pc,  and the error shows up because it really doesn't stored inside file folders. how can I solve this?
