### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '0.69327074'

### ISSUE THREAD

**Issue by gautam1858** [pierluigiferrari/ssd_keras#67]
When the input has floating values i.e the bounding boxes I am getting the following error 
`ValueError: invalid literal for int() with base 10: '0.69327074'`

I changed the line 263 of the ssd_batch_generator.py file to 
` obj.append(float(i[self.input_format.index(item)].strip()))` but in vain

**Comment by pierluigiferrari** [comment]
A few things here:
1. As the documentation of the method in question (`parse_csv()`) clearly states, the bounding box coordinates are expected to be absolute coordinates, not relative coordinates. In particular, they need to be integer values.
2. The transformations in the `generate()` method rely on absolute coordinates, so even if you rewrote `parse_csv()` to work with relative coordinates, you'd still also have to change code in other places to work with relative coordinates.
3. The easiest solution to this is to just convert your labels from relative to absolute bounding box coordinates.

**Comment by gautam1858** [comment]
Ok but my coordinate values are between 0 and 1 so what changes should I make in the parse_csv() ?

**Comment by pierluigiferrari** [comment]
As I said above, you should just change your coordinate values from relative to absolute. Doing that is way easier than changing the batch generator.

If you want to change the code to work with relative coordinates, that's your own adventure. I don't know of the top of my head all places in the code you'd have to change and I don't intend to invest time in it. If I were you I would just write a simple preprocessing function that takes your CSV with relative coordinates and outputs either another CSV with absolute coordinates or a Python list with the labels in the format as the batch generator constructor needs them.

**Comment by gautam1858** [comment]
ok thank you

**Comment by heavenao** [comment]
I have changed the absolute coordinates of the picture. But still report an error，invalid literal for int() with base 10: '628.0'。
