### ISSUE TITLE
How to get parameters for my own custom dataset

### ISSUE THREAD

**Issue by Adnation** [pierluigiferrari/ssd_keras#68]
Hi there,

First of all sorry for creating issue to ask question.

I am trying to train this model on my own dataset and predictions are really bad. What I have done is used SSD300 model and trained with my own images using weight_sampling_tutorial.ipynb tutorial. However there are many parameters specific to COCO dataset so how can I set those parameters for my own dataset?
Also what would be a better choice training pretrained SSD300 or train SSD7 from scratch?

Thank you!!

**Comment by pierluigiferrari** [comment]
Well, I don't know anything about your dataset, so that makes it hard to answer the question.

**Comment by Adnation** [comment]
What information about dataset you need?

**Comment by IntelligentIndia7** [comment]
@pierluigiferrari Hey, I have a dataset with cable wires and floor mats with bounding boxes pretty longer and thin. So how can I modify the scales and aspect ratios? 

Please advise on the same !

Thanks in advance.
