### ISSUE TITLE
improvement to weight_sampling_tutorial.ipynb

### ISSUE THREAD

**Issue by santhoshdc1590** [pierluigiferrari/ssd_keras#70]
I found an article for transferred learning with limited data for entirely new data than what the original pre trained network was actually trained for. 
Hope this can help you refine `weight_sampling_tutorial.ipynb`

 [All-Transfer Learning for Deep Neural Networks and its Application to Sepsis](https://arxiv.org/pdf/1711.04450.pdf)

**Comment by pierluigiferrari** [comment]
Looks good, thanks!
