### ISSUE TITLE
Parameters for my own custom dataset

### ISSUE THREAD

**Issue by ryutenor** [pierluigiferrari/ssd_keras#72]
Hi,

Thanks for providing the codes for me to learn more about SSD.

I would like to try training on my own custom dataset. It consists images of size 1920 x 1080, where I want to detect 2 objects, namely lamp post of size ratio (height:width) 7:1 and stop sign (size ratio 1:1).

I would like to train with the SSD300. However, I have question on setting the aspect ratio. The aspect ratio should be based on the original size (1920x1080) or after the image have been resized to 300x300 for the SSD training?

Thanks in advance

**Comment by pierluigiferrari** [comment]
The aspect ratios should cater to the shapes of your objects after resizing to 300x300, i.e. they should reflect what the network actually gets to see.

Unfortunately, in your case this will make the already extreme aspect ratio of 7:1 even more extreme.

It might be hard to learn the lamp posts effectively. You will probably have to experiment a bit with the anchor box parameters and choose them carefully. In particular:
1. You could try to just have 3:1 as the most extreme aspect ratio and see how that is going. The problem with this will be that no anchor box will ever have an IoU overlap that meets the threshold, so the matching process will always fall back to just matching the one anchor box with the highest IoU overlap for each lamp post. The training might still work, but with only one anchor box matched per lamp post instance, it would probably not be as good as it could be.
2. If you set extreme aspect ratios for the anchor boxes, like 6:1 or 7:1, make sure that the resulting anchor boxes are still within the receptive field of the respective predictor layer. You might have to adjust the scaling factors, too.
3. I would recommend to use `SSDBoxEncoder.generate_anchor_boxes_for_layer()` with the diagnostic output option to get a clear picture of what the result of a given set of anchor box parameters is. It will tell you how far the individual boxes are spaced apart from each other, how large they are, etc. I sometimes just draw the grid of anchor boxes for a specific aspect ratio onto a test image just to see how well the anchor boxes cover the image. And, once again, make sure the resulting anchor boxes are within the receptive field of their respective predictor layer.

**Comment by ryutenor** [comment]
Thanks for the reply.

How about the scale? How can i calculate the scales needed?

**Comment by pierluigiferrari** [comment]
The code [here](https://github.com/pierluigiferrari/ssd_keras/blob/9d9241e276359f7110199bc8ab636307dd83cd7e/ssd_box_utils/ssd_box_encode_decode_utils.py#L724-L740) (or the formulae in the paper) tell you how the scaling factors determine the sizes of the resulting anchor boxes. The anchor boxes for your model should meet two requirements as well as possible:
1. You want to teach a given filter in a given predictor layer to detect objects of a certain size and aspect ratio. The better the sizes of the anchor boxes cover the different sizes of the objects in your dataset, the better will the results of the matching process be and thus the better will that given filter learn to detect the boxes it should. This means you want to pick scaling factors that result in anchor boxes that cover the sizes of the objects in your dataset well.
2. You want to pick scaling factors such that the resulting anchor boxes lie within the receptive fields of the respective predictor layers. It is still possible that objects that are larger than the layer's receptive field are matched to a given anchor box, but it reduces the likelihood. Disclaimer: This is just a hypothesis, I haven't tested how well the model would learn if the individual layers had to detect objects that go beyond their receptive fields. Intuitively it should be harder for a layer to classify, and, more importantly, predict the borders of, an object that it cannot fully see.

That being said, it's worth noting that the anchor box sizes and aspect ratios don't imply that the respective layers will learn to detect objects of those shapes and sizes, they merely specify that those shapes and sizes are what the layers are supposed to learn.
