### ISSUE TITLE
the last prediction layer question

### ISSUE THREAD

**Issue by GengboLiu** [pierluigiferrari/ssd_keras#76]
I tried to run the keras_ssd300.py. I got a last concatenate lay like this:

predictions (Concatenate)       (None, 8732, 21)

In the commend, the author of this code mentioned that is *(batch, n_boxes_total, n_classes + 4 + 8)*

But I can not get it why 300*300 image can get 8732 total boxes. (8732 = 2 x 2 x 37 x 59). Could you please help me to understand the reason of this phenomena.

**Comment by GengboLiu** [comment]
And does the training labels of each image also provide 8732 x 21 labels?

**Comment by pierluigiferrari** [comment]
8732 is the sum of all boxes of all prediction layers that SSD300 predicts. It is the sum of `feature_map_height * feature_map_width * num_boxes` over all predictor layers, i.e.:

8732 = 38*38*4 + 19*19*6 + 10*10*6 + 5*5*6 + 3*3*4 + 1*1*4

**Comment by GengboLiu** [comment]
Thank you so much!!! @pierluigiferrari

**Comment by GengboLiu** [comment]
Great repo!
