### ISSUE TITLE
Error: aspect_ratios_per_layer is None or len(aspect_ratios_per_layer) = len(predictor_size)

### ISSUE THREAD

**Issue by humayun** [pierluigiferrari/ssd_keras#80]
Dear Pierluigiferrari,

I am trying to fine tune SSD512 model with weights VGG_ILSVRC_16_layers_fc_reduced.h5 but it gave me this error:

`ValueError: It must be either aspect_ratios_per_layer is None or len(aspect_ratios_per_layer) == len(predictor_sizes), but len(aspect_ratios_per_layer) == 7 and len(predictor_sizes) == 6`

I think these weights are for SSD300 model only.

Later, I tried to chage the weight file with VGG_coco_SSD_512x512_iter_360000.h5 but not working. This is only for VGG model not the FC layers.
 How can I get weights for SSD512 model which are trained either ImageNet or COCO dataset?

Thank you.

Best,
-Humayun

**Comment by pierluigiferrari** [comment]
This error has nothing to do with the weights. SSD512 has one predictor layer more than SSD300. Presumably you didn't include that additional predictor layer in the `predictor_sizes` list that is being created in the code cell where the `SSDBoxEncoder` constructor is called. It must be:

```
predictor_sizes = [model.get_layer('conv4_3_norm_mbox_conf').output_shape[1:3],
                               model.get_layer('fc7_mbox_conf').output_shape[1:3],
                               model.get_layer('conv6_2_mbox_conf').output_shape[1:3],
                               model.get_layer('conv7_2_mbox_conf').output_shape[1:3],
                               model.get_layer('conv8_2_mbox_conf').output_shape[1:3],
                               model.get_layer('conv9_2_mbox_conf').output_shape[1:3],
                               model.get_layer('conv10_2_mbox_conf').output_shape[1:3]]
```
Note the additional `conv10_2_mbox_conf` layer.

**Comment by humayun** [comment]
Thanks. Now it is working.

Best,
-Humayun
