### ISSUE TITLE
Input Image Size

### ISSUE THREAD

**Issue by zeynali** [pierluigiferrari/ssd_keras#81]
Hi,
I have some question about input size image training : 
 is it possible to change input image size to any image size ? my images's dataset are 1242*375 , when i use ssd300/512 , in my opinion , that's possible to distortion aspect ratio , right ?

**Comment by pierluigiferrari** [comment]
SSD300 and SSD512 will work as expected only with 300x300 and 512x512 input, respectively. Since the original trained models were trained on images with distorted aspect ratios, they are robust to such distortions to a certain extent.
