### ISSUE TITLE
change aspect ratios and scales

### ISSUE THREAD

**Issue by zeynali** [pierluigiferrari/ssd_keras#82]
Hi , 
i want to change the default aspect ration to = [1.0 , 1.0/4.0 , 1.0/3.0 , 0.5 , 3.0/4.0 ] but i don't know how to adjust this values to per layers , this the defaults values we have : 

> aspect_ratios_per_layer=[[1.0, 2.0, 0.5],
>                                      [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
>                                      [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
>                                      [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
>                                      [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
>                                      [1.0, 2.0, 0.5],
> [1.0, 2.0, 0.5]],

Now  i want to replace my values with these default values , How do I add these to the layers?

**Comment by pierluigiferrari** [comment]
You just have to read the documentation of any of the functions that have `aspect_ratios_per_layer` as a parameter. `aspect_ratios_per_layer` is a nested list that contains one list of aspect ratios for each predictor layer. I think that's pretty clear. You just set this list however you want.

**Comment by zeynali** [comment]
@pierluigiferrari , Hi , you don't get my problem , i want to have this values for aspect ratios = [1 , 0.25 , 0.33 , 0.5 , 0.75] , so which of below ones can be better ? why ? 
```
aspect_ratios_per_layer=
[[1.0, 0.25, 0.5],
[1.0, 0.25, 0.5, 0.75, 0.33],
[1.0, 0.25, 0.5, 0.75, 0.33],
[1.0, 0.25, 0.5, 0.75, 0.33],
[1.0, 0.25, 0.5, 0.75 , 0.33],
[1.0, 0.25, 0.5],
[1.0, 0.25, 0.5]],

aspect_ratios_per_layer=
[[1.0, 0.75, 0.5],
[1.0, 0.75, 0.5, 0.25, 0.33],
[1.0, 0.75, 0.5, 0.25, 0.33],
[1.0, 0.75, 0.5, 0.25, 0.33],
[1.0, 0.75, 0.5, 0.25 , 0.33],
[1.0, 0.75, 0.5],
[1.0, 0.75, 0.5]],

aspect_ratios_per_layer=
[[1.0, 0.33, 0.5],
[1.0, 0.33, 0.5, 0.25, 0.75],
[1.0, 0.33, 0.5, 0.25,0.75],
[1.0, 0.33, 0.5, 0.25, 0.75],
[1.0, 0.75, 0.5, 0.25 ,0.75],
[1.0, 0.75, 0.5],
```

**Comment by pierluigiferrari** [comment]
I answered your question above: You can set any number of aspect ratios for any predictor layer, i.e. you can set the `aspect_ratios_per_layer` list however you like. If you want the aspect ratios for all predictor layers to be `[1 , 0.25 , 0.33 , 0.5 , 0.75]`, then you set

```
aspect_ratios_per_layer=
[[1.0, 0.33, 0.5, 0.25, 0.75],
 [1.0, 0.33, 0.5, 0.25, 0.75],
 [1.0, 0.33, 0.5, 0.25, 0.75],
 [1.0, 0.33, 0.5, 0.25, 0.75],
 [1.0, 0.75, 0.5, 0.25 ,0.75],
 [1.0, 0.33, 0.5, 0.25, 0.75]]
```
Or, easier in this case, you set
```
aspect_ratios_global = [1.0, 0.33, 0.5, 0.25, 0.75]
aspect_ratios_per_layer = None # Important, otherwise `aspect_ratios_per_layer` will override `aspect_ratios_global`.
```
If you want the aspect ratios to be `[1 , 0.25 , 0.33 , 0.5 , 0.75]` for only the middle two predictor layers and `[1 , 0.5 , 0.75]` for all other predictor layers, you set
```
aspect_ratios_per_layer=
[[1 , 0.5 , 0.75],
 [1 , 0.5 , 0.75],
 [1.0, 0.33, 0.5, 0.25, 0.75],
 [1.0, 0.33, 0.5, 0.25, 0.75],
 [1 , 0.5 , 0.75],
 [1 , 0.5 , 0.75]]
```
and so on. You simply set this list to whatever aspect ratios you want for the respective predictor layers, as I've already written above.

Now, **why** you would want to set certain aspect ratios for certain layers is a different question. Here are the possible reasons why the aspect ratios of the original SSD300 and SSD512 are chosen the way they are:
1. More aspect ratios == more complexity == slower model. For example, out of the 8732 boxes that SSD300 predicts, 5776 are predicted by the first predictor layer alone. That's more than half of all the boxes. And that's at only 3 aspect ratios for the first predictor layer. If the first predictor layer predicted boxes for 5 different aspect ratios, that would make 8664 boxes just for the first predictor layer. Possibly, the authors of the original SSD chose to only use the 3 most important aspect ratios for the first predictor layer to make the model faster.
2. Not all aspect ratios may be necessary for all object sizes. The authors of the original SSD decided to leave out the more extreme aspect ratios (3:1 and 1:3) for the largest boxes. The rationale behind that might be that if objects make up a very large area of a given image, then their aspect ratios can only be very extreme if the aspect ratio of the whole image is very extreme, which isn't the case for SSD300 and SSD512.

As for you second question, if you download one of the original Caffe models, e.g. the SSD300 Pascal VOC "07+12" model, and open the included `ssd_pascal.py`, you can find how they calculated the scaling factors:

```
min_dim = 300
# conv4_3 ==> 38 x 38
# fc7 ==> 19 x 19
# conv6_2 ==> 10 x 10
# conv7_2 ==> 5 x 5
# conv8_2 ==> 3 x 3
# conv9_2 ==> 1 x 1
mbox_source_layers = ['conv4_3', 'fc7', 'conv6_2', 'conv7_2', 'conv8_2', 'conv9_2']
# in percent %
min_ratio = 20
max_ratio = 90
step = int(math.floor((max_ratio - min_ratio) / (len(mbox_source_layers) - 2)))
min_sizes = []
max_sizes = []
for ratio in xrange(min_ratio, max_ratio + 1, step):
  min_sizes.append(min_dim * ratio / 100.)
  max_sizes.append(min_dim * (ratio + step) / 100.)
min_sizes = [min_dim * 10 / 100.] + min_sizes
max_sizes = [min_dim * 20 / 100.] + max_sizes
```

**Comment by zeynali** [comment]
Thanks for quickly answers. 
you said this values of scales_voc and coco are calculated ssd_pascal.py and ssd_coco.py , right ? if so , for custom dataset How to calculate ?

**Comment by rkaushik97** [comment]
How to calculate the scaling factors and aspect ratios for each prediction layers for a custom dataset?

**Comment by pierluigiferrari** [comment]
@kaushikraghu Search through old issues, this topic has come up a few times in the past and various tipps, hints, and general principles are scattered across different old issues.

**Comment by isalirezag** [comment]
@pierluigiferrari can yo please explain what is the meaning of 
min_ratio and max_ratio?

**Comment by isalirezag** [comment]
@pierluigiferrari can yo please explain what is the meaning of 
min_ratio and max_ratio?

**Comment by pierluigiferrari** [comment]
@isalirezag there are no parameters named `min_ratio` or `max_ratio`.

**Comment by isalirezag** [comment]
@pierluigiferrari 
so what are:
```
min_ratio = 20
max_ratio = 90
```

**Comment by pierluigiferrari** [comment]
@isalirezag please link to the exact line of a file in this repository

**Comment by isalirezag** [comment]
@pierluigiferrari 
In the answer that you provided above you mentioned:

> As for you second question, if you download one of the original Caffe models, e.g. the SSD300 Pascal VOC "07+12" model, and open the included ssd_pascal.py, you can find how they calculated the scaling factors:....

and there is 

```
min_ratio = 20
max_ratio = 90
```

that are in cahrge of how to define the 

`min_sizes` and `max_sizes`

In general, I am having trouble to understanding how to define the `min_sizes` and `max_sizes`, i mean I dont know how I can change them based on my objects sizes...
