### ISSUE TITLE
Error deep in fit_generator when using SSD7_training notebook with TF v1.6.0

### ISSUE THREAD

**Issue by fancypantsifier** [pierluigiferrari/ssd_keras#84]
First, thanks for an incredibly detailed and well-documented code base and tutorials. This is an amazing piece of work.

I'm trying to retrain the SSD7 model on COCO data, by very slightly modifying the ssd7_training notebook. I'm getting the following error stack when I get to the `history = model.fit_generator()` step.

I'm using the notebook as is, except that I'm setting up the train/val datasets from json instead of csv:
```python
train_dataset.parse_json(images_dirs=['{}/train2014'.format(coco_data_path)], 
                         annotations_filenames=['{}/annotations/instances_train2014.json'.format(coco_data_path)], 
                         ground_truth_available=True,
                         include_classes='all')

val_dataset.parse_json(images_dirs=['{}/val2014'.format(coco_data_path)], 
                       annotations_filenames=['{}/annotations/instances_val2014.json'.format(coco_data_path)], 
                       ground_truth_available=True,
                       include_classes='all')
```

I'm using TensorFlow 1.6.0. Could this be a versioning issue, as it seems deep within TensorFlow (i.e., down in a call to `tf.clip_by_value` and `tf.sqrt`?  

```python
WARNING:tensorflow:Variable *= will be deprecated. Use variable.assign_mul if you want assignment to the variable value or 'x = x * y' if you want a new python Tensor object.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-22d018627654> in <module>()
     21                                                              cooldown=0)],
     22                               validation_data = val_generator,
---> 23                               validation_steps = ceil(num_val_samples/batch_size))
     24 
     25 # TODO: Set the filename (without the .h5 file extension!) under which to save the model and weights.

~/Code/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/Code/tensorflow/lib/python3.6/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2078 
   2079         do_validation = bool(validation_data)
-> 2080         self._make_train_function()
   2081         if do_validation:
   2082             self._make_test_function()

~/Code/tensorflow/lib/python3.6/site-packages/keras/engine/training.py in _make_train_function(self)
    988                     training_updates = self.optimizer.get_updates(
    989                         params=self._collected_trainable_weights,
--> 990                         loss=self.total_loss)
    991                 updates = self.updates + training_updates + self.metrics_updates
    992                 # Gets loss and metrics. Updates weights at each call.

~/Code/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/Code/tensorflow/lib/python3.6/site-packages/keras/optimizers.py in get_updates(self, loss, params)
    452 
    453         t = K.cast(self.iterations, K.floatx()) + 1
--> 454         lr_t = lr * (K.sqrt(1. - K.pow(self.beta_2, t)) /
    455                      (1. - K.pow(self.beta_1, t)))
    456 

~/Code/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in sqrt(x)
   1459     zero = _to_tensor(0., x.dtype.base_dtype)
   1460     inf = _to_tensor(np.inf, x.dtype.base_dtype)
-> 1461     x = tf.clip_by_value(x, zero, inf)
   1462     return tf.sqrt(x)
   1463 

~/Code/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py in clip_by_value(t, clip_value_min, clip_value_max, name)
     58   """
     59   with ops.name_scope(name, "clip_by_value",
---> 60                       [t, clip_value_min, clip_value_max]) as name:
     61     t = ops.convert_to_tensor(t, name="t")
     62 

~/Code/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in __enter__(self)
   5614       if self._values is None:
   5615         self._values = []
-> 5616       g = _get_graph_from_inputs(self._values)
   5617       self._g_manager = g.as_default()
   5618       self._g_manager.__enter__()

~/Code/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _get_graph_from_inputs(op_input_list, graph)
   5282         graph = graph_element.graph
   5283       elif original_graph_element is not None:
-> 5284         _assert_same_graph(original_graph_element, graph_element)
   5285       elif graph_element.graph is not graph:
   5286         raise ValueError("%s is not from the passed-in graph." % graph_element)

~/Code/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _assert_same_graph(original_item, item)
   5218   if original_item.graph is not item.graph:
   5219     raise ValueError("%s must be from the same graph as %s." % (item,
-> 5220                                                                 original_item))
   5221 
   5222 

ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32) must be from the same graph as Tensor("sub:0", shape=(), dtype=float32).
```

**Comment by pierluigiferrari** [comment]
Hm, very strange. I haven't been able to reproduce this error in TensorFlow 1.4.1. I have a hunch though. Could you try to compile the model with a different optimizer?  `keras.optimizers.SGD` or something. Anything but Adam. Let me know what happens.

**Comment by andrew-anki** [comment]
Thanks for the quick response!

You are correct: switching to SGD from Adam avoids that error.  I'm curious if you identified that so quickly because you know of changes to the Adam optimizer since v1.4.1 or what. Is your suggested workaround to "just use SGD" or downgrade my TF install to v1.4.1?

btw, I get a new error, but I'm assuming this is simply because I've done no work to verify that the COCO annotations are as expected for the SSD box encoder you created. I have not investigated this at all yet, but if you have any experience getting this working with COCO and can share any insight, that would certainly be great! 

```python
~/Code/ssd_keras/ssd_box_utils/ssd_box_encode_decode_utils.py in encode_y(self, ground_truth_labels, diagnostics)
    939                 assign_indices = np.nonzero(available_and_thresh_met)[0] # Get the indices of the left-over anchor boxes to which we want to assign this ground truth box
    940                 if len(assign_indices) > 0: # If we have any matches
--> 941                     y_encoded[i,assign_indices,:-8] = np.concatenate((class_vector[int(true_box[0])], true_box[1:]), axis=0) # Write the ground truth box coordinates and class to all assigned anchor box positions. Remember that the last four elements of `y_encoded` are just dummy entries.
    942                     available_boxes[assign_indices] = 0 # Make the assigned anchor boxes unavailable for the next ground truth box
    943                 else: # If we don't have any matches

IndexError: index 28 is out of bounds for axis 0 with size 6
```

**Comment by pierluigiferrari** [comment]
Thanks for trying it out, I'm glad that my suspicion was confirmed. TensorFlow 1.6.0 introduced a new internal Optimizer API that affects particularly how `AdamOptimizer` must be used, which means that this is a Keras issue. What Keras version are you on?

As for your second error: You forgot to set the number of classes to 80 at the top of the notebook. Also, since the image size is non-constant in MS COCO, you will also need to use one of the options in `BatchGenerator.generate()` to make sure all images end up with the right size. You could either simply `resize` them or use `max_crop_and_resize` or `random_pad_and_resize` (or both).

**Comment by fancypantsifier** [comment]
Ah, ok, that makes sense. Thanks for the explanation. 

I'm on Keras version 2.1.5.

I had switched to using `resize` but had not updated the number of classes. Thanks! Training is now running. I'm guessing I'll need to update the annotations, which are encoded at original image resolution, to the resized resolution for matching to ground truth at train time though...


> Thanks for the quick response!
>
>You are correct: switching to SGD from Adam avoids that error.  I'm curious if you identified that so quickly because you know of changes to the Adam optimizer since v1.4.1 or what. Is your suggested workaround to "just use SGD" or downgrade my TF install to v1.4.1?
>
>btw, I get a new error, but I'm assuming this is simply because I've done no work to verify that the COCO annotations are as expected for the SSD box encoder you created. I have not investigated this at all yet, but if you have any experience getting this working with COCO and can share any insight, that would certainly be great! 
>
```python
~/Code/ssd_keras/ssd_box_utils/ssd_box_encode_decode_utils.py in encode_y(self, ground_truth_labels, diagnostics)
    939                 assign_indices = np.nonzero(available_and_thresh_met)[0] # Get the indices of the left-over anchor boxes to which we want to assign this ground truth box
    940                 if len(assign_indices) > 0: # If we have any matches
--> 941                     y_encoded[i,assign_indices,:-8] = np.concatenate((class_vector[int(true_box[0])], true_box[1:]), axis=0) # Write the ground truth box coordinates and class to all assigned anchor box positions. Remember that the last four elements of `y_encoded` are just dummy entries.
    942                     available_boxes[assign_indices] = 0 # Make the assigned anchor boxes unavailable for the next ground truth box
    943                 else: # If we don't have any matches

IndexError: index 28 is out of bounds for axis 0 with size 6
```

**Comment by pierluigiferrari** [comment]
All image transformations that `BatchGenerator` provides adjusts the box annotations accordingly, so there's nothing you need to do. Otherwise the generator would be pretty useless ;)

If you don't mind I'll open an issue in the Keras repository an post your stack trace there, unless you want to do that yourself.

**Comment by fancypantsifier** [comment]
Oh! That's great to hear. 

Yeah, I'm happy for you to open the Keras issue. You obviously know a lot more about it, so will be more useful in getting it resolved. 

Would you recommend just using SGD until it's fixed, or downgrading TF to 1.4.1 for now?

**Comment by pierluigiferrari** [comment]
Alright, I'll open an issue then.

I'd recommend going with SGD with 0.9 momentum. It's already in my previous answer above in a bit more detail.

**Comment by fancypantsifier** [comment]
Ah, sorry. I somehow didn't see the second paragraph. You totally already answered. Thanks again!

**Comment by pierluigiferrari** [comment]
No worries and you're welcome!

**Comment by rodrigoruiz** [comment]
@pierluigiferrari where's the link for the new issue?
And has it been solved already?
I'm still having the same problem with Adam.

**Comment by Flock1** [comment]
Hi. Something weird is happening with me. I am using keras to train a mode. First, it's not changing weights for some reason, so there is no change in loss or accuracy. 
Second, when I use some other model, I get the warning as shown above:
```
WARNING:tensorflow:Variable *= will be deprecated. Use variable.assign_mul if you want assignment to the variable value or 'x = x * y' if you want a new python Tensor object.
```
and then, my kernel crashes, it uses up all of my memory. 
Can someone help me with what's happening?
