### ISSUE TITLE
Training on Dataset with different image sizes

### ISSUE THREAD

**Issue by rodsnjr** [pierluigiferrari/ssd_keras#89]
Hello.

I'm trying to use your implementation to train on my own dataset.
I have multiple images with multiple sizes, annotated with the Pascal VOC format.

The thing is I keep getting the following error:

> .../ssd_batch_generator.py", line 1182, in generate batch_X = np.array(batch_X) ValueError: could not broadcast input array from shape (224,224,4) into shape (224,224)

I'm using the example of SSD 7 to get started, with this generator configuration:

```python
train_generator = train_dataset.generate(batch_size=batch_size,
                                         shuffle=True,
                                         train=True,
                                         ssd_box_encoder=ssd_box_encoder,
                                         convert_to_3_channels=True,
                                         equalize=False,
                                         brightness=(0.5, 2, 0.5), # Randomly change brightness between 0.5 and 2 with probability 0.5
                                         flip=0.5, # Randomly flip horizontally with probability 0.5
                                         translate=((5, 70), (3, 50), 0.5), # Randomly translate by 5-70 pixels horizontally and 3-50 pixels vertically with probability 0.5
                                         scale=(0.7, 1.4, 0.5), # Randomly scale between 0.7 and 1.4 with probability 0.5
                                         max_crop_and_resize=False,
                                         random_pad_and_resize=False,
                                         random_crop=False,
                                         crop=False,
                                         resize=(224, 224),
                                         gray=False,
                                         limit_boxes=True,
                                         include_thresh=0.4)

val_generator = val_dataset.generate(batch_size=batch_size,
                                     shuffle=True,
                                     train=True,
                                     ssd_box_encoder=ssd_box_encoder,
                                     convert_to_3_channels=True,
                                     equalize=False,
                                     brightness=False,
                                     flip=False,
                                     translate=False,
                                     scale=False,
                                     max_crop_and_resize=False,
                                     random_pad_and_resize=False,
                                     random_crop=False,
                                     crop=False,
                                     resize=(224, 224),
                                     gray=False,
                                     limit_boxes=True,
                                     include_thresh=0.4)

```

Is there any configuration I should do to avoid this error, my guess it's possibly because there are multiple sized images on my dataset.

Any help is appreciated thanks! And also thanks for this great repository.

**Comment by pierluigiferrari** [comment]
Since you're resizing the images, the varying sizes are not an issue here. In your case the number of channels is the issue. Are you using 4-channel images? Do all your images have the same number of channels?

**Comment by pierluigiferrari** [comment]
Glad to hear it. Yeah the generator cannot yet deal with 4-channel images, I guess I'll fix that soon. What data format were your images in? What's the fourth channel? Alpha? Depth?

**Comment by rodsnjr** [comment]
My data was collected from multiple sources: multiple pictures from multiple users, including myself, google, etc ...

The 4th channel is possibly Alpha for this case.
My small snippet works like a charm to convert them, but it's slow, possibly not good to use in the Generator.

But if anyone has trouble using with multiple sources images like me, might be a good idea to use it to clean/normalize their dataset.

**Comment by pierluigiferrari** [comment]
Yeah, if an image has a fourth channel, that channel will be a special channel (alpha, depth, etc.), so it isn't possible to artificially create that fourth channel for a 3-channel image in a meaningful way. The best solution for a dataset in which some images have four channels is therefore to just throw away the fourth channel, which is a relatively cheap operation in Numpy compared to what your function above does.

Thanks for the feedback, I'll close this issue.
