### ISSUE TITLE
use Histogram Equalization on HSV instead of RGB

### ISSUE THREAD

**Issue by lababidi** [pierluigiferrari/ssd_keras#9]
I'm presenting this as a suggestion, because skewing RGB channels individually may not produce the desired effects to improve contrast.

**Comment by lababidi** [comment]
or use CLAHE

http://docs.opencv.org/3.1.0/d5/daf/tutorial_py_histogram_equalization.html

**Comment by pierluigiferrari** [comment]
Fixed as per your suggestion: Histogram EQ is now applied to HSV instead of RGB.
