### ISSUE TITLE
mAP and IOU Evaluation results

### ISSUE THREAD

**Issue by ilyes495** [pierluigiferrari/ssd_keras#95]
Hello,

I would like to know how I can evaluate my model trained on custom dataset? How I can get the mAP and IOU over the training and validation splits?

Thanks

**Comment by pierluigiferrari** [comment]
1. This is more of a question for some deep learning forum or StackOverflow, it has nothing to do with this particular SSD implementation.
2. You could convert your ground truth annotations to either the Pascal VOC format or the MS COCO JSON format and then use the tools I provide to compute the mAP for those formats.
3. IoU is a metric to compare two bounding boxes, not an evaluation metric for a dataset. Also note that there is no one single definition of the mAP. Different competitions compute it differently.

**Comment by sudonto** [comment]
Hi @pierluigiferrari , firstly, thank you for your hard working. At the moment, I would like to evaluate the result using official MATLAB code. Can you give me a link or clue how to use MATLAB file to assess the result. I have been searching this in StackOverflow with no luck.
Thank you.

**Comment by pierluigiferrari** [comment]
@sudonto check out chapters 7 and 8 of the [official Pascal VOC documentation](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/htmldoc/index.html). The documentation is pretty shitty when it comes to using their provided scripts, but with a bit of reading the code you should be able to get it to work. Basically, you produce the results text files that contain all the pedictions as shown in the evaluation tutorial in this repo, then you copy those results text files to the "results" folder (and to the correct subfolder, which is "Main") within the "VOCdevkit" folder, then you check out the `VOCinit.m` file in the "VOCcode" subfolder to check if it is set to the dataset you want to, and then you run this function here (create a function file inside the "VOCcode" subfolder): 

```matlab
function aps = evaluate_results()

% change this path if you install the VOC code elsewhere
%addpath([cd '/VOCcode']);

% initialize VOC options
VOCinit;

aps = zeros(VOCopts.nclasses, 1);

% train and test detector for each class
for i=1:VOCopts.nclasses
    cls=VOCopts.classes{i};
    [recall,prec,ap]=VOCevaldet(VOCopts,'comp3',cls,true);  % compute and display PR
    aps(i) = ap;
end
```

**Comment by sudonto** [comment]
Hi @pierluigiferrari , thank you for the clue. Now, I am able to run m-file to calculate PR. These are some screenshot of my result:
![bird](https://user-images.githubusercontent.com/34728756/38951873-dfe3e31a-4384-11e8-9fbc-870e2b2744d0.jpg)
![dog](https://user-images.githubusercontent.com/34728756/38951874-e010add2-4384-11e8-9282-cb9b701420ec.jpg)
I am wondering why the AP of bird class is so small, other class equals to zero (0.000). And then, there is no graph for dog class. Can you spare your time to explain these situation?

**Comment by pierluigiferrari** [comment]
An AP this low is just noise, it means that the evaluation script is finding no matches at all, which indicates that you're likely using the script incorrectly. I don't have time right now to look into this unfortunately.

**Comment by pierluigiferrari** [comment]
@sudonto I've pushed a new Python mAP evaluator, check out the Pascal VOC evaluation tutorial notebook. No more need for Matlab.

**Comment by sudonto** [comment]
@pierluigiferrari , thank you for your lates code. Actually, it's because of my trained model. When I evaluate your model trained in VOC2007, the result was just like you stated in Readme.md. Anyway, you make my life easier as you provide Python version. Thanks!
