### ISSUE TITLE
extract features from all bounding boxes

### ISSUE THREAD

**Issue by igor-87** [pierluigiferrari/ssd_keras#96]
Hi, is it possible to extract features from all bounding boxes?
I am trying to build a small search engine and for my usage, I want to detect objects in images and extract their features to make knn nearest neighbor search.
is it possible?
is there an example for this kind of task?

**Comment by pierluigiferrari** [comment]
> Hi, is it possible to extract features from all bounding boxes?

What exactly do you mean by that?

**Comment by igor-87** [comment]
thanks for your response, I am kind of new in this field, so I will try to explain a little bit more.
currently, I am using vgg19 model to pass over images and get a features map of every image.
I thought maybe I can do the same thing, using Single-Shot MultiBox Detector, to detect objects in the image and pass them to calculate the feature map using vgg 19.
is it possible to combine Single-Shot MultiBox Detector with vgg19 to extract all bounding boxes features?

**Comment by pierluigiferrari** [comment]
That's still not a well-formed question. What does "extracting feature maps" mean? Each layer of a network produces hundreds of feature maps. A feature map is just the output of a given layer. So when you say "get feature maps of every image", that doesn't mean anything, because there is no such thing as the one feature map of an image. Each output of each layer of a network represents a feature map of the input image.

**Comment by igor-87** [comment]
thank you for your response again, you are right I am a little bit confused.
I follow the next example: [link](https://tech.zegami.com/comparing-pre-trained-deep-learning-models-for-feature-extraction-c617da54641)
if I understand right I should Extract features from an intermediate layer.
will appreciate your guidance on how to build the best solution for my task.
thanks again for your help.

**Comment by pierluigiferrari** [comment]
It's not clear to me what your task is, but if you want to get the output from any of the layers of an SSD, you can just do that. The Keras documentation tells you how to get the output of any layer of the network. I think you need to spend more time trying to understand what the outputs of a given layer actually represent. I can't help you further than that.
